products/brms/_common/product.yml
This will appear in the docs-and-apis
=> RHD-546 - Business Resource Planner added to to BRMS product page

_config/site.yml, javascripts/namespace.js
See https://issues.jboss.org/browse/RHD-559 for details.
=> Prepare site.yml and namespace.js for Searchisko 2

buzz.html.slim, javascripts/buzz.js
Combined changes from https://github.com/redhat-developer/developers.redhat.com/pull/314
=> Use Searchisko v2 on Buzz pages on developers.redhat.com

README.md, _docker/control.rb
Workaround for issues running boot2docker and CA Certs
=> Boot2docker ca

Gemfile, _docker/control.rb
Clean up the gemfile. Also the bundle update should not be done at runtime for two reasons:
1.It start up process as docker can't cache it.
2.It could bring in Gem updates that are unexpected and could break thigns
=> Gemfile updates

Gemfile
@ollyjshaw made a good point that the commented out Aweplug lines were confusing. I've moved them into a comment and added a description to make this clearer.
=> Improved the clarity of the Aweplug section

javascripts/namespace.js
Needed before https://issues.jboss.org/browse/RHD-634 can be implemented.
=> Add events search URL.

_docker/searchisko_configure/Dockerfile, _docker/searchisko_configure/run.sh
Replaces my previous PR. It's easier to start again than untangle
=> Stabilise searchoisko config

_ext/stacks.rb
This is part of a larger fix, but they can be independent.
=> Fixes RHD-625 missing bom

_docker/awestruct/Dockerfile, _docker/control.rb, _docker/drupal/Dockerfile, _docker/ruby/Dockerfile
I got tripped up by a rebase again. The original PR is here. https://github.com/redhat-developer/developers.redhat.com/pull/377
=> Sharing a base Ruby install to speed up build

Rakefile
Now only removing closed pr builds from one month back to last week.
=> Enhancing the pull reaper date logic

products/eap/get-started.adoc
They should no longer be pointing to staging
=> Fixing images pointing to staging

Gemfile, Gemfile.lock, README.md, Rakefile, _smoke_tests/features/community.feature, _smoke_tests/features/downloads.feature, _smoke_tests/features/homepage.feature, _smoke_tests/features/solutions.feature, _smoke_tests/features/step_definitions/community.steps.rb, _smoke_tests/features/step_definitions/downloads.steps.rb, _smoke_tests/features/step_definitions/homepage_steps.rb, _smoke_tests/features/step_definitions/solutions.steps.rb, _smoke_tests/features/support/env.rb, _smoke_tests/smoke.rake
This does not currently affect any builds (although it could be very easily). The smoke tests need to be run in isolation with:
```
rake features
```
=> Cucumber smoke tests

devnation2015.html.slim, javascripts/vendor/ytembed.js
=> Changed script to link internally to video  RHD-695

_config/nav.yml, _layouts/base.html.slim, _layouts/developer-materials.html.slim, _layouts/get-started-item.html.slim, _layouts/video_page.html.slim, _partials/developer-materials-filters.html.slim, javascripts/developer-materials.angular.js, resources.html.slim, stylesheets/_developer-materials.scss, stylesheets/_global-wrapper.scss
Also closes RHD-670 and RHD-624
=> Created a resources page. RHD-681

_partials/getstarted-thankyou.html.slim, javascripts/terms-and-conditions.js, products/amq/get-started.adoc, products/eap/get-started.adoc, products/fuse/get-started.adoc
I combined these into one PR; however there is one issue.  Instead of saying the actual product it displays the current product instead of what is downloaded - https://github.com/redhat-developer/developers.redhat.com/blob/master/_partials/getstarted-thankyou.html.slim#L4
=> RHD-592 Fixed redirect links

Gemfile.lock, _ext/pipeline.rb
Aweplug needed an update to fix this issue. You can see the changes at
awestruct/aweplug@776158d42f685b71806b53ed628d7082475dc198
There are some other smaller dependency changes here too, looks like
mostly for typhoeus
=> Updating aweplug and other deps

Gemfile.lock, _ext/jboss_developer.rb
=> Updating aweplug && improved drupal error handling

Gemfile, Gemfile.lock, _ext/jboss_developer.rb, _ext/pipeline.rb, stylesheets/_sprites.scss, stylesheets/app.scss, stylesheets/global.scss
Reverts redhat-developer/developers.redhat.com#490
=> Revert "Feature/remove compass"

_layouts/base.html.slim
I realized now that I cast the array to a string before.  I think this should now remove some of the complexity since the for loop doesn't exit upon finding the item in the array.  I believe include? will exit if the item is in the array
=> RHD-934 - Removed the for loop to reduce the complexity.

_config/site.yml
We should get the port and the hostname here out as env variables once this has cleared the outstanding PRs.
=> Quick fix to PRs

javascripts/buzz.js, products/bpmsuite/_common/product.yml
BuzzFix - Fixed tag issues on RHD
=> BuzzFix - Fixed tag issues on RHD

products/bpmsuite/get-started.adoc
Please merge to remove links to jboss.org product pages, replaced with developer.redhat.com links.
=> Updated bpm suite product page references from jboss.org

_cucumber/cucumber.rake
PLEASE MERGE -  To avoid false successful test runs.
=> Fixing false success test results on Jenkins

products/atomic/_common/product.yml, products/datagrid/get-started.adoc, products/datavirt/_common/product.yml
Still waiting for access to the magnolia project files, but this should fix some of the errors in the mean time
=> Broken link fixes

_layouts/base.html.slim
Reverts redhat-developer/developers.redhat.com#517
=> Revert "Removing VWO again - page re-loads still occurring"

Rakefile
I didn't have a good way to push information back up into the wrap
method, so I did some c&p :(
=> First attempt at using Status API for blinkr

javascripts/namespace.js, javascripts/sso.js
This is how we specify which URL to redirect to after email confirmation.
=> RHD-1250 Email confirmation from staging redirects to production

javascripts/namespace.js, register.html.slim
For @paulrobinson's register page in PR #629
=> Allow namespace variables to be pulled in independently

Gemfile, Gemfile.lock, _layouts/base.html.slim, _layouts/video_page.html.slim, _partials/share.html.slim, _partials/video_player.html.slim, javascripts/carousel.js, javascripts/experiments.js, javascripts/social.js, javascripts/video.js, javascripts/visual.js, stylesheets/_socialite.scss, stylesheets/_videos.scss, stylesheets/app.scss
Still missing a few pieces of data - to come..
=> Video page RHD-621 WIP

products/eap/_common/product.yml
Reverts redhat-developer/developers.redhat.com#644
=> Revert "DEVELOPER-1456 - Added EAP 7.0.0.Beta to download tables"

Rakefile, _docker/lib/options.rb, _docker/test/test_options.rb
The job is set up. When this is merged I can just change jenkins to point to the main master branch 
https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/jboss.org/job/developers.redhat.com-pr_reaper/3/console
=> Rhd 941 reap prs

_docker/docker-compose.yml.erb
@paulrobinson @LightGuard I don't believe we need this, but let me know if there's something I'm missing
=> Removing elevated privileges

_cucumber/features/support/hooks.rb, _cucumber/lib/helpers/customer.rb, _cucumber/lib/pages/base_page.rb, _cucumber/lib/pages/login_page.rb
removed wip tag
removed unnecessary code.
=> adding fixes for failing production tests.

_docker/lib/options.rb, _docker/test/test_options.rb
Running from my branch 
http://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/jboss.org/job/developers.redhat.com-drupal-nightly/6/console
=> DEVELOPER-2363 creation of CI drupal task

Rakefile
This will fail the current blinkr build. Once merged we have to update the blinkr job
The results of blinkr run with this is here http://it-developers-pr.stage.redhat.com/pr/707/blinkr_test/33/report.html
The result of a jenkins build of the NEW blinkr jobs is here http://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/jboss.org/job/developers.redhat.com-blinkr/33/console
=> Developer 2367 blinkr build

_docker/docker-compose.yml.erb, _docker/lib/options.rb, _docker/test/test_options.rb
@paulrobinson Should not affect current build, but will be ready when testing of docker-pr branch is ready
=> Fix cpu usage

Rakefile, _docker/docker-compose.yml.erb
The PR status misses the unit test phase passing.
=> Env vars needed for github status

_partials/developer-materials-results.html.slim, javascripts/developer-materials.angular.js, javascripts/namespace.js
=> DEVELOPER-1992 - Omit Red Hat tags from resource finder

_cucumber/cucumber.rake
This reverts commit 8b137dc94a7a09bcefc816eac834dd94528c6543.
=> Revert "Wrapping properly"

_cucumber/features/primary_nav.feature, _cucumber/features/support/env.rb
… js causing a lot of failures. Needs removing whilst investigating.
=> urgent test fix

javascripts/topics.js, stylesheets/_topics.scss
Having difficulties with the ellipsis colors.  Also, it doesn't seem to be supported with FF.  I am currently working on a solution.
=> DEVELOPER-2567 - Topics visual updates

index.html.slim
Attempting to see what's really up with Adela's branch
=> DEVELOPER-2581 Added back Content Contributor band in homepage

products/cdk/download.adoc, products/cdk/get-started-cdk2-nodejs.adoc, products/cdk/get-started-cdk2-php.adoc, products/rhel/_common/product.yml
Reverts redhat-developer/developers.redhat.com#866
=> Revert "DEVELOPER-2680 Apply the link changes to CDK and RHEL downloads"

products/cdk/download.adoc, products/cdk/get-started-cdk2-nodejs.adoc, products/cdk/get-started-cdk2-php.adoc, products/rhel/_common/product.yml
This reverts commit fd08ba936f3355749a5324716ddf88642ff9cce3.
=> Revert "Revert DEVELOPER-2680 Apply the link changes to CDK and RHE downloads"

downloads.html.slim
Temporary fix, see comments in DEVELOPER-2774
=> DEVELOPER-2774 Fixed Download RHEL link

Gemfile.lock, _ext/pipeline.rb
Testing aweplug changes to make sure links aren't broken
=> Developer 2716 - Update Fuse Quickstarts to version 6.2.1

_layouts/product-get-started-cdk.html.slim, _layouts/product-get-started-multipath.html.slim
This is pretty urgent - the CDK downloads aren't working because the downloads /thank you box is no longer on these new page layouts
=> Reinstated thankyou box that allows downloads DEVELOPER-2875

_cucumber/features/support/env.rb
adding chrome to available browserstack drivers
=> adding chrome to available browserstack drivers

_docker/drupal/modules/custom/redhat_developers/config/install/filter.format.rhd_html.yml, _docker/drupal/run.sh, _docker/drupal/themes/custom/rhd/rhd.theme, _docker/drupal/themes/custom/rhd/templates/node--article.html.twig, _docker/drupal/themes/custom/rhd/templates/share.html.twig, _docker/drupal/themes/custom/rhd/templates/toc-responsive--article.html.twig
Layout files and small module additions within drupal
=> DEVELOPER-2885 Articles in Drupal

products/devstudio/_common/product.yml
DEVELOPER-2900 for JBDS 9.1.0.GA, set current_version: 9.1.0.GA. 
Safe to merge -- bits are live in CSP now.
=> DEVELOPER-2900 for JBDS 9.1.0.GA, set current_version: 9.1.0.GA

articles/no-cost-rhel-faq.adoc
* Add global customer service link for email contact
* Nested list format fixes
=> DEVELOPER-2932 No-cost RHEL FAQ global customer service email

_docker/drupal/themes/custom/rhd/templates/system/html.html.twig
=> DEVELOPER-2911 - Synced the index.html with html.html.twig

README.md
Minimum versions add for:
* docker
* docker-compose
* ruby
* nodejs
=> Adding minimum versions for building the site

_docker/drupal/modules/custom/redhat_developers/config/install/core.entity_view_display.node.promotion_card.default.yml, _docker/drupal/modules/custom/redhat_developers/config/install/core.entity_view_display.node.topic.default.yml, _docker/drupal/themes/custom/rhd/templates/topic/node--topic.html.twig, stylesheets/_topics.scss
As far as I can tell this is identical now, save commas between tag
listings, but that's exceptionally minor.
=> DEVELOPER-2943 Fixing styling & display of topics in Drupal

products/softwarecollections/updates.adoc
Create Updates page for Software Collections RHSCL 2.2 Beta.
=> DEVELOPER-2977 Software Collections Update Page

products/softwarecollections/get-started-rhel7-nodejs-beta.adoc, products/softwarecollections/updates.adoc
* Node.js v4  TTHW for RHSCL 2.2 Beta
* link from updates page.
=> DEVELOPER-3012 Node.js v4 (RHSCL 2.2 Beta)

_ext/jboss_developer.rb, _tests/test_drupal8service.rb
The Drupal8Service was missing a method if the first attempt failed.
=> Fixing a method missing error with my last impl

_docker/control.rb, _docker/lib/options.rb, _docker/test/test_options.rb
Reverted to starting all services with a docker-compose up to see if we can resolve the ports in use issue.
=> [#DEVELOPER-3029] Start all additional services with docker-compose up

products/cdk/_common/product.yml
Check this by ensuring https://www.youtube.com/playlist?list=PLf3vm0UK6HKot0DBAXHKQfRDjqWKxj2mK videos are in the DCP.
=> DEVELOPER-3042 CDK Product videos are not appearing on the site

products/eap/_common/product.yml
Unfortunately the URLs are now completely unpredictable for EAP, so I needed to hard-code them all in :-(
=> [DEVELOPER-3111] EAP 7 Updates: Docs and APIs

Gulpfile.js, _docker/drupal/web/themes/custom/rhd/rhd.theme, _docker/drupal/web/themes/custom/rhd/templates/system/html.html.twig, _docker/environments/drupal-dev/rhd.settings.php, _docker/environments/drupal-production/rhd.settings.php, _docker/environments/drupal-production/rhd.settings.yml.erb, _docker/environments/drupal-staging/rhd.settings.php
These were both related so I grouped them together.
=> Adding support for A/B testing & metrics

products/amq/index.html, products/bpmsuite/index.html, products/brms/index.html, products/cdk/index.html, products/datagrid/index.html, products/datavirt/index.html, products/developertoolset/index.html, products/devstudio/index.html, products/eap/index.html, products/fuse/index.html, products/mobileplatform/index.html, products/openshift/index.html, products/rhel/index.html, products/softwarecollections/index.html, products/webserver/index.html
Related to comments in the task.
=> [DEVELOPER-3080] Removed html based redirects on products index pages.

_docker/drupal/README.md
Not sure how much documentation this needs, but it seems like this fits the definition of done requirements.
=> DEVELOPER-3087 - Added diff documentation.

products/amq/overview.adoc, products/bpmsuite/overview.adoc, products/brms/overview.adoc, products/cdk/overview.adoc, products/datagrid/overview.adoc, products/datavirt/overview.adoc, products/developertoolset/overview.adoc, products/devstudio/overview.adoc, products/eap/overview.adoc, products/fuse/overview.adoc, products/mobileplatform/overview.adoc, products/openshift/overview.adoc, products/rhel/overview.adoc, products/softwarecollections/overview.adoc, products/webserver/overview.adoc
This covers the last part of content titles and descriptions update for DEVELOPER-3080
=> Filled titles and descriptions for overview product pages.

Gemfile.lock
Sections were not working with includes before, they are now.
=> Allowing asciidoctor includes for sections

.gitignore
Because some luddites, like me, still use emacs.
=> gitignore emacs backup files *~

products/eap/overview.adoc
This update needs to go live on 6/27
=> [HOLD - 6/27] DEVELOPER-3168 - Updated Overview page for EAP 7

index.html.slim
Update promos for the RHD homepage
=> https://issues.jboss.org/browse/DEVELOPER-3234

.gitignore, _cucumber/features/login_register/basic_login.feature, _cucumber/features/login_register/basic_registration.feature, _cucumber/features/login_register/social_registration.feature, _cucumber/features/primary_nav/primary_nav.feature, _cucumber/features/step_definitions/additional_information_steps.rb, _cucumber/features/step_definitions/login_steps.rb, _cucumber/features/step_definitions/navigation_steps.rb, _cucumber/features/step_definitions/register_steps.rb, _cucumber/features/support/browser.rb, _cucumber/features/support/env.rb, _cucumber/features/support/hooks.rb, _cucumber/features/support/site.rb, _cucumber/lib/helpers/github_admin.rb, _cucumber/lib/helpers/keycloak_admin.rb, _cucumber/lib/helpers/site_user.rb, _cucumber/lib/pages/additional_information_page.rb, _cucumber/lib/pages/base.rb, _cucumber/lib/pages/edit_account_page.rb, _cucumber/lib/pages/forgot_password_page.rb, _cucumber/lib/pages/github_login_page.rb, _cucumber/lib/pages/login_page.rb, _cucumber/lib/pages/register_page.rb, _cucumber/lib/pages/site_nav.rb
changes to logn/registration page.
removed ignore tag
completed updates to registration tests.
wip
added remaining scenario
Update cdn.store
fixed merge conflicts
added nightly tags to password reset tests
added new test account for keycloak API
attempting to fix selenium Net::ReadTimeout (Net::ReadTimeout) error.
minor adjustment to browser timeout
Made changes to test on mobile browsers.
=> Developer 3141 and 3140 - create/update new login/registration flows.

products/developertoolset/_common/product.yml, products/developertoolset/docs-and-apis.adoc, products/developertoolset/overview.adoc
Please merge updates reflecting the current version of DTS (docs links, product version, component names, language fixes).
=> DTS 4.1 updates

_docker/environments/drupal-production/docker-compose.yml, _docker/environments/drupal-staging/docker-compose.yml
Fixing up compose files for staging and also production
=> Fixing up compose files

_docker/lib/backup/backup.rb, _docker/tests/backup/test_backup.rb
=> [DEVELOPER-3283] Compress SQL dump from Drupal backup

products/rhel/_includes/get-started-dcr7-step3b.adoc, products/rhel/get-started-dcr7-nodejs.adoc, products/rhel/get-started-dcr7-php.adoc, products/rhel/get-started-dcr7-python.adoc, products/rhel/get-started-dcr7-ruby.adoc
* Fixed web server source file name, now parameterized
=> RHD-1632 Fix source file name error from templating

products/openjdk/overview.adoc
Specified what type of development (applications that work with JBoss MW) is supported.
=> Updated the context of development support

_docker/drupal/scripts/drupal_install_checker.rb, _docker/tests/drupal/drupal_install_checker_test.rb
If we're not building from scratch there was an issue where the cache,
and updating the db for module updates, wasn't being done. I've tried
this out on the command line it works fine.
=> Cache wasn't rebuilding in prod / staging

Gemfile.lock
All changes associated with this are in awestruct/aweplug@21c40dcab676c2059197a7e5ed5514ac09689e6f
=> DEVELOPER-3284 [Updates aweplug to fix the quickstart paths]

_docker/lib/export/drupal_page_url_list_generator.rb, _docker/lib/export/httrack_export_strategy.rb, _docker/tests/export/sitemap.xml, _docker/tests/export/test_httrack_export_strategy.rb
This PR fixes an issue with the export from the production and staging Drupal instances. With this fix hopefully all pages should now be included and re-written correctly.
=> [DEVELOPER-3317] Fix production export

_docker/lib/export/export.rb, _docker/tests/export/test_export.rb
Fixes a missing parameter in the rsync process. Regression introduced by previous work on DEVELOPER-3317.
=> [DEVELOPER-3317] Fix regression introduced into rsync process

products/dotnet/get-started.adoc
The previous instructions were written prior to RTM for .NET. This document is now up to date.
=> Updated the instructions for installing .NET on RHEL

products/datagrid/get-started.adoc
Replacing https://github.com/redhat-developer/developers.redhat.com/pull/1311/files as the link was broken.
=> RHD-1648 Fixed EAP download link

community/contributor/index.html.slim
See issues.jboss.org/browse/DEVELOPER-3330 for the full info.
We had another relative link, well two actually. I fixed both of them.
=> [DEVELOPER-3330] Broken sign-up link on contributor page in Drupal

products/datagrid/docs-and-apis.adoc
Updating supported configurations link for JDG 7.0.
=> Updated links for 7.0.

Gulpfile.js, _config/site.yml, _docker/drupal/drupal-filesystem/web/modules/custom/redhat_developers/config/install/filter.format.as_is_html.yml, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/rhd.theme, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/client-side/product_stackoverflow_template.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/client-side/search_page_template.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/client-side/stackoverflow_template.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/system/html.html.twig, _docker/drupal/scripts/run-httpd.sh, _docker/environments/drupal-dev/rhd.settings.yml, _ext/jboss_developer.rb, _tests/test_drupal8service.rb, events.html.slim, javascripts/drupal-namespace.js, javascripts/search.js, products/amq/learn.html.slim, products/bpmsuite/learn.html.slim, products/brms/learn.html.slim, products/datagrid/learn.html.slim, products/datavirt/learn.html.slim, products/devstudio/learn.html.slim, products/eap/learn.html.slim, products/fuse/learn.html.slim, products/mobileplatform/learn.html.slim, products/openshift/learn.html.slim, products/rhel/learn.html.slim, resources.html.slim, search.html.slim
Turns out all of these issues had pieces that are related, so I'm
fixing them all in one commit.
See
* https://issues.jboss.org/browse/DEVELOPER-3292
* https://issues.jboss.org/browse/DEVELOPER-3291
* https://issues.jboss.org/browse/DEVELOPER-3293
for more detail about each issue.
A good portion of these had to do with drupal fixing up hrefs in anchor
tags. That's all well and good for most things, but for pages that use
Angular, we need it to not do that, hence bringing back the as_is_html
filter. This filter is only used for pages that have the drupal_filter
set to `as_is_html`, otherwise, it uses `full_html`. A few files were
updated to include this new variable in the front matter.
There were some added client side templates in the current site which
were not added for Drupal, so I …
=> Fixes DEVELOPER-3292 DEVELOPER-3291 DEVELOPER-3293

products/openjdk/overview.adoc
Updated msi link to point to u101 (July 2016 CPU update)
=> Updated msi link to point to u101

_docker/lib/export/form_action_rewrite.rb, _docker/tests/export/test_export_form_rewrite/containers.html, _docker/tests/export/test_form_action_rewrite.rb, _ext/jboss_developer.rb, _layouts/product-get-started-fuse.html.slim, _layouts/product-get-started-old.html.slim, _partials/developer-materials-results.html.slim, resources.html.slim, search.html.slim
There's no ticket for this, but it removes some hacks we've had to put in place for the export.
@robpblake, @adelasofia please go over this and verify.
=> [DEVELOPER-3360] Switching to angular ng-href

products/cdk/overview.adoc
Please merge to fix links from CDK Overview.
=> Fix CDK docs links; misc. lang. fixes.

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/rhd.theme
Please see https://issues.jboss.org/browse/DEVELOPER-3373 for more
information.
@drupalbee would you mind taking a look at this and reviewing for me please?
=> Fixes DEVELOPER-3373 (topic promo card layout)

javascripts/search.js
Another attempt to fix the site navigation from the /search page of the export.
Search functionality on the preview site should be checked thoroughly.
=> [DEVELOPER-3359] Site navigation is broken on search page of export

products/openjdk/overview.adoc
The installer should work on any version of Windows, there is no need to say "Windows 8"
=> Changed "Windows 8" to say "Windows"

stylesheets/app.scss
Styling issue due to competing styles with Drupal.
=> Fixes DEVELOPER-3385 (tabs rendered incorrectly)

stylesheets/app.scss
I missed the second part of the ticket, sorry. @adelasofia please review
and merge if happy.
=> Fixes DEVELOPER-3385, missed vertical tabs

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/system/html.html.twig
We ultimately need to find the right Adobe DTM code, as what we have
isn't working, or if we're even using DTM any longer.
=> Fixes DEVELOPER-3368 (SO forums not working)

Gemfile.lock
@paulrobinson @LightGuard  - Waiting on https://github.com/awestruct/aweplug/pull/117 to be merged. Then this can be rebased and merged.
=> DEVELOPER-3377 - sys_url_view should point to the abstract/purchase page

_docker/drupal/drupal-filesystem/web/config/sync/field.field.node.topic.field_blue_card_description.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.topic.field_topic_sub_title.yml
3397 was actually done earlier, you can see it live in the production /
staging version of drupal now.
3395 required some small configuration changes.
=> FIXES DEVELOPER-3395 and DEVELOPER-3397

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/node--article.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/share.html.twig
These could be two separate PRs, but I figured they're both small and dealing with the same thing.
=> DEVELOPER-3419 and DEVELOPER-3415

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/system/html.html.twig, _layouts/base.html.slim
See: https://issues.jboss.org/browse/DEVELOPER-3449.
2 minute content fix, so quicker to just do it, than schedule it for next sprint.
=> DEVELOPER-3449 LOGOUT should be LOG OUT

_docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.topic.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.topic.field_blue_card_description.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_blue_card_description.yml, _docker/drupal/drupal-filesystem/web/modules/custom/redhat_developers/config/install/core.entity_view_display.node.topic.default.yml, _docker/drupal/drupal-filesystem/web/modules/custom/redhat_developers/config/install/field.field.node.topic.field_blue_card_description.yml, _docker/drupal/drupal-filesystem/web/modules/custom/redhat_developers/config/install/field.storage.node.field_blue_card_description.yml
See https://issues.jboss.org/browse/DEVELOPER-3441 for more information.
You may not see this is staging / prod until we rebuild the database.
This is actually a fix for a different issue I discovered, the blue card
description was being rendered as plain text, which isn't right. I had
to make a few other changes to it as well.
=> Fixes DEVELOPER-3441

Gemfile, Gemfile.lock, _cucumber/features/help/resources/resources_page.feature, _cucumber/features/help/stack_overflow/DEVELOPER-3035_stackoverflow.feature, _cucumber/features/help/stack_overflow/DEVELOPER-3036_stackoveflow.feature, _cucumber/features/search/search.feature, _cucumber/features/support/browser.rb, _cucumber/features/support/env.rb
=> DEVELOPER-3474 - fixing drupal resources tests

products/openjdk/overview.adoc
Updated download link to 8u102-1 MSI, added missed link in the first paragraph.
=> OpenJDK links update

stylesheets/_adaptive-placeholder.scss, stylesheets/app.scss
To be used in the RHD login form
=> DEVELOPER-3108 Added CSS for Adaptive Placeholders

products/fuse/overview.adoc
https://issues.jboss.org/browse/DEVELOPER-3527
=> Fix JBDS link for DEVELOPER-3527

README.md, _ext/jboss_developer.rb
See https://issues.jboss.org/browse/DEVELOPER-3479 for full detail.
Currently, none of the pages are set to be ignored, you'll need to do that part yourself while testing.
=> Fixes DEVELOPER-3479 (migration process)

products/cdk/overview.adoc, products/datavirt/get-started.adoc, products/developertoolset/updates.adoc, products/eap/get-started.adoc, products/fuse/overview.adoc, products/rhel/docs-and-apis.adoc, products/softwarecollections/_common/product.yml, products/softwarecollections/docs-and-apis.adoc, ticket-monster.adoc
This fixes the ticket monster page as well as a number of other broken pages.
=> DEVELOPER-3511 - Broken page reported on http://developers.redhat.com/whatisticketmonster/

stylesheets/app.scss
Resolves DEVELOPER-3473 to sync up with other RH properties
=> Increased button font-size to 16px, added line-height 1.2em

_cucumber/features/downloads/protected_downloads/eap_protected_downloads.feature, _cucumber/features/login/basic_login.feature, _cucumber/features/register/social_registration.feature, _cucumber/features/step_definitions/additional_action_steps.rb, _cucumber/features/step_definitions/register_steps.rb, _cucumber/features/support/env.rb, _cucumber/lib/helpers/github_admin.rb, _cucumber/lib/helpers/it_admin.rb, _cucumber/lib/helpers/keycloak_admin.rb, _cucumber/lib/helpers/site_user.rb, _cucumber/lib/pages/additional_action_page.rb, _cucumber/lib/pages/additional_information_page.rb, _cucumber/lib/pages/register_page.rb
=> [DEVELOPER-3438] - fixed broken social registration scenarios.

products/devstudio/overview.adoc
add link to devsuite installer
=> add link to devsuite installer

_docker/drupal/drupal-filesystem/web/config/sync/node.type.rhd_microsite.yml, _docker/drupal/drupal-filesystem/web/config/sync/node.type.rhd_solution_overview.yml, _docker/drupal/drupal-filesystem/web/config/sync/node.type.topic.yml
This fixes all the renames for content types
=> DEVELOPER-3424 DEVELOPER-3404 DEVELOPER-3400

index.html.slim
Completely replaced 1, 3, & 5
Updated artwork for 4
Fixed punctuation and updated alt-tags
=> Updating promo section

events.html.slim
Commented out slider and fixed block comment for filters from Events page
=> RHD-1769 Removed slider from Events page

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/system/html.html.twig, _docker/environments/drupal-dev/rhd.settings.yml, _docker/environments/drupal-pull-request/rhd.settings.yml.erb
https://issues.jboss.org/browse/DEVELOPER-3580
Puts the initial data object and setup for DTM integration into place on every page. Should be pointed to the unpublished profile using DPAL scripts.
=> DEVELOPER-3580 - Add DPAL script and initial DTM data object

_partials/hero1.html.slim, index.html.slim
Mongo DB -> MongoDB
Cheatsheet -> Cheat Sheet
=> Correcting typos in getstarted column

_cucumber/cucumber.rake, _cucumber/features/login/social_login.feature, _cucumber/features/search/search.feature, _cucumber/features/step_definitions/login_steps.rb, _cucumber/features/step_definitions/register_steps.rb, _cucumber/features/step_definitions/search_steps.rb, _cucumber/features/support/env.rb, _cucumber/lib/pages/abstract/site_base.rb, _cucumber/lib/pages/home_page.rb, _cucumber/lib/pages/search_page.rb, _docker/lib/options.rb, cucumber.yml
Searching for 'enterprise linux' should return 'RHEL' product pages first,
Searching for 'red hat developers' should return 'about' page first,
Boost topic-name search terms.
=>  includes tickets DEVELOPER-3077, DEVELOPER-3078, DEVELOPER-3079

_cucumber/features/downloads/downloads_page.feature, _cucumber/features/downloads/product_overview/cdk_featured_download.feature, _cucumber/features/downloads/product_overview/eap_featured_download.feature, _cucumber/features/downloads/product_overview/rhel_featured_download.feature, _cucumber/features/downloads/promotions/cheatsheet_download.feature, _cucumber/features/downloads/protected_downloads/cdk_protected_downloads.feature, _cucumber/features/downloads/protected_downloads/eap_protected_downloads.feature, _cucumber/features/downloads/protected_downloads/rhel_protected_downloads.feature, _cucumber/features/login/basic_login.feature, _cucumber/features/login/social_login.feature, _cucumber/features/register/basic_registration.feature, _cucumber/features/register/social_registration.feature
added tags for both keycloak and download-manager related scenarios.
=> adding tags for tests related to keycloak and download manager.

products/openjdk/overview.adoc
Updated download link to 8u111 MSI
=> OpenJDK 8u111 link update

products/openjdk/overview.adoc
Added title. Please let me know if I need to create a JIRA issue for this change.
=> Add title for OpenJDK overview

_docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.promotion_page.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.promotion_page.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.promotion_page.teaser.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.promotion_page.field_mail_to_link.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_mail_to_link.yml, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/promotion-page/field--field-mail-to-link.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/promotion-page/node--promotion-page.html.twig, stylesheets/_microsite.scss
https://issues.jboss.org/browse/DEVELOPER-3550
=> DEVELOPER-3550 SOLP mobile layout and css changes

javascripts/sso.js
https://issues.jboss.org/browse/DEVELOPER-3643
Creates async user login from keycloak information includes keycloak ID, social accounts linked, and days since registration
=> DEVELOPER-3643 - Implement User logic

javascripts/sso.js
https://issues.jboss.org/browse/DEVELOPER-3643
Just a small change for the Adobe DTM user object from feedback from Emeel and Mark
=> DEVELOPER-3643 - Remove profileID value

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/rhd.theme, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/system/html.html.twig, javascripts/search.js
https://issues.jboss.org/browse/DEVELOPER-3642
Updates for Adobe DTM logic. Corrects items found here: https://docs.google.com/document/d/1YcIevNsG0tutjNJP5tQQ01Tid4flusVpjiuNWiAsZfA/edit
=> DEVELOPER-3642 - Implement Forms and Events logic

products/softwarecollections/updates.adoc
Edits to the SCL Updates pages are for the new V2.3 release.
=> [HOLD 15th NOV] Update for RHSCL updates page for v2.3.adoc

products/developertoolset/updates.adoc
These changes are to accommodate DTS v6.
=> [HOLD - 15th NOV] Update DTS updates page for v6.adoc

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/rhd.theme, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/system/html.html.twig
Quick fix to remove the server-side base_url value because it doesn't function with export.
=> DEVELOPER-3642 - Remove server-side base_url

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/rhd.theme, _docker/environments/drupal-pull-request/docker-compose.yml, _docker/environments/drupal-pull-request/rhd.settings.yml.erb
https://issues.jboss.org/browse/DEVELOPER-3679
Sets rhd_base_url and rhd_final_base_url in docker_compose file and then provides those via the Drupal Theme to the drupalSettings object in JavaScript
=> [HOLD] DEVELOPER-3679 - Provide environment URLs to Front-end

products/cdk/overview.adoc, products/cdk/resources.adoc
Please merge to
- update a number of old links to CDK-related docs
- fix a bit of mark-up
=> CDK docs fixes

_cucumber/features/step_definitions/resources_steps.rb, _cucumber/features/step_definitions/topics.rb, _cucumber/features/topics/developer_3654_white_cards.feature, _cucumber/lib/helpers/driver_helper.rb, _cucumber/lib/pages/abstract/generic_base_page.rb, _cucumber/lib/pages/resources_page.rb
=> DEVELOPER-3681 - Investigate & fix failing Resource/Topics tests

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/rhd.theme, javascripts/downloads.js, javascripts/search.js, javascripts/sso.js, javascripts/terms-and-conditions.js, javascripts/vendor/keycloak.js
https://issues.jboss.org/browse/DEVELOPER-3680
Includes fixes for search refinement, contentID, error messaging, and a few JS errors
=> DEVELOPER-3680 - Implement Custom Events for additional Use Cases and Fix Bugs

_docker/lib/export/static_export_rsync.rb, _docker/tests/export/test_static_export_rsync.rb
Adding a new `apidocs` directory and setting it to protect in the rsync.
Hoping this doesn't clobber things already existing.
=> Adding in apidocs for javadoc

index.html.slim
This should remove the mixed-content warnings on the homepage.
=> Forcing rebuild of homepage

_docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.paragraph.docs_and_apis.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.paragraph.get_started.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.paragraph.overview.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.paragraph.get_started.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/editor.editor.rhd_html.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.paragraph.docs_and_apis.field_overview_url.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.paragraph.get_started.field_secondary_content.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.paragraph.overview.field_product_overview_features.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_product_summary.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_product_technology_group.yml, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/templates/product-pages.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/paragraph/paragraph--get-started.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/paragraph/paragraph--overview.html.twig, stylesheets/_get-started.scss
Fixes for small changes that have been found
=> More product page changes

_ext/jboss_developer.rb
This should force a rebuild of the pages to Drupal so all the https
fixes go in.
=> Pushing every page (unless ignored) to Drupal

_ext/jboss_developer.rb
Reverts redhat-developer/developers.redhat.com#1655
=> Revert "Pushing every page (unless ignored) to Drupal"

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/paragraph/paragraph--download.html.twig, javascripts/buzz.js
Please see https://issues.jboss.org/browse/DEVELOPER-3719 (and apparently https://issues.jboss.org/browse/DEVELOPER-3718) for full details and definition of done
=> DEVELOPER-3719 buzz tag filtering

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/paragraph/paragraph--help.html.twig
Please see https://issues.jboss.org/browse/DEVELOPER-3720 for full info and definition of done.
I missed a class in the template if there is no Stack Overflow page,
this adds that class in if needed.
=> Fixes DEVELOPER-3720 single column forum help

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/paragraph/download_thankyou.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/paragraph/paragraph--download.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/paragraph/paragraph--get-started.html.twig
Looks like I was missing the download thank you on the get started page.
=> Fixes DEVELOPER-3729 Downloads not working

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/paragraph/paragraph--connectors.html.twig
Please see https://issues.jboss.org/browse/DEVELOPER-3737 for full
information and testing.
I decided to comment things out in case we want to bring back featured connectors.
=> Fixing DEVELOPER-3737 Connectors displaying twice

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/paragraph/paragraph--help.html.twig
See https://issues.jboss.org/browse/DEVELOPER-3740 for full details.
=> Fixing DEVELOPER-3740 SO links and angular issue

Gulpfile.js, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.paragraph.getting_started_section.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.paragraph.getting_started_section.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.paragraph.getting_started_section.field_support_progress.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.paragraph.field_support_progress.yml, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/rhd_common.module, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/templates/get-started-tabs.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/paragraph/paragraph--get-started.html.twig, javascripts/terms-and-conditions.js, stylesheets/app.scss
All products now have collapsible panels and can include steps that can
be checked off.
Please see https://issues.jboss.org/browse/DEVELOPER-3738 for full details.
=> Fixing DEVELOPER-3738 (rhel get started)

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/system/html.html.twig, javascripts/sso.js
Fixes
- Download event firing without an actual download
- URL parsing to correct incorrect pageName and categories
=> Fixes for issues found during analytics training

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/system/html.html.twig, javascripts/sso.js
Reverts redhat-developer/developers.redhat.com#1696
=> Revert "Fixes for issues found during analytics training"

index.html.slim
Reduced the image size of the promos to 375px wide and processed them to reduce page weight.
=> Promo image size reduction

_cucumber/features/register/basic_registration.feature, _cucumber/features/step_definitions/common/navigation_steps.rb, _cucumber/features/step_definitions/technologies_steps.rb, _cucumber/lib/pages/abstract/site_base.rb, _cucumber/lib/pages/login_page.rb
=> Developer 3710 - Modify KeyClaok tests so that they can be ran without a d.r.c website	

_docker/environments/drupal-dev/rhd.settings.yml, _docker/environments/drupal-pull-request/rhd.settings.yml.erb
=> Update Sentry.io raven script to latest version

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/system/html.html.twig, javascripts/sso.js
https://issues.jboss.org/browse/DEVELOPER-3770
Sets the Adobe DTM registered flag on the user based on the existence of the rhd_member cookie.
=> DEVELOPER-3770 - Set registered flag based on rhd_member cookie

javascripts/sso.js
https://issues.jboss.org/browse/DEVELOPER-3693
Fixes Math.trunc and also localStorage checking
=> DEVELOPER-3693 - IE-incompatible JS function Math.trunc

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/paragraph/paragraph--help.html.twig
Please see 
* https://issues.jboss.org/browse/DEVELOPER-3731
* https://issues.jboss.org/browse/DEVELOPER-3736
for further information and a definition of done.
Decided to do DEVELOPER-3736 while I was in there and this incorporates
a lot of the work needed for it anyway.
SO section now takes up the full allotted width if there are no forums.
Also if it is full width we're displaying two columns and eight
questions instead of one column and four questions.
If there is no forum link and no SO to display we're no longer
displaying "Community Q&A".
=> Fixes DEVELOPER-3731 and DEVELOPER-3736 (Help page tickets)

_docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/rhd_common.module
Please see https://issues.jboss.org/browse/DEVELOPER-3787 for full information.
=> Fixes DEVELOPER-3787 incorrect tab id generation

_docker/drupal/drupal-filesystem/web/config/sync/paragraphs.paragraphs_type.get_started.yml, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/rhd_common.install, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/src/Controller/ProductPageController.php, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/paragraph/paragraph--get-started.html.twig
* Left link now has '!' at the end
* Title of the "Hello World" page has '!' at the end
=> DEVELOPER-3688 Fixing up some stuff Rob found

resources.html.slim
See https://issues.jboss.org/browse/DEVELOPER-3754
=> DEVELOPER-3754 Resources page header - fix typo to "Great"

stylesheets/_topics.scss
https://issues.jboss.org/browse/DEVELOPER-3536
Blue area should have the appropriate background.
=> DEVELOPER-3536 - Add style for background on microservices topic

_docker/drupal/drupal-filesystem/web/config/sync/system.file.yml
Stop gap for images disappearing
=> Stop gap for images disappearing

forums.html.slim
https://issues.jboss.org/browse/DEVELOPER-3827
Updates the text to match the JIRA issue above.
=> DEVELOPER-3827 - Update description on the Forums page for read only forums.

stylesheets/app.scss
Temporary PR, needed for review of [ DEVELOPER-3837](https://issues.jboss.org/browse/DEVELOPER-3837). Will close and open a new one with the CSS only once approved.
=> DEVELOPER-3837 EU Cookie Banner Styles

Gulpfile.js, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/templates/get-started-tabs.html.twig, javascripts/products.js
https://issues.jboss.org/browse/DEVELOPER-3817
Resolves an issue where Angular doesn't like having multiple ng-app directives on a single page.
=> DEVELOPER-3817 - Move AngularJS app scope to parent div for product get started

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/system/html.html.twig
[DEVELOPER-3788 Update hyperlink behavior in footer](https://issues.jboss.org/browse/DEVELOPER-3788)
- Links within the footer conform to the "Hyperlink Behaviours" section of [this document](https://docs.google.com/document/d/1bAb9MkrLW34wtk4RtrYvqLylXnvWhS81aDHAjhSzxMQ/edit#heading=h.99lcm8fwu7q1).
=> DEVELOPER-3788 Updated footer hyperlinks

_docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/templates/product-pages.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/paragraph/paragraph--buzz.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/paragraph/paragraph--community.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/paragraph/paragraph--connectors.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/paragraph/paragraph--docs-and-apis.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/paragraph/paragraph--download.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/paragraph/paragraph--get-started.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/paragraph/paragraph--help.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/paragraph/paragraph--overview.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/paragraph/paragraph--resources.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/paragraph/paragraph--updates.html.twig, stylesheets/_products.scss
Jira: [DEVELOPER-3828 Update Product title bar styles](https://issues.jboss.org/browse/DEVELOPER-3828)
- The grey background and large page title has been removed.
- The page now matches that of the expected image: https://issues.jboss.org/secure/attachment/12410403/product_mobile_revise.png
=> DEVELOPER-3828 Updated Product title bar styles

_partials/hero1.html.slim, stylesheets/_home.scss
[DEVELOPER-3900](https://issues.jboss.org/browse/DEVELOPER-3900) - New Hero for RHD Homepage to go live on Monday, Feb 20 2017
=> [MERGE MONDAY FEB. 20] DEVELOPER-3900 Homepage hero for Edson's book

_docker/drupal/drupal-filesystem/web/config/sync/views.view.connectors_rest_export.yml, _docker/drupal/drupal-filesystem/web/config/sync/views.view.events_rest_query.yml
Added "authored on" to the view export so that searchisko can obtain a sys_created date.
=> DEVELOPER-3809 - Updated sys_created view for consistency in Searchisko

stylesheets/_colours.scss, stylesheets/_judcon-brno.scss, stylesheets/_stackoverflow.scss, stylesheets/app.scss, stylesheets/foundation/components/_panels.scss
Jira: [DEVELOPER-3748](https://issues.jboss.org/browse/DEVELOPER-3784)
- Colours, focus, and hover state (including paragraph treatment) have been updated to confirm with the "In the future, all Red Hat web properties should:" section of [this document.](https://docs.google.com/document/d/1bAb9MkrLW34wtk4RtrYvqLylXnvWhS81aDHAjhSzxMQ/edit#heading=h.o66oxl6insgl)
=> DEVELOPER-3784 Updates hyperlinks' colors

_cucumber/features/help/resources/resources_page.feature, _cucumber/features/step_definitions/footer_steps.rb, _cucumber/lib/pages/abstract/site_base.rb
Fixed non passing/failing test. .present? returns true or false. Added an assertion, and to keep things consistent added footer element to site base.
=> DEVELOPER-3801 - test fixes

javascripts/search.js, search.html.slim
Jira: [DEVELOPER-3555](https://issues.jboss.org/browse/DEVELOPER-3555)
- Videos: Any videos on the site (has /video/ in the URL) should have the results type of "VIDEO" instead of "WEBPAGE".
- Forum: Change to "FORUM THREAD" instead of "FORUM". This makes it more consistent with BLOG POST.
- Events: Any event pages on the site (has /events/ in the URL) should have the results type of "EVENT".
To review Videos and Forum labels: https://developers-pr.stage.redhat.com/pr/1780/export/search/?q=eap
To review Events label: https://developers-pr.stage.redhat.com/pr/1780/export/search/?q=eap
=> DEVELOPER-3555 Updated search results metadata

_docker/drupal/drupal-filesystem/composer.json, _docker/drupal/drupal-filesystem/composer.lock, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.video_resource.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.video_resource.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.video_resource.teaser.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.extension.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.video_resource.field_duration.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.video_resource.field_likes.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.video_resource.field_video_target_product.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.video_resource.field_video_thumbnail_url.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.video_resource.field_views.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_duration.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_likes.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_video_target_product.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_video_thumbnail_url.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_views.yml, _docker/drupal/drupal-filesystem/web/config/sync/views.view.video.yml
Please see https://issues.jboss.org/browse/DEVELOPER-3852 for full information.
=> DEVELOPER-3852 View/REST export for videos

_docker/drupal/drupal-filesystem/composer.json, _docker/drupal/drupal-filesystem/composer.lock, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/rhd_common.module
Please see https://issues.jboss.org/browse/DEVELOPER-3857 for full information.
For testing:
* go into adding a new video (don't actually save it though as emails will probably be sent) 
* paste in a YouTube URL (either a https://youtu.be or regular URL)
* move off the element to kick off the ajax call
* ensure all fields save Speakers have been auto-populated
=> DEVELOPER-3857 YouTube API integration

README.md
This includes - https://issues.jboss.org/browse/DEVELOPER-3855
=> DEVELOPER-3910 - Added documentation for creating new content

_docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.video_resource.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.video_resource.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.video_resource.field_video_publish_date.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_video_publish_date.yml, _docker/drupal/drupal-filesystem/web/config/sync/views.view.video.yml, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/rhd_common.module
Also adding the ajax command to do it and the view portion of it as
well.
=> Adding the published field to videos

_docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.cheat_sheet.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.cheat_sheet.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.cheat_sheet.teaser.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.cheat_sheet.body.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.cheat_sheet.field_cheat_sheet_author.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.cheat_sheet.field_cheat_sheet_download_url.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.cheat_sheet.field_cheat_sheet_image.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.cheat_sheet.field_cheat_sheet_tags.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_cheat_sheet_author.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_cheat_sheet_download_url.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_cheat_sheet_image.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_cheat_sheet_tags.yml, _docker/drupal/drupal-filesystem/web/config/sync/node.type.cheat_sheet.yml, _docker/drupal/drupal-filesystem/web/config/sync/pathauto.pattern.cheat_sheet.yml, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/node--cheat-sheet.html.twig, javascripts/sso.js, stylesheets/_cheat-sheet.scss, stylesheets/app.scss
[DEVELOPER-3844](https://issues.jboss.org/browse/DEVELOPER-3844) - Created "Cheat Sheets" Content Type
The Cheat Sheet instances will be present under the https://develpers.redhat.com/cheat-sheet/<name>" URL.
=> DEVELOPER-3844 Created cheat-sheet content type

_cucumber/features/step_definitions/technologies_steps.rb
URL changes in Drupal have resulted in the tests failing. This is an attempted fix.
=> [DEVELOPER-3871] Fixed technologies tests URL checks

search.html.slim, stylesheets/_search.scss
[DEVELOPER-3961](https://issues.jboss.org/browse/DEVELOPER-3961):
Limited the hight of search results' descriptions to two lines, truncated with ellipses if longer.
=> DEVELOPER-3961 Fixed height of search results

about/index.html.slim
Added ignore_export:true to About page, which was removed as part of #1809
=> Added ignore_export to About page

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/system/html.html.twig
Environment string needs to be quoted.
=> Sentry Update - Quote environment string

stylesheets/app.scss
[DEVELOPER-3974](https://issues.jboss.org/browse/DEVELOPER-3974)
Added styles for CTAs according to the brand guide
=> DEVELOPER-3974 Added styles for CTAs

_partials/hero1.html.slim, stylesheets/_home.scss
Jira: [RHD-1971](https://issues.jboss.org/browse/RHD-1971)
Added RHEL anniversary hero.
[Mockup](http://design.jboss.org/redhatdeveloper/marketing/nocost_birthday/website/images/RHDP_hero_rhelbirthday_r1v1.png)
=> [URGENT] RHD-1971 Added RHEL anniversary Hero

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/paragraph/paragraph--download.html.twig
[DEVELOPER-4010](https://issues.jboss.org/browse/DEVELOPER-4010) Added text to the Product Download pages
=> DEVELOPER-4010 Added text to product download pages

_partials/hero1.html.slim, index.html.slim, stylesheets/_home.scss
DO NOT MERGE UNTIL MONDAY. APRIL 24TH
[DEVELOPER-4030](https://issues.jboss.org/browse/DEVELOPER-4030)
Mockup: http://design.jboss.org/redhatdeveloper/marketing/summit_2017/website/images/RHDP_hero_summit_r1v1.png
=> DEVELOPER-4030 Added RHD hero for Summit

_docker/drupal/drupal-filesystem/web/config/sync/views.view.cheat_sheets_rest_export.yml
To test: Follow video demo: https://www.dropbox.com/s/s232vngxqsqjibd/Screencast_04-25-2017_11%3A31%3A21%20AM.webm?dl=0
Notice that the fields "nid", "created" and "path" now exist. We need these for the "sys_created", "id" and "sys_url_view" values in the DCP configuration.
=> DEVELOPER-3846 - Part 1: Updated rest export view for necessary dcp information

Gulpfile.js, _docker/drupal/drupal-filesystem/web/robots.txt, javascripts/verify-member.js, stylesheets/_verify.scss, stylesheets/app.scss
https://issues.jboss.org/browse/DEVELOPER-4031
Existing member should receive an affirmative upon press of enter or blur of the input field. Non-member should receive negative and registration link upon press of enter or blur of the field.
Content must be added and directed to /verify-member
=> DEVELOPER-4031 - New webpage to verify program membership

_docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/src/Controller/ProductPageController.php
Only the latest published version and its related paragraphs should be
displayed.
JIRA: https://issues.jboss.org/browse/DEVELOPER-3987
Testing this is going to be a little bit tricky. You'll need to modify the hello world section of a product page to add another tab, save a draft, then either in another session as an anonymous user navigate to that hello world page to make sure that new tab does not display. You can then publish that edit and verify it does show up to anonymous users.
Ideally, this would all be done with an instance of data that doesn't send emails to the actual users :) Feel free to ask me how you would do that if you need to know (the command is drush sqlsan).
=> DEVELOPER-3987 Fix loading only current published

stylesheets/_verify.scss
Adds some margin under the text box to space the new button properly, and adds a border to delineate the response section
=> DEVELOPER-4031 - [update] Adjust styles from feedback

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/system/html.html.twig
@LightGuard I created this PR with just the mega menu change. The other pages in the other PR might be interferring with the tests, so for priority reasons I want to see if just this change passes the tests.
Since Ian made the mega menu tests dynamic, I didn't have to update them.
=> DEVELOPER-4060 Added RHAMT to mega menu

_docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/src/Controller/ProductPageController.php
Please see https://issues.jboss.org/browse/DEVELOPER-4063 for the full issue and testing.
=> DEVELOPER-4063 - Permission check

_partials/hero1.html.slim, index.html.slim, stylesheets/_home.scss
Opening this PR for approval. DO NOT MERGE before Tuesday May 2nd, 9:30 AM Boston time.
[DEVELOPER-4055 ](https://issues.jboss.org/browse/DEVELOPER-4055) - Added RHD hero for OSIO and [RHD-1964](https://issues.jboss.org/browse/RHD-1964?_sscc=t) updated promo for summit.
Will close this PR once approved and reopen on Monday.
=> [HOLD - Merge Tuesday 05/02, 9:30 AM ET] DEVELOPER-4055, RHD-1964 -  RHD hero for OSIO, promo for summit

index.html.slim
**ATTENTION: Please merge this into production on Wednesday May 3rd, 2017**
=> [HOLD - Merge Wed. 05/03] Update index.html.slim

_config/categories.yml, _cucumber/features/step_definitions/technologies_steps.rb, products/rhamt/_common/product.yml, products/rhamt/overview.adoc
[DEVELOPER-4060](https://issues.jboss.org/browse/DEVELOPER-4060)
Added RHAMT - "Red Hat Application Migration Toolkit" to:
- /products/
- /downloads/
=> DEVELOPER-4060 Added RHAMT to products and downloads pages

_config/categories.yml, _cucumber/features/register/basic_registration.feature, _cucumber/features/register/social_registration.feature, _cucumber/features/step_definitions/additional_action_steps.rb, _cucumber/features/step_definitions/common/navigation_steps.rb, _cucumber/features/step_definitions/edit_account_steps.rb, _cucumber/features/step_definitions/register_steps.rb, _cucumber/features/step_definitions/technologies_steps.rb, _cucumber/features/technologies/technologies.feature, _cucumber/features/user_profile/user_profile_edit.feature, _cucumber/lib/pages/additional_action_page.rb, _cucumber/lib/pages/edit_account_page.rb, _cucumber/lib/pages/register_page.rb, products/rhamt/_common/product.yml, products/rhamt/overview.adoc
This PR fixes failing KC test scenarios.
=> Fixes for broken registration tests.

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/system/html.html.twig, _docker/environments/drupal-pull-request/rhd.settings.yml.erb, javascripts/search.js
Updates PR Sentry environment to the most recent build and removes a dependency on DTM for some scripts to work by making the custom event sender global regardless of DTM being active.
=> [FIX] - Update Sentry, move custom event call

_docker/drupal/drupal-filesystem/db-migrations/20170512203354_rhamt_fix.php, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/src/Controller/ProductPageController.php
I have already created a new version of the product page ready to go.
This change "deletes" the old version of the product page and publishes
the version I created.
It also fixes an issue where we may pull deleted product pages and
display them, which wouldn't be good at all.
=> [URGENT] - Attempting to fix rhamt revert issues

stylesheets/_home.scss
Adds https for home page image
=> [FIX] Fix non-secure image reference

_docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.scheduled_update.multiple_node_embargo.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/editor.editor.rhd_html.yml, _docker/drupal/drupal-filesystem/web/config/sync/filter.format.rhd_html.yml, _docker/drupal/drupal-filesystem/web/config/sync/user.role.article_creator.yml, _docker/drupal/drupal-filesystem/web/config/sync/user.role.article_reviewer.yml, _docker/drupal/drupal-filesystem/web/config/sync/user.role.books_creator.yml, _docker/drupal/drupal-filesystem/web/config/sync/user.role.books_reviewer.yml, _docker/drupal/drupal-filesystem/web/config/sync/user.role.connectors_creator.yml, _docker/drupal/drupal-filesystem/web/config/sync/user.role.connectors_reviewer.yml, _docker/drupal/drupal-filesystem/web/config/sync/user.role.events_creator.yml, _docker/drupal/drupal-filesystem/web/config/sync/user.role.events_reviewer.yml, _docker/drupal/drupal-filesystem/web/config/sync/user.role.product_creator.yml, _docker/drupal/drupal-filesystem/web/config/sync/user.role.product_reviewer.yml, _docker/drupal/drupal-filesystem/web/config/sync/user.role.promotion_card_creator.yml, _docker/drupal/drupal-filesystem/web/config/sync/user.role.promotion_card_reviewer.yml, _docker/drupal/drupal-filesystem/web/config/sync/user.role.promotion_page_creator.yml, _docker/drupal/drupal-filesystem/web/config/sync/user.role.promotion_page_reviewer.yml, _docker/drupal/drupal-filesystem/web/config/sync/user.role.rhd_microsite_creator.yml, _docker/drupal/drupal-filesystem/web/config/sync/user.role.rhd_microsite_reviewer.yml, _docker/drupal/drupal-filesystem/web/config/sync/user.role.rhd_solution_overview_creator.yml, _docker/drupal/drupal-filesystem/web/config/sync/user.role.rhd_solution_overview_reviewer.yml, _docker/drupal/drupal-filesystem/web/config/sync/user.role.topic_creator.yml, _docker/drupal/drupal-filesystem/web/config/sync/user.role.topic_reviewer.yml, _docker/drupal/drupal-filesystem/web/config/sync/user.role.video_resource_creator.yml, _docker/drupal/drupal-filesystem/web/config/sync/user.role.video_resource_reviewer.yml
Also making the rhd_html the format for all non-admin users.
=> Adding back in WYSIWYG editor video button

stylesheets/_header.scss
[DEVELOPER-3746](https://issues.jboss.org/browse/DEVELOPER-3746)
Updated active and hover states for links in the mega menu (topics, technologies, community, help, and downloads)
Active state: #ffbb11 
Hover state: #242424
=> DEVELOPER-3746 Changed active/hover states for mega menu

_docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/src/Controller/ProductPageController.php
JIRA: https://issues.jboss.org/browse/DEVELOPER-4022
If we don't have any revisions for a product or don't have an
active_paragraph/subpage throw a NotFoundHttpException. This will stop
the PHP errors and send a 404 back to the user, which is probably what
we want to have happen anyway.
The easiest way to test this would be to pull it in locally and run drupal, then go to a product that doesn't exist and a subpage that doesn't exist in an actual product (and for completeness a fake subpage in a product that is also fake). You'd then look for exceptions in the running HTTP server.
=> DEVELOPER-4022 - Throw exceptions if empty/null

_docker/drupal/drupal-filesystem/web/config/sync/views.view.video.yml
The REST export for videos needed to be modified to for indexing by DCP.
Changes can be viewed here: <base_url>/admin/structure/views/view/video
=> VideoViewUpdates - Updated the views to sync with DCP

_docker/drupal/drupal-filesystem/web/config/sync/workbench_email.workbench_email_template.back_to_draft.yml, _docker/drupal/drupal-filesystem/web/config/sync/workbench_email.workbench_email_template.published.yml, _docker/drupal/drupal-filesystem/web/config/sync/workbench_email.workbench_email_template.ready_for_review.yml, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/rhd_common.module, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/rhd_common.tokens.inc
JIRA: https://issues.jboss.org/browse/DEVELOPER-4013
This isn't the easiest of things to test, unfortunately, well, at least not without spamming people. You to /admin/help/token to check the token is properly installed under 'Node'. You'll have edit one of the workbench moderation templates to also send it to administrators, or add yourself to the Content Team Role. Once that's done you'll need to go through and create some content or change and run it through the workflow pipeline. I suggest creating a new article and running it through the various workflow steps to ensure the emails are sent correctly, at least I think emails are sent from the PR environments. 
In the emails, you'll see a 'by <user name>' in the second sentence.
=> DEVELOPER-4013 moderation transition tokens in email

_partials/hero1.html.slim, stylesheets/_home.scss
[DEVELOPER-4058](https://issues.jboss.org/browse/DEVELOPER-4058) - Added RHD hero for Advanced Linux Cheat Sheet
=> DEVELOPER-4058 Added hero for Advanced Linux Cheat Sheet

javascripts/sso.js
Adds a script to redirect to login for any URL with /login
=> DEVELOPER-3946 - Create developers.redhat.com/login link and redirect

_cucumber/features/downloads/downloads_page.feature, _cucumber/features/step_definitions/common/navigation_steps.rb, _cucumber/features/step_definitions/smoke_tests.rb.rb, _cucumber/lib/pages/register_page.rb
Smoke tests were failing due to minor change to registration page.
=> Fixed production smoke tests

stylesheets/_topics.scss
HACKATHON -- [DEVELOPER-4092 Fixed blue box on .net topic page](https://issues.jboss.org/browse/DEVELOPER-4092)
Issue: Blue box was truncating content on smaller windows.
=> DEVELOPER-4092 Fixed blue box on .net topic page

javascripts/visual.js
JIRA: https://issues.jboss.org/browse/DEVELOPER-3581
Test: Go to an article page, notice there's no number in the fragment
part of the URL.
=> DEVELOPER-3581 Fixing bookmarking toc in articles

_docker/drupal/drupal-filesystem/web/config/sync/editor.editor.rhd_html.yml
Media should now only have media Browser and Node Browser.
Block formatting should include Block quote, formatting, and styles
Tools should only include source and maximize
Layout should include Layouts, Table, and justifications
=> Rearranging editor buttons

_docker/drupal/drupal-filesystem/web/config/sync/user.role.content_team.yml
Content Team members cannot see all unpublished content.
Tiffany may create an issue for this, but I don't have one yet.
=> [URGENT] Update user.role.content_team.yml

_docker/drupal-data/README.md, _docker/environments/README.md, _docker/lib/backup/README.md, _docker/lib/backup/reset/README.md, _docker/lib/export/README.md, _docker/lib/pull_request/README.md, _docker/lib/rollback/README.md, _docker/lib/staging-sync/README.md
As part of the hand-over to Lukas, this PR simply updates many of the README.md for build related code to ensure that the documentation is correct and complete.
For reviewers:
* Have a read and make sure it all makes sense.
=> [DEVELOPER-4036] Update README.md for build related code

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/system/html.html.twig, _tests/karma/e2e/README.md, _tests/karma/unit/README.md, _tests/karma/unit/rhdp-search/rhdp-search-app_spec.js, _tests/karma/unit/rhdp-search/rhdp-search-box_spec.js, _tests/karma/unit/rhdp-search/rhdp-search-filter-group_spec.js, _tests/karma/unit/rhdp-search/rhdp-search-filter-item_spec.js, _tests/karma/unit/rhdp-search/rhdp-search-filters_spec.js, _tests/karma/unit/rhdp-search/rhdp-search-query_spec.js, _tests/karma/unit/rhdp-search/rhdp-search-result-count_spec.js, _tests/karma/unit/rhdp-search/rhdp-search-result_spec.js, _tests/karma/unit/rhdp-search/rhdp-search-results_spec.js, _tests/karma/unit/rhdp-search/rhdp-search-sort-page_spec.js, javascripts/build.js, karma.conf.js, package.json, typescript/rhdp-search/rhdp-search-app.ts, typescript/rhdp-search/rhdp-search-filters.ts
https://issues.jboss.org/browse/DEVELOPER-4195
Holding for the build to be able to test with IE11 as I can't get a local build to work at the moment.
=> DEVELOPER-4195 - Error when removing facets - IE11

_docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/src/Controller/ProductPageController.php, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/templates/product-pages.html.twig
https://issues.jboss.org/browse/DEVELOPER-3980
=> DEVELOPER-3980 - Remove Mobile CTAs from product pages with broken links

_docker/lib/export/static/rhdp-apps/devnationlive/index.html, javascripts/build.js, typescript/devnation-live/devnation-live.ts
=> DEVELOPER-4246 - Updates

stylesheets/_colours.scss, stylesheets/_header.scss, stylesheets/_home.scss, stylesheets/app.scss
[DEVELOPER-4217 - Hyperlink color updates for RHDP main site](https://issues.jboss.org/browse/DEVELOPER-4217)
All of the changes requested in the Jira had already been implemented; the only change that was needed and in this PR was the following:
In dark backgrounds (black or dark gray): use link color #73BCF7 - Hover = #2B9AF3
=> DEVELOPER-4217 Hyperlink color updates

_docker/lib/export/static/clicktale/ctIframe.htm
https://issues.jboss.org/browse/DEVELOPER-4305
Need this so ClickTale people can track between RHDP and OSO
=> Add Clicktale Frame HTM for Cross-site tracking

_docker/lib/export/static/rhdp-apps/devnationlive/index.html
Code completion error with document.getElementsByName should be getElementsByTagName
=> [FIX] DEVELOPER-4246 - Fix autocompleted function

_partials/hero1.html.slim, stylesheets/_home.scss
[DEVELOPER-4315 - Implement Hero for "Intro to EAP 7 Cheat Sheet"](https://issues.jboss.org/browse/DEVELOPER-4315)
=> [MERGE MONDAY 07/21] DEVELOPER-4315 Hero for "Intro to EAP 7 Cheat Sheet"

javascripts/build.js, typescript/rhdp-search/rhdp-search-app.ts, typescript/rhdp-search/rhdp-search-query.ts
To review - Follow https://issues.jboss.org/browse/DEVELOPER-4213
You will need to use the Omnibus app to view evar41. I had to confirm the "privacy alert" for adobe before the omnibus console would populate for this PR.  To do that, open the dpal link in a separate tab and confirm (Chrome Users).
=> DEVELOPER-4213 - Remove + sign from search box on results page

stylesheets/_searchapp.scss
[DEVELOPER-4304 - OneBox Styling](https://issues.jboss.org/browse/DEVELOPER-4304)
Added styles for OneBox.
Styles won't affect anything until [DEVELOPER-4302](https://issues.jboss.org/browse/DEVELOPER-4302) is completed.
=> DEVELOPER-4304 Added OneBox styles

_cucumber/features/primary_nav/primary_nav.feature, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/system/html.html.twig
https://issues.jboss.org/browse/DEVELOPER-4298
=> DEVELOPER-4298 - Update RHD Topics pull down to be .NET Core

products/openshift/_common/product.yml
As per Erik Jacobs, the download link for OpenShift needs to be updated
=> Updating the download link for OpenShift

CONTRIBUTING.md, javascripts/drupal-namespace.js
[DEVELOPER-4347 - Update product Stack Overflow tags](https://issues.jboss.org/browse/DEVELOPER-4347)
Updated Stack Overflow tags for each products are listed in [this doc](https://docs.google.com/spreadsheets/d/1dtx2ySawoFnFchle8AqPli3fZJjDAA78dQk0VOk8lRM/edit#gid=0)
=> DEVELOPER-4347 Updated product Stack Overflow tags

_partials/hero1.html.slim, stylesheets/_home.scss
[DEVELOPER-4321 - Implement Hero for "Advanced EAP Cheat Sheet"](https://issues.jboss.org/browse/DEVELOPER-4321) 
DO NOT MERGE -- SHOULD GO LIVE MONDAY 08/07
For review purposes only, will close once approved and reopen closer to the date
=> DEVELOPER-4321 Hero for "Advanced EAP Cheat Sheet"

_cucumber/features/primary_nav/primary_nav.feature
Removed redundant ruby-based acceptance test scenarios.
Removed scenarios have been replaced with js-e2e tests.
=> Removed redundant ruby-based acceptance test scenarios.

_docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/templates/product-pages.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/node--cheat-sheet.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/paragraph/paragraph--download.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/promotion-page/field--field-call-to-action-link.html.twig, _layouts/ticket-monster.html.slim, _partials/join-now-1.html.slim, _partials/join-now-2.html.slim, _partials/solution-partial-docker.html.slim, index.html.slim, javascripts/downloads.js, stylesheets/app.scss
[DEVELOPER-3792](https://issues.jboss.org/browse/DEVELOPER-3792) - Update hyperlink behavior in "CTA / buttons" (Drupal)
Updated CTAs according to [this spreadsheet](https://docs.google.com/a/redhat.com/spreadsheets/d/1SWnxIvzHnW2Dw6r51aTl2PMwG7u4_fQ3Z39o1eO3C2w/edit?usp=sharing)
=> [HOLD] DEVELOPER-3792 updated CTA classes

_tests/node_jenkins_test_runner.rb
[DEVELOPER-4360](https://issues.jboss.org/browse/DEVELOPER-4360) - Broken link check nightly prod job is broken
=> DEVELOPER-4360 - Fix for failing nightly broken link checks

_docker/drupal/drupal-filesystem/web/config/sync/views.view.rest_products.yml, _docker/drupal/drupal-filesystem/web/config/sync/views.view.taxonomy_tags_rest_export.yml
Two REST exports are contained in this pull request. Please see the two JIRA issues at:
https://issues.jboss.org/browse/DEVELOPER-4288
https://issues.jboss.org/browse/DEVELOPER-4289
These will be used by the maven plugin (and possibly others?) to find the taxonomy tags and products and create links to them.
=> DEVELOPER-4288 & DEVELOPER-4289 REST Exports

Gulpfile.js, _layouts/base.html.slim, javascripts/middleware-blog.js, javascripts/referrer.js, middleware.html.slim, stylesheets/_middleware.scss, stylesheets/app.scss
[DEVELOPER-4345 - Create /middleware Landing Page](https://issues.jboss.org/browse/DEVELOPER-4345)
=> DEVELOPER-4345 Created middleware landing page

variants/hero1.html.slim
No longer sending it to Drupal
=> Stop sending the A/B testing variant to Drupal

stylesheets/_alerts.scss
Updated links in _alerts.scss to https to avoid mixed content warnings
=> Updated links in _alerts.scss to https

_tests/blc/Gemfile.lock
Fixed issue introduced by previous merge into master causing bundle failures to Blinkr and e2e tests.
=> Fixed issue introduced by previous merge into master.

_tests/e2e/features/search/search.feature, _tests/e2e/features/step_definitions/search_steps.js, _tests/e2e/support/pages/search.page.js, _tests/unit/rhdp-search/rhdp-search-empty-query_spec.js, javascripts/build.js, stylesheets/_searchapp.scss, typescript/rhdp-search/rhdp-search-app.ts, typescript/rhdp-search/rhdp-search-empty-query.ts, typescript/rhdp-search/rhdp-search-query.ts, typescript/rhdp-search/rhdp-search-results.ts, typescript/rhdp-search/rhdp-search.ts
https://issues.jboss.org/browse/DEVELOPER-4202
=> DEVELOPER-4202 - Add Content for New Search Landing Page

stylesheets/_javaone.scss
[DEVELOPER-4243](https://issues.jboss.org/browse/DEVELOPER-4243) - JavaOne Events Page
Added CSS for new JavaOne 2017 page banner image, page for it will be created in Drupal.
=> [URGENT] DEVELOPER-4243 CSS for JavaOne 2017 page

stack-overflow.html.slim
[DEVELOPER-4407 - Need to add additional products to the /stack-overflow dropdown](https://issues.jboss.org/browse/DEVELOPER-4407)
Added the following products to the dropdown in /stack-overflow/:
- Red Hat JBoss Data Grid - (maps to tag: redhat-datagrid)
- Red Hat JBoss AMQ - (maps to tag: amq)
- Red Hat JBoss BRMS - (maps to tag: redhat-brms)
- Red Hat JBoss BPM Suite - (maps to tag: redhat-bpm)
- Red Hat JBoss Data Virtualization - (maps to tag: redhat-datavirt)
- .NET Core for Red Hat Enterprise Linux - (maps to tag: rhel.net)
=> DEVELOPER-4407 Added missing products to SO dropdown

_docker/drupal/drupal-filesystem/web/config/sync/core.menu.static_menu_link_overrides.yml
JIRA: https://issues.jboss.org/browse/DEVELOPER-4406
Added the missing content types to the menu.
=> DEVELOPER-4406: Update the add content drop-down menu

javascripts/build.js, typescript/rhdp-search/rhdp-search-result-count.ts
https://issues.jboss.org/browse/DEVELOPER-4435
=> DEVELOPER-4435 - Scrub term before printing to page

javascripts/build.js, stylesheets/_searchapp.scss, typescript/rhdp-search/rhdp-search-app.ts
To review:
1. Go to /search/?q=containers
2. Scroll to the bottom
3. Load More button should be center aligned
=> DEVELOPER-4216 Fixes search load more button position

index.html.slim, stylesheets/_home.scss
[DEVELOPER-4416 Multiple click zones for homepage promos](https://issues.jboss.org/browse/DEVELOPER-4416)
Navigate to the home page
Inspect a promo
Structure should be an anchor tag with an image and text inside (not an additional span)
Hover effect for the area should reduce the opacity of the image, but text should stay white
=> DEVELOPER-4416 Fixes click zones on homepage promos

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/system/html.html.twig
RHOAR product pages will go live on Friday, this adds the product to the main nav.
=> [HOLD] Added RHOAR to main nav

_tests/unit/rhdp-tryitnow_spec.js, javascripts/build.js, typescript/rhdp-tryitnow.ts
Should allow placement by HTML as well as JS now. Also allows HTML tags in text.
=> Try It Now element tweaks

javascripts/downloads.js
JIRA: https://issues.jboss.org/browse/DEVELOPER-4458
They don't want the download button.
=> DEVELOPER-4458 -- Remove RHOAR Download button

_tests/unit/rhdp-thankyou-page_spec.js, javascripts/build.js, stylesheets/_thank-you.scss, stylesheets/app.scss, typescript/rhdp-thankyou-page.ts
https://issues.jboss.org/browse/DEVELOPER-4019
The best way I've found to test this is to try downloading the Developer Salary Report 2016:
https://developers.stage.redhat.com/download-manager/file/Developers_Salary_Report_2016_pdf
This will redirect you to this PR and you should notice the correct name and direct link.
=> DEVELOPER-4019 - Create thank you page component for media downloads

javascripts/drupal-namespace.js, stack-overflow.html.slim
[DEVELOPER-4457 - Add SO tags for RHOAR](https://issues.jboss.org/browse/DEVELOPER-4457)
Adds the Stack Overflow tag for RHOAR, and added the product to the SO dropdown.
=> DEVELOPER-4457 Added SO tags for RHOAR

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/system/html.html.twig, stylesheets/_global-wrapper.scss
Moved footer logos inside the grid, and updated legal links font size
=> Footer fixes

index.html.slim, stylesheets/_home.scss
[DEVELOPER-4416 Multiple click zones for homepage promos](https://issues.jboss.org/browse/DEVELOPER-4416)
Homepage promos should not contain an img tag inside, instead the image should be displayed using CSS (in a :before pseudoelement). This will help the clicktale reports.
Cleaned up home.scss as well.
1. Navigate to the home page
2. Inspect a promo
3. Structure should be an anchor tag with text and image should be displayed using CSS
4. Hover effect for the area should reduce the opacity of the image, but text should stay white
=> DEVELOPER-4416 Fixed clicktale for homepage promos

_docker/drupal/Dockerfile, _docker/drupal/drupal-filesystem/composer.json, _docker/drupal/drupal-filesystem/composer.lock, _docker/drupal/drupal-filesystem/web/config/sync/core.extension.yml, _docker/drupal/drupal-filesystem/web/config/sync/filter.format.asciidoc.yml, _docker/drupal/drupal-filesystem/web/config/sync/filter.format.markdown.yml, _docker/drupal/drupal-filesystem/web/config/sync/markdown.settings.yml, _docker/drupal/drupal-filesystem/web/config/sync/user.role.content_creator.yml
JIRA: https://issues.jboss.org/browse/DEVELOPER-4437
Adding the filters, permissions and programs necessary for this to all work.
=> DEVELOPER-4437 Allowing markdown & asciidoc

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/system/html.html.twig, _tests/e2e/features/siteNavigation.feature
https://issues.jboss.org/browse/DEVELOPER-4470
=> DEVELOPER-4470 - Add appropriate footer links to services section

_config/categories.yml, _cucumber/features/primary_nav/primary_nav.feature, _cucumber/lib/data/categories.yml, _cucumber/lib/helpers/rest/download_manager/downloads_helper.rb, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/system/html.html.twig
https://issues.jboss.org/browse/DEVELOPER-4418
=> [HOLD] DEVELOPER-4418 - Redo Technology section for October launch

_docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.promotion_card.teaser.yml, _docker/drupal/drupal-filesystem/web/config/sync/system.site.yml, _docker/drupal/drupal-filesystem/web/config/sync/system.theme.global.yml, _docker/drupal/drupal-filesystem/web/config/sync/views.view.frontpage.yml, _docker/lib/drupal-data/lite/drupal_data_lite_image_builder.rb, _docker/tests/drupal-data/lite/test_drupal_data_lite_image_builder.rb, javascripts/contributors-quiz.js, javascripts/current-tab.js, javascripts/custom-jira-collector.js, javascripts/footer.js, javascripts/foundation/foundation.js, javascripts/jboss-docker.js, javascripts/pdf-links.js, javascripts/referrer.js, javascripts/visual.js
https://issues.jboss.org/browse/DEVELOPER-4497
https://issues.jboss.org/browse/DEVELOPER-4499
Hopefully making a smaller datadump for people.
=> 4497, 4499, smaller backup, config sync

_docker/drupal/drupal-filesystem/composer.json, _docker/drupal/drupal-filesystem/composer.lock, _docker/drupal/drupal-filesystem/web/config/sync/embed.button.media_browser.yml, _docker/drupal/drupal-filesystem/web/config/sync/embed.button.node.yml
No tickets, just things I noticed while playing around.
=> Random fixes for the admin UI

_docker/drupal-data/Dockerfile.lite, _docker/drupal/drupal-filesystem/web/sites/default/services.yml, _docker/lib/drupal-data/lite/drupal_data_lite_image_builder.rb, _docker/tests/drupal-data/lite/test_drupal_data_lite_image_builder.rb
These changes should drastically cut down on the size of the data-drupal-lite images
=> Creating smaller data-drupal-lite images

stylesheets/_searchapp.scss
[DEVELOPER-4487 Overlapping search filter buttons](https://issues.jboss.org/browse/DEVELOPER-4487)
=> DEVELOPER-4487 Fixed search btns on mobile

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/system/html.html.twig, javascripts/nav-highlight.js
[DEVELOPER-4493 Request to add "Security" Topic to the Topic tab](https://issues.jboss.org/browse/DEVELOPER-4493)
Add "Security" topic to the navigation
=> DEVELOPER-4493 Added Security topic to main nav

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/system/html.html.twig
[DEVELOPER-4498 Added SAP to the main nav](https://issues.jboss.org/browse/DEVELOPER-4498)
[DEVELOPER-4509 Re-order Technology pull down page to make columns the same length](https://issues.jboss.org/browse/DEVELOPER-4509)
=> DEVELOPER-4498 Added SAP to the main nav 

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/rhd.theme, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/field--field-related-product.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/node--books.html.twig, stylesheets/app.scss
JIRA: https://issues.jboss.org/browse/DEVELOPER-4081
Also styling it at the field level.
=> DEVELOPER-4081 Related product card

_docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.paragraph.overview.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.paragraph.overview.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.paragraph.overview.field_video_caption.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.paragraph.field_video_caption.yml, _docker/drupal/drupal-filesystem/web/config/sync/pathauto.settings.yml, _docker/drupal/drupal-filesystem/web/config/sync/user.role.content_admin.yml, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/paragraph/paragraph--overview.html.twig, stylesheets/_videos.scss
There are a couple of smaller things here as well that are not tied to a ticket.
JIRA: https://issues.jboss.org/browse/DEVELOPER-4423
To test this, find a product, edit and see the new field below the video field in the overview sub page.
Add a caption to the video.
Save, view the product and see the caption
=> DEVELOPER-4423 Video caption product overview

_docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.article.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.books.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.cheat_sheet.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.coding_resource.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.connectors.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.events.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.landing_page.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.page.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.product.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.promotion_card.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.promotion_page.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.rhd_microsite.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.rhd_solution_overview.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.topic.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.video_resource.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/workbench_email.workbench_email_template.published.yml, _docker/drupal/drupal-filesystem/web/config/sync/workbench_email.workbench_email_template.ready_for_review.yml, _docker/drupal/drupal-filesystem/web/config/sync/workbench_moderation.moderation_state_transition.draft_needs_review.yml, _docker/drupal/drupal-filesystem/web/config/sync/workbench_moderation.moderation_state_transition.draft_published.yml, _docker/drupal/drupal-filesystem/web/config/sync/workbench_moderation.moderation_state_transition.needs_review_draft.yml, _docker/drupal/drupal-filesystem/web/config/sync/workbench_moderation.moderation_state_transition.needs_review_needs_review.yml, _docker/drupal/drupal-filesystem/web/config/sync/workbench_moderation.moderation_state_transition.needs_review_published.yml, _docker/drupal/drupal-filesystem/web/config/sync/workbench_moderation.moderation_state_transition.published_draft.yml
=> Various Drupal admin config changes

_docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/rhd_common.form_validations.inc
JIRA: https://issues.jboss.org/browse/DEVELOPER-4524
All the info needed to test is available in JIRA.
=> DEVELOPER-4524 - PHP Serialization error

_docker/drupal/drupal-filesystem/db-migrations/20171121171201_revisions_not_displaying.php, _docker/drupal/drupal-filesystem/db-migrations/20171121181918_restore_embedded_paragraphs.php
Simple sql update to fix the problem.
=> DEVELOPER-4359 Discovered the problem with revisions displaying

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/system/html.html.twig
https://issues.jboss.org/browse/DEVELOPER-4525
=> DEVELOPER-4525 - Change all references from RHD to RHDP in Twig Files

_docker/drupal/drupal-filesystem/web/config/sync/core.extension.yml, _docker/drupal/drupal-filesystem/web/config/sync/editor.editor.rhd_html.yml, _docker/drupal/drupal-filesystem/web/config/sync/filter.format.rhd_html.yml, _docker/drupal/drupal-filesystem/web/config/sync/image.style.video_embed_wysiwyg_preview.yml
Testing: Make sure there's a new button in the media section
Go to the Karaf tab on the Fuse Hello World pages, make sure you see videos.
=> Re-enable video embed

_docker/drupal/drupal-filesystem/web/config/sync/pathauto.pattern.coding_resource.yml, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/rhd_common.tokens.inc, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/rhd.theme, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/system/field--node--field-related-product--coding-resource.html.twig
Create a coding resource, verify it displays properly (meaning it displays pretty much the same as other quickstarts). You'll notice a difference in the target product display, but that should be fine.
=> Fix coding resource display

stylesheets/_adaptive-placeholder.scss, stylesheets/_keycloak-pages.scss, stylesheets/app.scss
[DEVELOPER-4488 - Static HTML/CSS for Login page](https://issues.jboss.org/browse/DEVELOPER-4488)
=> DEVELOPER-4488 CSS styles for new login page

_docker/lib/export/static/rhdp-apps/devnationlive/devnationlive.json
=> [DevNation Live] Add latest webinars

javascripts/drupal-namespace.js, javascripts/search.js
https://issues.jboss.org/browse/DEVELOPER-4491
To test: visit Devtoolset help page and verify that the search query is returning tag pairs as expected.
=> DEVELOPER-4491 - Updated stackoverflow search logic to include AND logic

_docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.product.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.product.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.product.field_stackoverflow_product_refe.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_stackoverflow_product_refe.yml, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/rhd_common.product_related.inc, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/paragraph/paragraph--help.html.twig, javascripts/drupal-namespace.js
https://issues.jboss.org/browse/DEVELOPER-4491
To test: Visit each of the help pages and make sure that the results are returning from Stackoverflow as expected. You can also test the new field "Stackoverflow Product Reference". If that field exists, it will search for that label on "javascripts/drupal-namespace.js -> app.products" instead of the product code. 
E.g. http://rhdp-jenkins-slave.lab4.eng.bos.redhat.com:37144/products/clang-llvm-go-rust/help
=> DEVELOPER-4491 - Updates for adding tags AND logic

javascripts/build.js, typescript/devnation-live/devnation-live.ts
https://issues.jboss.org/browse/DEVELOPER-4523
Links on /devnationlive to past sessions should go to their corresponding content on the site rather than out to youtube.
=> DEVELOPER-4523 - Video links for past DevNation Live sessions should keep you on RHDP

_config/site.yml, _docker/environments/drupal-pull-request/rhd.settings.yml.erb
[DEVELOPER-4427](https://issues.jboss.org/browse/DEVELOPER-4427)
Use production Download Manager in pull-request environment
=> [READY!!] DEVELOPER-4427 Use production Download Manager in pull-request environment

_partials/hero1.html.slim, stylesheets/_home.scss
Initial attempt at a home page update for RHOAR
=> DEVELOPER-4557 - RHOAR Home page updates

_docker/drupal/drupal-filesystem/web/config/sync/pathauto.pattern.coding_resource.yml
This HAS to go in before the next Drupal restart.
=> HOTFIX Update pathauto.pattern.coding_resource.yml

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/client-side/mini_buzz.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/client-side/share_js_micro.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/share.html.twig, javascripts/build.js, stylesheets/_articles.scss, stylesheets/_home.scss, stylesheets/app.scss, typescript/devnation-live/devnation-live.ts, typescript/rhdp-downloads/rhdp-downloads.ts
* Adjusts some display issues on social buttons
* Home page images now HTTPS to avoid mixed content
* removes unnecessary event listening in some components
=> [FIX] - Updating some minor things

_ext/pipeline.rb
Hold this until https://github.com/redhat-developer/developers.redhat.com/pull/2150 is merged.
=> Remove DCP push from Awestruct pipeline

_tests/e2e/features/step_definitions/home_steps.js, _tests/e2e/features/website/rhd_home.feature
missing test scenario for [DEVELOPER-3669](https://issues.jboss.org/browse/DEVELOPER-3669).
=> Added missing test scenario for DEVELOPER-3669.

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/node--books.html.twig, stylesheets/_books.scss, stylesheets/_home.scss
[DEVELOPER-4446 Fix styles for 'More formats' section in Books pages](https://issues.jboss.org/browse/DEVELOPER-4446)
- Fixes this spacing issue: [screenshot](https://www.dropbox.com/s/ojadls4svvwfq0j/Screenshot%202017-09-27%2013.01.40.png?dl=0)
- Also made background color for home page hero black, so the older blue color doesn't show before the image loads
=> DEVELOPER-4446 Minor style fixes

_docker/drupal/drupal-filesystem/composer.json, _docker/drupal/drupal-filesystem/composer.lock
There is a known bug in Drupal affecting the Help Text for link fields that have the Link Text subfield disabled. Drupal issue: https://www.drupal.org/node/2421001
1. Go to create a new video resource in /node/add/video_resource
2. The SlideShare Source field should display the help text _Src attribute content from the embed code provided by SlideShare. For a more detailed explanation on where to get this link, see this doc._
=> DEVELOPER-4521 Fix help text not showing on Drupal fields

_docker/drupal/drupal-filesystem/scripts/run-httpd.sh
This PR updates the `run-httpd.sh` Drupal start-up script to correctly handle the `SIGTERM` signal received from the Docker daemon when the Drupal container is being stopped.
Currently we do not handle the `SIGTERM` from the Docker daemon correctly, meaning that Docker forcefully terminates the Drupal container with a `SIGKILL` after 10 seconds (the default timeout period for a container to exit after being sent the `SIGTERM` signal). The problem with this is that Drupal might be doing some work when it gets abruptly terminated, and we believe this may have been a partial cause of the production outage we had the other day were it appears that Drupal caches became corrupt.
**To test:**
1.  Using the current `master` branch, launch Drupal in a Docker container. Once it is running, issue a …
=> [DEVELOPER-4596] Ensure Drupal shuts down gracefully on `docker stop`

_tests/blc/config/prod_blinkr.yaml
Simply added url's to be ignored when generating blinkr report for prod checks.
=> [Blinkr] Updated Blinkr ignores

_docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.paragraph.download.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.paragraph.download.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.paragraph.download.field_overview_main_content.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.paragraph.download.field_para_download_imp_info.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.paragraph.field_para_download_imp_info.yml, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/paragraph/paragraph--download.html.twig
JIRA: https://issues.jboss.org/browse/DEVELOPER-4398
Added the new Important Information section, help text and display.
Renamed and reordered "Main Content"
All field labels for the Download Paragraph are fully hidden
=> DEVELOPER-4398 Adding new field, display tweaks

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/system/html.html.twig, _docker/lib/export/static/404-error/index.html, stylesheets/_header.scss
[DEVELOPER-4669](https://issues.jboss.org/browse/DEVELOPER-4669)
Changed h1 tag in logo for a div. in html.html.twig template and the error pages html.
Also updated css classes for it.
=> DEVELOPER-4669 Removed h1 tag from logo

_docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.article.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.books.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.cheat_sheet.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.learning_path.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.product.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.rh_training_class.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.video_resource.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.article.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.books.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.cheat_sheet.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.learning_path.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.product.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.rh_training_class.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.video_resource.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.article.field_card_image.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.books.field_card_image.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.cheat_sheet.field_card_image.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.learning_path.field_card_image.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.product.field_card_image.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.rh_training_class.field_card_image.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.video_resource.field_card_image.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_card_image.yml
@KamiQuasi - I believe this meets the requirements for the issue. Let me know if you need me to add anything else for the card element.
=> DEVELOPER-4590 - Update Existing Content Types for Learning Path

Gulpfile.js, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/js/devnationlive.json, _docker/lib/export/static/rhdp-apps/devnationlive/devnationlive.json, javascripts/build.js, package-lock.json, package.json, stylesheets/_devnation-live.scss, typescript/devnation-live/devnation-live-session.ts, typescript/devnation-live/devnation-live-speaker.ts, typescript/devnation-live/devnation-live.ts
https://issues.jboss.org/browse/DEVELOPER-4622
Removes eloqua registration, adds Inxpo registration, and cleans up the data and interface
=> DEVELOPER-4622 - Inxpo changes

javascripts/products.js
=> DEVELOPER-3431 - Download action resets situation tab

_tests/e2e/features/support/pages/website/CheatSheets.page.js, _tests/e2e/features/support/pages/website/Downloads.page.js, _tests/e2e/features/support/pages/website/Home.page.js, _tests/e2e/features/support/pages/website/Search.page.js, _tests/e2e/features/support/pages/website/StackOverflow.page.js, _tests/e2e/features/support/pages/website/Technologies.page.js, _tests/e2e/features/support/pages/website/Topics.page.js, _tests/e2e/features/website/rhd_navigationMenu.feature
Updated tests that were broken due to drupal migration.
=> Test fixes 

_tests/unit/rhdp-downloads/rhdp-downloads-popular-product_spec.js, _tests/unit/rhdp-os-download_spec.js, javascripts/build.js, typescript/rhdp-downloads/rhdp-downloads-all-item.ts, typescript/rhdp-downloads/rhdp-downloads-popular-product.ts, typescript/rhdp-os-download.ts
https://issues.jboss.org/browse/DEVELOPER-4657
To test: Visit the /downloads page and make sure that the correct OS version is linked
=> DEVELOPER-4657 - OS detection doesn't appear to be working for the Most Popular Downloads section

stylesheets/fonts/_fonts.scss
Overpass CDN reference was set to be done insecurely. This fixes that.
=> Fix Overpass reference

javascripts/products.js, javascripts/terms-and-conditions.js
@KamiQuasi - I'm not sure what the best way to review this is. I created a quick video to demo how I tested it.
https://www.dropbox.com/s/ckbwz6azskqzwb2/Screencast_02-14-2018_09%3A52%3A22%20AM.webm?dl=0
=> DEVELOPER-2788 - Do not trigger automatical download when user visits download landing page again (after back button usage).

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/js/devnationlive.json, _docker/lib/export/static/rhdp-apps/devnationlive/devnationlive.json
[DEVELOPER-4713 DevNation Live Webinar March 1st - Update DevNation Live Page with Reg Link](https://issues.jboss.org/browse/DEVELOPER-4713)
=> DEVELOPER-4713 Added upcoming DevNation webinar

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/learning-path/node--rh-training-class--learning-path-card.html.twig
[DEVELOPER-4723](https://issues.jboss.org/browse/DEVELOPER-4723)
Completion time and difficulty were not being displayed on the RH Training Class cards on Learning Path pages.
=> DEVELOPER-4723 Display missing fields in Training class

stylesheets/_get-started.scss, stylesheets/_topics.scss
Fixes issue with active tab having a bottom margin: see [screenshot 1](https://www.dropbox.com/s/xx0ypee5b9xvz4a/Screenshot%202018-02-23%2010.40.14.png?dl=0) , [screenshot 2](https://www.dropbox.com/s/eqx0hlrvrgu4127/Screenshot%202018-02-23%2010.43.01.png?dl=0)
**To review go to:**
- /products/devsuite/hello-world/#fndtn-windows
- /products/webserver/hello-world/
Also fixes issue with Topic pages not displaying font colors correctly: see [screenshot](https://www.dropbox.com/s/uhudd1hp2s9w1gz/Screenshot%202018-02-23%2012.01.41.png?dl=0)
**To review go to:**
- /topics/devops/
=> Style fix for Hello World and Topic pages

_tests/unit/rhdp-downloads/rhdp-downloads-all-item_spec.js, javascripts/build.js, javascripts/drupal-namespace.js, typescript/rhdp-downloads/rhdp-downloads-products.ts, typescript/rhdp-os-download.ts
Product downloads should be relative now.
=> Set relative paths for testing

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/js/devnationlive.json, _docker/lib/export/static/rhdp-apps/devnationlive/devnationlive.json
[DEVELOPER-4735 March 15th DevNation Live Webinar: Camel riders in the cloud](https://issues.jboss.org/browse/DEVELOPER-4735)
=> DEVELOPER-4735 Added DevNation session

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/learning-path/node--rh-training-class--learning-path-card.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/learning-path/node--video-resource--learning-path-card.html.twig
Fixes video and training class duration display.
=> DEVELOPER-4723 - Learning path value fixes

_tests/e2e/config/chimp-browserstack.js, _tests/e2e/config/chimp-docker-ci.js, _tests/e2e/config/chimp-local-docker.js, _tests/e2e/config/chimp-local.js, _tests/e2e/config/chimp-watch.js, _tests/e2e/environments/docker-compose.yml, _tests/e2e/features/support/rest/Drupal.instance.js
Fix for failing product tests.
=> Fix for failing product tests

stylesheets/_home.scss
[DESIGN-1510 New homepage promo](https://issues.jboss.org/browse/DESIGN-1510)
This needs to go live at the same time as the change in text/link underneath the image (a content change in Drupal)
=> DESIGN-1510 New homepage promo

stylesheets/_home.scss
[DEVELOPER-4786 Place JBoss BPM Book Promo on site](https://issues.jboss.org/browse/DEVELOPER-4786)
This needs to go live at the same time as the change in text/link underneath the image (a content change in Drupal)
=> DEVELOPER-4786 Updated homepage promo

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/js/devnationlive.json, _docker/lib/export/static/rhdp-apps/devnationlive/devnationlive.json
[DEVELOPER-4785 Add 4/5/2018 DevNation Live session](https://issues.jboss.org/browse/DEVELOPER-4785)
To review:
Go to https://developers-pr.stage.redhat.com/pr/2255/export/devnationlive/ and check that the upcoming session "TEST SMARTER AND GAIN SOME TIME BACK" is displayed
=> DEVELOPER-4785 Added DevNation Live session

_docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.article.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.product.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.user.user.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.user.user.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.article.field_hide_toc.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.product.field_product_categories.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.product.field_short_description.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.user.user.field_long_bio.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.user.user.field_short_bio.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.user.user.field_user_photo.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.user.user.field_user_title.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_hide_toc.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_product_categories.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.user.field_long_bio.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.user.field_short_bio.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.user.field_user_photo.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.user.field_user_title.yml, _docker/drupal/drupal-filesystem/web/config/sync/taxonomy.vocabulary.product_categories.yml
Updates that Tiffany made she wants added to prod.
JIRA: https://issues.jboss.org/browse/DEVELOPER-4793
testing: verify the changes Tiffany made in the JIRA are actually there.
=> DEVELOPER-4793 Changes from Tiffany

_docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/article/article.module, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/node--article.html.twig
JIRA: https://issues.jboss.org/browse/DEVELOPER-4794
Testing: find an article with the toc (/articles/frequently-asked-questions-no-cost-red-hat-enterprise-linux-developer-subscription works well),
click the checkbox to hide the TOC, safe, verify the toc is not
displayed and content takes the full width of the area.
=> DEVELOPER-4794 ability to hide article toc

_docker/drupal/drupal-filesystem/web/config/sync/field.field.node.article.field_card_image.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.books.field_card_image.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.cheat_sheet.field_card_image.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.learning_path.field_card_image.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.product.field_card_image.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.rh_training_class.field_card_image.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.video_resource.field_card_image.yml, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/rhd.theme, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/learning-path/node--cheat-sheet--learning-path-card.html.twig
https://issues.jboss.org/browse/DEVELOPER-4784
To test, add an unsplash image to the cheat-sheet cards and notice that the image should now appear.
=> DEVELOPER-4784 - Card Image on Learning Paths incorrect and not updating

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/package-lock.json, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/package.json
https://issues.jboss.org/browse/DEVELOPER-4743
=> DEVELOPER-4743 - Add NPM dependency to theme

_docker/drupal/drupal-filesystem/web/sites/development.services.yml, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/system/html.html.twig, _docker/environments/drupal-dev/rhd.settings.yml, _docker/environments/drupal-pull-request/rhd.settings.yml.erb, _docker/lib/export/static/404-error/index.html, _docker/tests/export/test_export_form_rewrite/homepage/index.html, javascripts/build.js, typescript/rhdp-search/rhdp-search-zapp.ts
Search-related issues: https://issues.jboss.org/browse/DEVELOPER-4759
DTM-related issues: https://issues.jboss.org/browse/DEVELOPER-4567
=> DEVELOPER-4759 and DEVELOPER-4567 - DTM and Search updates

_docker/drupal/drupal-filesystem/composer.json, _docker/drupal/drupal-filesystem/composer.lock
This is a dependency for several entity display modes. Composer automatically updated an unrelated repo URL, but removing it would invalidate the hash in the lock file.
=> add fences module

_docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.call_to_action.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.assembly.call_to_action.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.assembly.call_to_action.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.call_to_action.field_background_image.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.call_to_action.field_cta_content.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.call_to_action.field_cta_link.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.call_to_action.field_title.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.assembly_page.field_sections.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.assembly.field_cta_content.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.assembly.field_cta_link.yml
PR #2278 needs to be merged first
=> DEVELOPER-4800: Call to Action assembly

_docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.events.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.events.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.events.field_event_location.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.events.field_presenter_s_.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_event_location.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_presenter_s_.yml, _docker/drupal/drupal-filesystem/web/sites/default/default.services.yml, _docker/drupal/drupal-filesystem/web/sites/default/services.yml, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/node--books.html.twig
=> [DO NOT MERGE] DEVELOPER-4870 & DEVELOPER-4877 - Modify events content type with fields for new event page

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_card.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/rhd.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/styles/rhd.css, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhdp.libraries.yml, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhdp.theme, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/node/node--books--card.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/node/node--cheat-sheet--card.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/node/node--learning-path--card.html.twig
These are all minor variants on a single component, so they're handled in the same commit.
=> DEVELOPER-4850/4851/4852: Card styling

_docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.content_with_image.yml
JIRA: https://issues.jboss.org/browse/DEVELOPER-4882
Testing:
* Look at the list of assembly types make sure "Content with Image" is
gone and "Rich Text with Image" appears
=> DEVELOPER-4882 rename content with image

_docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.all_products_listing.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.assembly.all_products_listing.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.assembly.all_products_listing.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.all_products_listing.field_content.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.assembly_page.field_sections.yml, _docker/drupal/drupal-filesystem/web/config/sync/views.view.all_products.yml, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Plugin/AssemblyBuild/AllProductsListingBuild.php, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/assembly/assembly--all_products_listing.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/system/views/views-view--all-products.html.twig
JIRA: https://issues.jboss.org/browse/DEVELOPER-4815
Testing:
* Switch themes (if needed)
* Create new instance of assembly
* Add assembly to a new Landing Page
* Verify all products are listed
=> DEVELOPER-4815 All Products Listing Assembly

_docker/drupal/drupal-filesystem/composer.lock
JIRA: https://issues.jboss.org/browse/DEVELOPER-4843
Testing: click around, make sure stuff works
=> DEVELOPER-4843 Update Drupal core to 8.4.6

_docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.product.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.paragraph.paragraph_with_image.field_media_reference.yml
Also requiring an image for product features.
Testing:
* Edit/create a product verify 
** Product feature with image has a required media reference field
** Moderation state and Scheduled update are at the bottom of the form
All of this is per Tiffany in https://issues.jboss.org/browse/DEVELOPER-4814
=> Updating location of fields for products

_docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.author.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.topic_page.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.scheduled_update.node__moderation_state_1.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.article.scheduled_update.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.author.scheduled_update.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.books.scheduled_update.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.cheat_sheet.scheduled_update.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.coding_resource.scheduled_update.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.connectors.scheduled_update.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.events.scheduled_update.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.learning_path.scheduled_update.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.page.scheduled_update.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.product.scheduled_update.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.promotion_card.scheduled_update.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.promotion_page.scheduled_update.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.rh_certification_exam.scheduled_update.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.rh_training_class.scheduled_update.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.rhd_microsite.scheduled_update.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.rhd_solution_overview.scheduled_update.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.topic.scheduled_update.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.topic_page.scheduled_update.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.video_resource.scheduled_update.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.scheduled_update.node__moderation_state_1.field_moderation_state_2.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.scheduled_update.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.scheduled_update.field_moderation_state_2.yml, _docker/drupal/drupal-filesystem/web/config/sync/node.type.author.yml, _docker/drupal/drupal-filesystem/web/config/sync/scheduled_updates.scheduled_update_type.node__moderation_state_1.yml
JIRA: https://issues.jboss.org/browse/DEVELOPER-4080
Testing: 
* Go to all the create/edit pages of the different content types and verify "Moderation State" and "Scheduled Updates" are all in the same location.
=> DEVELOPER-4080 location of moderation state

_docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Plugin/AssemblyBuild/LearningPathsBuild.php
Since I only had 1 Learning Path locally, I duplicated output so I could ensure it looks right, and I forgot to remove these lines.
=> [URGENT] DEVELOPER-4886b ensure each Learning Path only appears once

javascripts/build.js, javascripts/drupal-namespace.js, typescript/rhdp-os-download.ts
Updates DevSuite download version due to updated download
=> Update DevSuite version

_docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Plugin/AssemblyBuild/DynamicContentListBuild.php, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_dynamic_content_list.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/patterns/_teaser.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/styles/rhd.css, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/assembly/assembly--dynamic-content-list.html.twig
Formatting for teasers as well as hiding the Latest comments section and making better use of space when nothing is in the sidebar
=> DEVELOPER-4945/4949 dynamic content list improvements

_docker/drupal/drupal-filesystem/composer.lock
New exploit was found, this fixes it.
=> Fixes SA-CORE-2018-004

_docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/rhd_assemblies.module, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Plugin/AssemblyBuild/DynamicContentFeedBuild.php, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Service/WordpressApi.php, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/templates/wordpress-post-teaser.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_dynamic_content_list.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/patterns/_teaser.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/styles/rhd.css
This is a better fix for DEVELOPER-4945, and also fixes some alignment issues in the assembly
=> DEVELOPER-4945 Fix/dynamic content list

_docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.rich_text.yml, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_rich_text.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/styles/rhd.css
=> DEVELOPER-4957 add slim visual style for rich text assembly

_docker/environments/drupal-production/docker-compose.yml, _docker/environments/drupal-staging/docker-compose.yml
In testing the export, I had to make the following changes for things to
actually work.
=> Rollbacks should happen in the export context

_docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.scheduled_update.node__moderation_state.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.scheduled_update.node__moderation_state_1.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.scheduled_update.multiple_node_embargo.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.scheduled_update.node__moderation_state.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.scheduled_update.node__moderation_state_1.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.scheduled_update.node_embargo.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.scheduled_update.multiple_node_embargo.field_moderation_state.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.scheduled_update.node__moderation_state.field_moderation_state_1.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.scheduled_update.node__moderation_state_1.field_moderation_state_2.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.scheduled_update.node_embargo.field_moderation_state.yml, _docker/drupal/drupal-filesystem/web/config/sync/metatag.metatag_defaults.global.yml, _docker/drupal/drupal-filesystem/web/config/sync/scheduled_updates.scheduled_update_type.multiple_node_embargo.yml, _docker/drupal/drupal-filesystem/web/config/sync/scheduled_updates.scheduled_update_type.node__moderation_state.yml, _docker/drupal/drupal-filesystem/web/config/sync/scheduled_updates.scheduled_update_type.node__moderation_state_1.yml, _docker/drupal/drupal-filesystem/web/config/sync/system.site.yml, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/system/html.html.twig
Our monitoring solutions need to verify the correct page is loaded. They
would like something towards the top that is guaranteed to be there. The
title seemed to be a good option, but it needs to be within the first 5k
of the response. I'm moving it up higher so it's guaranteed to be in
that amount.
=> Moving title up higher for monitoring checks

setup_local_drupal.sh
=> specify the docker project namespace so it works with the latest docker

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/system/block/block--system-menu-block--universal-footer.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/system/region/region--rh-universal-header.html.twig
Please pull the image from the current host, not prod website
=> Missing RH logo fix

_docker/control.rb, _docker/lib/options.rb, _docker/tests/test_options.rb
Attempting to clear the cache before an export
=> Clear the cache before an export

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/system/html.html.twig, _tests/e2e/specs/rhd-home.spec.js
https://issues.jboss.org/browse/DEVELOPER-5073
=> DEVELOPER-5073 - Improve availability monitoring to be less brittle

_docker/drupal/drupal-filesystem/scripts/run-httpd.sh
Hopefully this stops the network issues for npm.
=> [STAGING TEST] If we have proxy values, set them for npm

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/system/block/block--system-menu-block--universal-footer.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/system/region/region--rh-universal-header.html.twig
TESTING: check any page besides the root and verify the image is present
=> DEVELOPER-5087 Previous fix was relative

_tests/e2e/specs/rhd-cheatsheet-downloads.js, _tests/e2e/specs/rhd-product-downloads-login.spec.js, _tests/e2e/specs/support/DownloadHelper.js, _tests/e2e/specs/support/pages/Base.page.js, _tests/e2e/specs/support/pages/website/CheatSheets.page.js
There was an infinite loop whilst waiting for the download to exist. Occasionally when downloading pdf's they do not trigger, therefore triggering an infinite loop causing the build to timeout with failure after 60 seconds.
=> DEVELOPER-5096: [e2e] Infinite loop exists whilst waiting for download to exist

_docker/drupal/drupal-filesystem/web/config/sync/metatag.metatag_defaults.node__assembly_page.yml, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/rhd_common.tokens.inc
JIRA: https://issues.jboss.org/browse/DEVELOPER-5103
TESTING:
* View source of homepage
* Verify metatag for image and og:image is listed
=> DEVELOPER-5103 Fixing share image url

_docker/drupal/drupal-filesystem/web/config/sync/core.base_field_override.node.books.promote.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.base_field_override.node.books.status.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.books.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.cheat_sheet.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.product.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.books.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.cheat_sheet.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.product.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.extension.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.books.field_meta_tags.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.cheat_sheet.field_meta_tags.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.product.field_meta_tags.yml, _docker/drupal/drupal-filesystem/web/config/sync/metatag.metatag_defaults.node.yml, _docker/drupal/drupal-filesystem/web/config/sync/metatag.metatag_defaults.node__books.yml, _docker/drupal/drupal-filesystem/web/config/sync/metatag.metatag_defaults.node__topic_page.yml, _docker/drupal/drupal-filesystem/web/config/sync/node.type.books.yml
JIRA: https://issues.jboss.org/browse/DEVELOPER-5102
Testing:
* Edit a book, product, cheatsheet
* Verify you can edit metatags on a per instance basis
* Make some changes to a metatag
* Verify the source for the page reflects those changes
=> DEVELOPER-5102 Adding metatags for extra content

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/js/header.js, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/js/sso.js, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_navigation.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/styles/rhd.css, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/tsconfig.json, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/menu/menu--account.html.twig, package-lock.json
[DEVELOPER-5063 Desktop and mobile menu states for logged in users](https://issues.jboss.org/browse/DEVELOPER-5063)
-- This PR replaces #2488
=> DEVELOPER-5063 Desktop and mobile menu states for logged in users

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/devnation-live/devnation-live.ts
https://issues.jboss.org/browse/DEVELOPER-5130
Visit /devnationlive and click on the video links, links should work
=> DEVELOPER-5130 Change link in ts file from video to videos

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/docs/js/rhd.js, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/docs/themes/rhd/static/js/rhd.js, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/rhdp-projects/rhdp-projects.ts, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/paragraph/paragraph--community.html.twig
https://issues.jboss.org/browse/DEVELOPER-5045
=> DEVELOPER-5045 - Product Community pages are empty

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_devnation2015.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/styles/rhd.css, stylesheets/_devnation2015.scss
Devnation 2015 page doesn't load content and header is missing See: http://rhdp-drupal.stage.redhat.com/devnation2015
Now should have header and data
=> DEVELOPER-4975 change cdn( to url(

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/rhdp-thankyou-page.ts
=> DEVELOPER-5101 - Cheatsheet download is not always triggered

.gitignore, _tests/e2e/Dockerfile, _tests/e2e/config/browsers/BrowserManager.js, _tests/e2e/config/wdio.conf.docker.js, _tests/e2e/specs/rhd-blog.spec.js, _tests/e2e/specs/rhd-cheatsheet-downloads.js, _tests/e2e/specs/rhd-home.spec.js, _tests/e2e/specs/rhd-navigation-spec.js, _tests/e2e/specs/support/pages/Base.page.js
Clean up of tests, minor speed/stability improvements
=> [NO ISSUE] Clean up of tests, minor speed/stability improvements

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/js/header.js, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/js/sso.js, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_navigation.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/menu/menu--account.html.twig
Last comments on [DEVELOPER-5063](https://issues.jboss.org/browse/DEVELOPER-5063)
When logged in, clicking on the user icon and user name should trigger the dropdown to show up.
=> Fixed User menu click zone

_docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.article.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.books.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.video_resource.default.yml, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/shared_fields/field--node--field-tags.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/shared_fields/field--node--field-video-resource-tags.html.twig
https://issues.jboss.org/browse/DEVELOPER-5180
* Navigate to {server}/taxonomy/term/9
* Assert 404
=> DEVELOPER-5180 Remove references to taxonomy

_docker/Gemfile, _docker/Gemfile.lock, _docker/export/Dockerfile, _docker/lib/export/export_html_post_processor.rb, _docker/tests/export/test_export_html_post_processor.rb, _docker/tests/test_helper.rb
Attempting to use typhoeus for fetching the resources.
* https://issues.jboss.org/browse/DEVELOPER-5175 
* Find the og:image url in the homepage
* Verify it does not 404 in the export
=> DEVELOPER-5175 Fetch other static resources

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/js/products.js, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/js/terms-and-conditions.js
* https://issues.jboss.org/browse/DEVELOPER-2788
* The easiest way to test this is to visit the export from this PR.
* Download a product and navigate away from the hello-world page.
* Hit the back button to go back to the page and notice that the download isn't triggered.
https://www.dropbox.com/s/atlbwjw1sgewo0e/Desktop%202018.07.19%20-%2014.08.48.03.mp4?dl=0
=> DEVELOPER-2788 - Do not trigger automatic downloads when user revisits page

_docker/control.rb, _docker/tests/test_control.rb
* https://issues.jboss.org/browse/DEVELOPER-5245
A code review should work for this. I tested the loop structure with IRB. We'll only really know for sure (without writing a bunch of infra code in the tests) once we get this in staging.
=> DEVELOPER-5245 Adding timeout check

.gitignore, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/learning-path/node--article--learning-path-card.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/learning-path/node--books--learning-path-card.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/learning-path/node--cheat-sheet--learning-path-card.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/learning-path/node--learning-path--learning-path-card.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/learning-path/node--product--learning-path-card.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/learning-path/node--rh-training-class--learning-path-card.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/learning-path/node--video-resource--learning-path-card.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/README.md, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/js/line-clamp-binding.js, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/js/vendor/clamp.js, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_learning-paths.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/styles/rhd.css, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/tsconfig.json, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/learning-path/node--article--learning-path-card.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/learning-path/node--books--learning-path-card.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/learning-path/node--cheat-sheet--learning-path-card.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/learning-path/node--learning-path--learning-path-card.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/learning-path/node--product--learning-path-card.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/learning-path/node--rh-training-class--learning-path-card.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/learning-path/node--video-resource--learning-path-card.html.twig
https://issues.jboss.org/browse/DEVELOPER-5212
=> Feature/developer 5212 - add js to clamp lines and add elipsiss

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_cheat-sheet.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_learning-paths.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/rhd.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/learning-path/node--video-resource--learning-path-card.html.twig
* [DEVELOPER-5184 - Style issue in Cheat Sheet pages](https://issues.jboss.org/browse/DEVELOPER-5184)
* [DEVELOPER-5185 - Styling issues on Learning Path pages](https://issues.jboss.org/browse/DEVELOPER-5185)
* [DEVELOPER-5183 - Styling issues on Book pages](https://issues.jboss.org/browse/DEVELOPER-5183) (only second bullet point)
=> Fixes for legacy pages

_docker/drupal/drupal-filesystem/web/config/sync/simple_sitemap.settings.yml, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/rhd_common.sitemap.inc
Trying to use the config we have in place to get to the right URL for
Drupal. We'll see how this works.
* https://issues.jboss.org/browse/DEVELOPER-5267
Honestly not sure how to do this without actually running it in staging.
You can verify the sitemap looks correct for product pages though.
=> DEVELOPER-5267 sitemap links incorrect in stage

.gitignore, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_articles.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/styles/rhd.css, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/articles/node--article.html.twig
https://issues.jboss.org/browse/DEVELOPER-5182
h2. Requirements
* Tags section -  label shouldn't show if there are no tags ([See https://developers.redhat.com/articles/using-native-perl-rhel-6-or-rhel-7/
* Tags section - comma should not break into new line by itself  ([See https://developers.redhat.com/articles/using-ruby-23-rhel-7-containers-and-red-hat-software-collections - @adelasofia **I have not been able to replicate this issue on my system!**
* Tags section - add more space between tags section and dropdown on tablet/mobile view ([See https://developers.redhat.com/articles/using-ruby-with-red-hat-container-development-kit-cdk/
* Content / header sections - if there is no TOC, there shouldn't be so much space between the article header and the content. It's probably being caused …
=> Feature/developer 5182 - css and twig fixes for article tags

_docker/environments/drupal-pull-request/docker-compose.yml
Nothing to review. Except that broken-link-checks do not run on this PR.
=> remove blinkr from PR's

_docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/src/Controller/ProductPageController.php
N/A Currently
Make sure the downloads, docs, help, etc pages all work
=> Attempting to fix product pages after update

_docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.form.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.base_field_override.node.landing_page_single_offer.promote.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.assembly.form.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.landing_page_single_offer.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.assembly.form.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.landing_page_single_offer.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.landing_page_single_offer.teaser.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.form.field_content.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.form.field_title.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.landing_page_single_offer.body.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.landing_page_single_offer.field_form.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.landing_page_single_offer.field_meta_tags.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.landing_page_single_offer.field_sections.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_form.yml, _docker/drupal/drupal-filesystem/web/config/sync/node.type.landing_page_single_offer.yml, _docker/drupal/drupal-filesystem/web/config/sync/simple_sitemap.bundle_settings.node.landing_page_single_offer.yml, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_solp.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_assembly.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_form.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/rhd.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhdp.theme, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/assembly/assembly--form.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/node/node--landing-page-single-offer.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/solp/page--landing-page-single-offer.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/system/page.html.twig
* https://issues.jboss.org/browse/DEVELOPER-5208
1. Create new Content node with "Landing Page - Single Offer" Content Type
2. Add Title and Body content
3. Add new "Form" assembly (limit 1)
4. Add optional form title and footer content (ie: Privacy link)
5. Update Form
6. Add optional assembly sections to appear below the main content and sidebar
7. Save node and view.
Note: Form is placeholder only.
=> [DEVELOPER-5208] Create Single Offer Landing Page

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_books.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_products.scss
Style fixes for product pages and book pages
=> Minor Style fixes

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/rhdp-projects/rhdp-project-item.ts, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/rhdp-projects/rhdp-project-query.ts, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_projects.scss
https://issues.jboss.org/browse/DEVELOPER-5294
=> update upstream fuse links

.gitignore, _docker/drupal/drupal-filesystem/web/sites/example.settings.local.php, _docker/drupal/drupal-filesystem/web/sites/example.sites.php, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/rhdp-projects/rhdp-project-item.ts
https://issues.jboss.org/browse/DEVELOPER-5294
=> add null check for download and add files to gitignore

_tests/e2e/specs/rhd-downloads.spec.js, _tests/e2e/specs/support/DownloadDir.js
* NO ISSUE
- e2e tests are successful.
=> E2E download tests update

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/js/sso.js
* https://issues.jboss.org/browse/DEVELOPER-5235
* Adjust home page hero audience to be "unauthenticated"
* Check that it is visible
* Log in to site
* Check that it is hidden
=> DEVELOPER-5309 - Hide home page hero for authenticated users

_docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/rhd_common.module, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/src/Controller/ProductPageController.php, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/templates/product-pages.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/node/node--assembly-page.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/node/node--topic-page.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/system/page.html.twig
I previously had fixed the bug in how things were working, now that I'm doing it the right way(TM) the old broken way was misbehaving. This should fix that.
* https://issues.jboss.org/browse/DEVELOPER-5324
* View product pages
** Make sure the title and summary display
* View other pages in the system
** Make sure they display correctly wrt a title
=> DEVELOPER-5324 Product pages and titles

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_developer-materials.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/coding-resource/node--coding-resource.html.twig
[DEVELOPER-5181  Styling issues on Quickstarts/Boms/Archetypes/Demos/Ticket Monster](https://issues.jboss.org/browse/DEVELOPER-5181)
=> DEVELOPER-5181 Fixes for coding resources

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/paragraph/paragraph--overview.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/paragraph/paragraph--overview.html.twig
https://issues.jboss.org/browse/DEVELOPER-5319
=> [DEVELOPER-5319]-add empty check to overview features

_docker/drupal/drupal-filesystem/web/config/sync/rhd_disqus.disqussettings.yml, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Plugin/AssemblyBuild/DynamicContentListBuild.php, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/templates/wordpress-post-tile.html.twig, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_disqus/js/disqusFetch.js, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_disqus/rhd_disqus.module, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_disqus/src/Form/DisqusSettingsForm.php, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_dynamic_content_list.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/patterns/_tile.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/styles/rhd.css, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/assembly/assembly--static-item.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/video-resource/node--video-resource--teaser.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/video-resource/node--video-resource--tile.html.twig
* https://issues.jboss.org/browse/DEVELOPER-5262
- View a section with tiles (dynamic content, curated content -- look at the DevOps page for examples)
- Click on the comment count on one of the items
- Confirm the link takes you to the comments on that page and that the count is correct
=> DEVELOPER-5262 Disqus comment count

_docker/drupal/drupal-filesystem/web/config/sync/rhd_disqus.disqussettings.yml, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Plugin/AssemblyBuild/DynamicContentListBuild.php, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_disqus/src/Form/DisqusSettingsForm.php, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_dynamic_content_list.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/styles/rhd.css, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/video-resource/node--video-resource--teaser.html.twig
* https://issues.jboss.org/browse/DEVELOPER-5263
- Go to the DevOps page
- Scroll down to a dynamic content list section
- Confirm it has a sidebar with recent comments
- Click reply on one of those
- Confirm it links to the specific comment
- Go back to a dynamic content list section
- Confirm that articles have links to leave comments
=> [DEVELOPER-5263] Disqus latest comments

_tests/e2e/specs/rhd-downloads.spec.js, _tests/e2e/specs/support/pages/Base.page.js, _tests/e2e/specs/support/pages/website/CheatSheets.page.js
=> increased logged in/download is triggered wait times.

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_featured_products.scss
https://issues.jboss.org/browse/DEVELOPER-5311
=> DEVELOPER-5311 Add flex and justify content to featured products.

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_navigation.scss
https://issues.jboss.org/browse/DEVELOPER-5327
=> DEVELOPER-5327 Add red underline on nav hover

_tests/e2e/README.md, _tests/e2e/config/browsers/BrowserManager.js, _tests/e2e/package-lock.json, _tests/e2e/package.json, _tests/e2e/specs/rhd-404-error.spec.js, _tests/e2e/specs/rhd-blog.spec.js, _tests/e2e/specs/rhd-downloads.spec.js, _tests/e2e/specs/rhd-general-error.spec.js, _tests/e2e/specs/rhd-home.spec.js, _tests/e2e/specs/rhd-navigation-spec.js, _tests/e2e/specs/rhd-search.spec.js, _tests/lib/run_test_options.rb, _tests/node_jenkins_test_runner.rb
=> SANITY CHECK UPDATE

_tests/e2e/specs/rhd-404-error.spec.js, _tests/e2e/specs/rhd-blog.spec.js, _tests/e2e/specs/rhd-downloads.spec.js, _tests/e2e/specs/rhd-general-error.spec.js, _tests/e2e/specs/rhd-home.spec.js, _tests/e2e/specs/rhd-navigation-spec.js, _tests/e2e/specs/rhd-search.spec.js, _tests/e2e/specs/support/Utils.js, _tests/e2e/specs/support/pages/Base.page.js
* [Stabilise production sanity checks](https://issues.jboss.org/browse/DEVELOPER-5360)
=> DEVELOPER-5360: Stabilise production sanity checks 

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_rhd.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_solutions.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_base.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/colors/_grayscale.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/typography/_anchor.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhdp.theme
https://issues.jboss.org/browse/DEVELOPER-5331
https://issues.jboss.org/browse/DEVELOPER-5372
https://issues.jboss.org/browse/DEVELOPER-5351
=> DEVELOPER-5331, DEVELOPER-5372 and DEVELOPER-5351

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/books/node--books--card.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/cheat-sheet/node--cheat-sheet--card.html.twig
[DEVELOPER-5352 - Styling changes to the Featured Resources assembly](https://issues.jboss.org/browse/DEVELOPER-5352)
In the homepage, look at the "Get started with next-generation application development" section. Ebooks should have the content type "EBook" instead of "E-Book". And PDFs should be listed as "Cheat Sheets".
=> DEVELOPER-5352 Featured Resources fix

_docker/drupal/drupal-filesystem/web/config/sync/core.base_field_override.node.assembly_page.status.yml, _docker/drupal/drupal-filesystem/web/config/sync/metatag.metatag_defaults.node__assembly_page.yml, _docker/drupal/drupal-filesystem/web/config/sync/node.type.assembly_page.yml
https://issues.jboss.org/browse/DEVELOPER-5358
To review, check that the "Landing Page" content type has been renamed to just "Page"
=> DEVELOPER-5358 Renamed Landing Page

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/books/node--books--card.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/cheat-sheet/node--cheat-sheet--card.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/learning-path/node--learning-path--card.html.twig
https://issues.jboss.org/browse/DEVELOPER-5352
1. On the homepage, go to the "Get started with next-generation application development" section
2. Hover over one of the users group icons
3. The title that goes with the fa-users should be "Free for members" instead of "Login required"
=> DEVELOPER-5352 Minor fix for the Featured Resources assembly	

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/learning-path/node--rh-training-class--learning-path-card.html.twig
https://issues.jboss.org/browse/DEVELOPER-5379
1. Go to /learning-paths/microservices/
2. The training class card should have the laptop icon next to 'RH TRAINING CLASS'
=> DEVELOPER-5379 Training Class card icon update

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/js/menu.js, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_navigation.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/styles/rhd.css, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/menu/menu--rhd-navigation.html.twig
* https://issues.jboss.org/browse/DEVELOPER-5332
1. Go to any page on desktop
2. Click the magnifying glass in the nav
3. Verify the search bar pops up
4. Click the 'x' on the search bar
5. Verify that closes the search bar
6. Open the search bar again
7. Click anywhere else on the page
8. Verify clicking elsewhere closes the search bar
9. Open the search bar
10. Enter a search term
11. Hit enter
12. Verify you are taken to a relevant search page
=> DEVELOPER 5332 - Nav search redesign

_tests/e2e/specs/rhd-search.spec.js, _tests/e2e/specs/support/pages/website/NavigationBar.section.js, _tests/e2e/specs/support/pages/website/components/search/SearchBox.js
* Fixes for changes to search functionality.
=> Search fixes

_docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/paragraph/paragraph--download.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/js/downloads.js, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/paragraph/paragraph--download.html.twig, javascripts/downloads.js
https://issues.jboss.org/browse/DEVELOPER-5389
=> DEVELOPER-5389 remove try it paragraph

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/rhdp-search/rhdp-search-zapp.ts, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/rhdp-search/v2/rhdp-search-zapp.ts.new, typescript/rhdp-search/rhdp-search-zapp.ts
https://issues.jboss.org/browse/DEVELOPER-5367
=> [DEVELOPER-5367] change case on topics

_docker/drupal/drupal-filesystem/web/config/sync/metatag.metatag_defaults.403.yml, _docker/drupal/drupal-filesystem/web/config/sync/metatag.metatag_defaults.404.yml, _docker/drupal/drupal-filesystem/web/config/sync/metatag.metatag_defaults.front.yml, _docker/drupal/drupal-filesystem/web/config/sync/metatag.metatag_defaults.global.yml, _docker/drupal/drupal-filesystem/web/config/sync/metatag.metatag_defaults.node.yml, _docker/drupal/drupal-filesystem/web/config/sync/metatag.metatag_defaults.node__article.yml, _docker/drupal/drupal-filesystem/web/config/sync/metatag.metatag_defaults.node__assembly_page.yml, _docker/drupal/drupal-filesystem/web/config/sync/metatag.metatag_defaults.node__books.yml, _docker/drupal/drupal-filesystem/web/config/sync/metatag.metatag_defaults.node__topic.yml, _docker/drupal/drupal-filesystem/web/config/sync/metatag.metatag_defaults.node__topic_page.yml, _docker/drupal/drupal-filesystem/web/config/sync/metatag.metatag_defaults.taxonomy_term.yml, _docker/drupal/drupal-filesystem/web/config/sync/metatag.metatag_defaults.user.yml, _docker/drupal/drupal-filesystem/web/modules/custom/redhat_developers/config/install/metatag.metatag_defaults.node__article.yml, _docker/drupal/drupal-filesystem/web/modules/custom/redhat_developers/config/install/metatag.metatag_defaults.node__topic.yml
https://issues.jboss.org/browse/DEVELOPER-5374
add / to default values for canonical and og:url links
=> [DEVELOPER-5374] add / to default values

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/js/related-content.js
https://issues.jboss.org/browse/DEVELOPER-5424
=> [Developer 5424]-remove broken types from related video content

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_get-started.scss
https://issues.jboss.org/browse/DEVELOPER-5436
=> DEVELOPER-5436 - remove display:none from empty item to fix JS top calc

_docker/awestruct/Dockerfile, _docker/backup/Dockerfile, _docker/control.rb, _docker/drupal/Dockerfile, _docker/export/Dockerfile, _docker/ruby/Dockerfile, _docker/tests/test_control.rb
=> [DEVELOPER-5437] Fix Docker Builds

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/js/drupal-namespace.js
=> Update CDK download to 3.6

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/system/block/block--system-branding-block.html.twig
https://issues.jboss.org/browse/DEVELOPER-5447
=> change default title and alt

_docker/awestruct/Dockerfile, _docker/awestruct/mariadb/MariaDB.repo, _docker/backup/Dockerfile, _docker/backup/mariadb/MariaDB.repo
This is the merge of PR #2684 into master now that we have tested it in `stage`.
* [DEVELOPER-5478](https://issues.jboss.org/browse/DEVELOPER-5478)
- The build should go green.
=> [DEVELOPER-5478] Updated yum gpg URL to use HTTP rather than HTTPS

_docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.content_call_to_action.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.assembly.content_call_to_action.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.assembly.content_call_to_action.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.content_call_to_action.field_audience_selection.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.content_call_to_action.field_content.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.content_call_to_action.field_form.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.article.field_content.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.assembly.field_form.yml, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_eloqua_embed/rhd_eloqua_embed.module, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_eloqua_embed/src/Controller/EloquaEmbedController.php, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_eloqua_embed/templates/rhd-eloqua-embed-page.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_assembly.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_content_call_to_action.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/patterns/_buttons.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/styles/rhd.css, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhdp.theme, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/assembly/assembly--eloqua-form-embed.html.twig
https://issues.jboss.org/browse/DEVELOPER-5412
1. Content authors should be able to create an article call to action assembly on an article node.
2. The assembly should display per the mocks based on whether the sidebar visual style is selected. 
3. Eloqua forms should display correctly.
NOTE: Eloqua forms have been styled, but we are waiting on a shorter form to test with. As you can see in the screenshots below, longer forms do not embed properly.
=> [DEVELOPER 5412] Article Call To Action

_docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.content_call_to_action.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.assembly.content_call_to_action.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.assembly.eloqua_form_embed.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.assembly.content_call_to_action.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.assembly.eloqua_form_embed.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.content_call_to_action.field_audience_selection.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.content_call_to_action.field_content.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.content_call_to_action.field_form.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.eloqua_form_embed.field_url.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.article.field_content.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.assembly.field_form.yml, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_eloqua_embed/rhd_eloqua_embed.module, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_eloqua_embed/src/Controller/EloquaEmbedController.php, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_eloqua_embed/templates/rhd-eloqua-embed-page.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_assembly.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_content_call_to_action.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_eloqua_form_embed.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/patterns/_buttons.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/styles/rhd.css, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhdp.theme, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/assembly/assembly--eloqua-form-embed.html.twig
N/A
This is a general style and logic update for Eloqua forms. Specific style overwrites for inline forms.
NOTE: This is dependent on https://github.com/redhat-developer/developers.redhat.com/pull/2676
=> [DEVELOPER 5412.5] Eloqua form style updates

CONTRIBUTING.md
This changes reference to the `git rebase` command in CONTRIBUTING.md to `git merge`. This seems to be a preferred git workflow for our team.
=> changed git rebase to git merge in contributing.md

_docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.code_snippet.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.assembly.code_snippet.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.assembly.code_snippet.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.code_snippet.field_audience_selection.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.code_snippet.field_code.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.code_snippet.field_programming_language.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.article.field_content.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.assembly.field_code.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.assembly.field_programming_language.yml, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/js/highlightjs-init.js, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhdp.libraries.yml, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhdp.theme, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/assembly/assembly--code-snippet.html.twig
* https://issues.jboss.org/browse/DEVELOPER-5432
Go here:
Relative URL: `/node/add/article`
Do this:
* Enter any content for required fields
* Once you reach the Content field, you should notice that you now have an option of using a Code Snippet assembly type.
* Add a new code snippet assembly type
* Enter some name for the code snippet that makes sense to you
* In the Code, long text unformatted field, enter some code like:
```
var msg = 'hello world';
console.log(msg);
```
* Finish filling out any required fields and save the edit form to create the Article
* You should be redirected to your newly created Article containing a code snippet assembly
=> [DEVELOPER-5432] add code snippets assembly

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/rhdp-search/rhdp-search-result-count.ts, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/tests/unit/rhdp-search/rhdp-search-filter-item_spec.js, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/tests/unit/rhdp-search/rhdp-search-sort-page_spec.js
* NA
JS Unit tests should actually pass
=> Fixes some spacing issues on tests

_docker/drupal/drupal-filesystem/composer.json, _docker/drupal/drupal-filesystem/composer.lock, _docker/drupal/drupal-filesystem/web/config/sync/core.extension.yml, _docker/drupal/drupal-filesystem/web/config/sync/lightning_core.versions.yml, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/learning-path/node--article--learning-path-card.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/learning-path/node--books--learning-path-card.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/learning-path/node--cheat-sheet--learning-path-card.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/learning-path/node--learning-path--learning-path-card.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/learning-path/node--product--learning-path-card.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/learning-path/node--rh-training-class--learning-path-card.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/learning-path/node--video-resource--learning-path-card.html.twig
https://issues.jboss.org/browse/DEVELOPER-4722
=> [DEVELOPER-4722] add publish date module and amend twig code for learning paths

_docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.article.default.yml
https://issues.jboss.org/browse/DEVELOPER-5469
- Link tags don't show at bottom of article nodes
=> [DEVELOPER-5469] Hide tags from Article content type.

_docker/environments/drupal-pull-request/docker-compose.yml, _docker/tests/test-runner/test_run_e2e_tests_options.rb, _docker/tests/test-runner/test_run_tests.rb, _tests/e2e/README.md, _tests/e2e/config/wdio.conf.base.js, _tests/e2e/config/wdio.conf.local.js, _tests/e2e/environments/docker-compose.yml, _tests/e2e/package-lock.json, _tests/e2e/specs/drupal/login.spec.js, _tests/e2e/specs/export/rhd-404-error.spec.js, _tests/e2e/specs/export/rhd-blog.spec.js, _tests/e2e/specs/export/rhd-downloads.spec.js, _tests/e2e/specs/export/rhd-general-error.spec.js, _tests/e2e/specs/export/rhd-home.spec.js, _tests/e2e/specs/export/rhd-navigation-spec.js, _tests/e2e/specs/export/rhd-search.spec.js, _tests/e2e/specs/support/pages/drupal/Home.page.js, _tests/e2e/specs/support/pages/drupal/Login.page.js, _tests/e2e/wait-for-docker-selenium.sh, _tests/node_jenkins_test_runner.rb, _tests/run_test_options.rb
* [DEVELOPER-5510 ](https://issues.jboss.org/browse/DEVELOPER-5510)
* We can create tests that verify Drupal functionality to be executed as part of the PR build pipeline
* We have a single test that logs into the Drupal admin interface
=> DEVELOPER-5510: Perform some health testing on Drupal as part of a PR build	

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/Dockerfile, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/tests/unit/README.md, _tests/run_tests.rb, _tests/unit/environments/docker-compose.yml
* [DEVELOPER-5494](https://issues.jboss.org/browse/DEVELOPER-5494)
* PR receives the correct PR status
* js-unit-tests HTML report correctly links to the test report generated by Jenkins.
=> DEVELOPER-5494: Fix unit-test build issues

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/patterns/_comment.scss
https://issues.jboss.org/browse/DEVELOPER-5527
=> [DEVELOPER-5527] add word break all to comment-body

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/rhdp-thankyou-page.ts
https://issues.jboss.org/browse/DEVELOPER-5385
=> [DEVELOPER-5385] Add url decode loop and mobile message

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/books/node--books.html.twig
https://issues.jboss.org/browse/DEVELOPER-5519
go to /books/java-persistence-hibernate
should now show a link to the external site rather than the download link.
If pdf link is blank external book.url is rendered if it is populated.
-->
=> [DEVELOPER-5519] Add conditions for rendering of download links

_docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.featured_products.yml, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_featured_products.scss
[DEVELOPER-5522](https://issues.jboss.org/browse/DEVELOPER-5522)
- Rename the assembly from "Featured Products" to "Curated Products"
- Create 2 visual styles (1) Basic Cards - This is the same card style with no red accent border on the top (2) Featured Cards - This is the current style with the red border on top of the card.
=> DEVELOPER-5522 - Assembly Update: Featured Products

_docker/drupal/drupal-filesystem/phinx.yml
https://issues.jboss.org/browse/DEVELOPER-5553
run ./setup_local_drupal.sh in local enviroment shoud start up without phinx errors
=> [DEVELOPER-5553] update db name in phinx config

_docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.assembly.dynamic_content_list.default.yml, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_dynamic_content_list.scss
https://issues.jboss.org/projects/DEVELOPER/issues/DEVELOPER-5502?
https://docs.google.com/document/d/1cqG1u4Tapx2FYjzfWz1iap-zLWppY0KW3Er82PLSxuM/edit#
Quick follow up from SJ's feedback:
* Makes Dynamic content list CTA blue
* Use stacked layout up to small desktop for list entries (teasers)
=> Developer 5502 followup

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhdp.theme
This wrap the library alter in a conditional that verifies the existence
of the keycloak config object and the scriptUrl key within the config
object. This should resolve the undefined index error reported by Rob.
* https://issues.jboss.org/browse/DEVELOPER-5537
The error (below) is resolved, and Keycloak continues to function as expected across environments:
```
Notice: Undefined index: scriptUrl in rhdp_library_info_alter() (line 721 of /var/www/drupal/web/themes/custom/rhdp/rhdp.theme) #0 /var/www/drupal/web/core/includes/bootstrap.inc(584): _drupal_error_handler_real(8, 'Undefined index...', '/var/www/drupal...', 721, Array) #1 /var/www/drupal/web/themes/custom/rhdp/rhdp.theme(721): _drupal_error_handler(8, 'Undefined index...', '/var/www/drupal...', 721, Array) #2 …
```
=> [DEVELOPER-5537] Undefined Index scriptUrl

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_rhd-accordion.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_product_download-list.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_product_hero.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/rhd.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/assembly/assembly--product-download-list.html.twig
Style improvements for:
- [Product Download List](https://issues.jboss.org/browse/DEVELOPER-5515)
- [Product try it hero](https://issues.jboss.org/browse/DEVELOPER-5514)
- [Product Download Hero](https://issues.jboss.org/browse/DEVELOPER-5513)
**UX review is required before merging.**
=> Style improvements for product assemblies

_docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.article.tile.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.books.card.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.books.tile.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.coding_resource.card.yml
This is a drush config-export of config on the master branch. The
changes must have been made on Prod and caught during the DB backup I
assume.
* n/a
* Running `drush cex` on the `master` branch should not result in any exported changes
=> Config Out Of Sync on master branch

README.md
add some extra doc info for mysql v8 error
=> Update Docs for mysql 8 local install

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/js/drupal-namespace.js
=> Fixes CDK download CTA

_docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/rhd_assemblies.module
* https://issues.jboss.org/browse/DEVELOPER-5588
**Do this:**
* Create a new Product node with dummy data for any necessary required fields and the value `rhamt` for the URL Product Name field.
* Submit the node form to create this new Product node
**You should see this:**
* The form submission should be rejected and there should be an error on the URL Product Name form field
* The error message should read "The value you entered for URL Product Name is already used by an existing Product. This field must be unique across all Products to prevent routing conflicts."
**Do this:**
* Create a new Product node with dummy data for any necessary required fields and the value `blahblahblahblahblah` for the URL Product Name field.
* Submit the node form to create this new Product node
**You should …
=> [DEVELOPER-5588] Product nodes unique url product name

_tests/e2e/specs/support/pages/keycloak/Login.page.js
* No Issue.
* e2e tests are passing
=> Updating tests due to sso changes.

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_assembly.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_featured_articles.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/articles/node--article--card.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/assembly/assembly--featured-articles.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/field--assembly--field-articles--featured-articles.html.twig
[DEVELOPER-5571 - Assembly Styling: Featured Articles](https://issues.jboss.org/browse/DEVELOPER-5571)
=> DEVELOPER-5571 - Assembly Styling: Featured Articles

_tests/e2e/README.md, _tests/e2e/package-lock.json, _tests/e2e/specs/export/rhd-downloads.spec.js, _tests/e2e/specs/support/pages/website/CheatSheets.page.js, _tests/e2e/specs/support/pages/website/components/search/SearchFilter.js
- Search test updates.
- fixed flaky cheatsheet test.
=> [NO ISSUE] Search test updates

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/rhdp-search/rhdp-search-result.ts
https://issues.jboss.org/browse/DEVELOPER-5608
search for 'virtualbox' using site search, results should be shown when the relevance sort order is selected.
=> [DEVELOPER-5608] Add null check to description population

_docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.featured_articles.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.assembly.featured_articles.default.yml, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_base.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_featured_articles.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/field--assembly--field-articles--featured-articles.html.twig
[DEVELOPER-5607 - Add Featured Articles visual style options](https://issues.jboss.org/browse/DEVELOPER-5607)
- **APPROVED BY UX**
- Decrease padding of Featured Articles assembly to match the Rich Text Assembly
- Added visual styles dropdown to Featured Articles assembly
=> DEVELOPER-5607 - Added Featured Articles visual style options

_docker/drupal/drupal-filesystem/web/modules/custom/redhat_developers/redhat_developers.module
This adds a necessary key/value pair to the returned array of
hook_theme() in redhat_developers.module.
* https://issues.jboss.org/browse/DEVELOPER-5620
* Upon logging into Drupal (and/or generally navigating the site), the following error does not present itself:
```
Notice: Undefined index: render element in Drupal\Core\Theme\ThemeManager->render() (line 202 of /var/www/drupal/web/core/lib/Drupal/Core/Theme/ThemeManager.php) #0 /var/www/drupal/web/core/includes/bootstrap.inc(584): _drupal_error_handler_real(8, 'Undefined index...', '/var/www/drupal...', 202, Array) #1 /var/www/drupal/web/core/lib/Drupal/Core/Theme/ThemeManager.php(202): _drupal_error_handler(8, 'Undefined index...', '/var/www/drupal...', 202, Array) #2 /var/www/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(437): …
```
=> Undefined index: RHD Search Block

_tests/e2e/specs/export/rhd-downloads.spec.js, _tests/e2e/specs/support/DownloadDir.js, _tests/e2e/specs/support/Utils.js, _tests/e2e/specs/support/pages/Page.js, _tests/e2e/specs/support/pages/website/CheatSheets.page.js, _tests/e2e/specs/support/rest/keycloak/Site.user.js
* No issue.
- cheatsheet test passes.
=> [NO ISSUE]  Cheatsheet test fix.

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/js/visual.js, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_get-started.scss
https://issues.jboss.org/browse/DEVELOPER-5599
go to /ticket-monster/jbossdeployment on a desktop browser, scroll to the bottom of the page, the left nav should now not overlap the footer.
=> [DEVELOPER-5599] add fix for static menu

.gitignore, _tests/blc/jenkins_blc_runner.rb, _tests/e2e/specs/support/pages/Page.js, _tests/e2e/specs/support/pages/PageExtension.js, _tests/node_jenkins_test_runner.rb
Just a minor update to the environment variables on Jenkins, keeping them in synch with other PR triggered jobs.
=> NO-ISSUE: Update to e2e jenkins job

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/js/visual.js, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_faq.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/articles/node--article.html.twig
https://issues.jboss.org/browse/DEVELOPER-5623
go to the page below on desktop and mobile, the mobile design should match the story visually.
/articles/build-run-colossal-cave-adventure-game/
=> [DEVELOPER-5623] Updated TOC for articles on tablet and mobile

_docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.assembly.product_download_hero.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.assembly.product_try_it_hero.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.product_download_hero.field_learn_more_link.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.product_try_it_hero.field_learn_more_link.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.product_try_it_hero.field_try_it_link.yml, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_assembly.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_content.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/assembly/assembly--product-download-hero.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/assembly/assembly--product-try-it-hero.html.twig
[DEVELOPER-5650 - Updates to product page assemblies](https://issues.jboss.org/browse/DEVELOPER-5650)
- Updated Product try it hero assembly and Product download hero assembly
-- If no link text is provided for Learn More and/or Try It links on both assemblies, a default link text is displayed to the user
- Content assembly stylesheet
-- Added padding to the content assembly
=> [URGENT] DEVELOPER-5650 - Updates to product page assemblies

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/assembly/assembly--product-try-it-hero.html.twig
Simple update so anchor tag will display link with the updated field's display config.
=> Updates Prod. Try It Hero

_docker/drupal/drupal-filesystem/composer.json, _docker/drupal/drupal-filesystem/composer.lock
This PR applies a patch to Drupal core that is supposed to address issues with Drupal admin interface occasionally dropping into an error state with `The lightning module does not exist` type errors.
Please see: https://www.drupal.org/project/drupal/issues/3000677
* https://issues.jboss.org/browse/DEVELOPER-5647
* Navigate around Drupal and ensure that there are no additional errors in the log file.
=> [DEVELOPER-5647] Fix module does not exist error in Drupal

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/js/product-comparison-table.js, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_product_comparison_table.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/tsconfig.json, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhdp.theme, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/assembly/assembly--product-comparison-table.html.twig
[DEVELOPER-5562 - Product Features Refinement](https://issues.jboss.org/browse/DEVELOPER-5562)
**This has been approved by UX**
You can review the table here: http://rhdp-jenkins-slave.lab4.eng.bos.redhat.com:37790/products/clang-llvm-go-rust/overview
=> [DEVELOPER-5562]Product Features Refinement

_tests/blc/blinkr/Gemfile
Nothing to review here. Just an update to use latest version of blinkr.
=> bump to updated version of blinkr

README.md
This removes an outdated sentence from the custom module development
instructions and adds a section that explains how to install contributed
modules.
* n/a
n/a
=> Update README Module Instructions

_docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.article.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.assembly_page.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.author.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.books.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.cheat_sheet.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.coding_resource.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.connectors.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.events.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.landing_page_single_offer.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.learning_path.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.product.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.rh_certification_exam.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.rh_training_class.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.topic_page.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.video_resource.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_tax_audience_segment.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_tax_business_unit.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_tax_campaign.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_tax_lifecycle.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_tax_product.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_tax_product_line.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_tax_project.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_tax_promotion.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_tax_region.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_tax_stage.yml
https://issues.jboss.org/browse/DEVELOPER-5596
- Edit node with Purpose Attributes
- View they are now multi-select checkboxes
=> [DEVELOPER-5596] Change Purpose Attributes to multi-select checkboxes.

_tests/e2e/specs/support/pages/website/ProductOverview.page.js
Added extra check to verify that we're redirected to the correct environment (hello-world page)
=> [NO-ISSUE] Verify download redirect

_tests/e2e/specs/support/pages/website/Blog.page.js
Blog title has changed. Good spot @jordanpagewhite.
=> [NO_ISSUE] Blog title change

_docker/drupal/drupal-filesystem/composer.json, _docker/drupal/drupal-filesystem/composer.lock, _docker/drupal/drupal-filesystem/web/config/sync/core.date_format.long_12h.yml, _docker/drupal/drupal-filesystem/web/config/sync/entity_browser.browser.media_browser.yml
This updates Drupal core to version 8.6.10 and updates the following
contrib projects: admin_toolbar, ctools, jsonapi, lightning,
lightning_core, lightning_media, lightning_workflow, paragraphs and
metatag.
See: https://www.drupal.org/sa-core-2019-003 for details on this
security release.
* n/a
* All tests are green
* Drupal core is 8.6.10
* Paragraphs is 8.x-1.6
* Metatag is 8.x-1.8
* JSONAPI is 8.x-2.3
=> Drupal Core Update: 8.6.10

_tests/blc/blinkr/Gemfile.lock
=> Update of blinkr dependencies

_docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/templates/wordpress-post-tile.html.twig, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_disqus/js/disqusFetch.js, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/assembly/assembly--static-item.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/video-resource/node--video-resource--tile.html.twig
https://issues.jboss.org/browse/DEVELOPER-5673
go to homepage should get no errors in the console for disqus.
if there are errors it could be a request limit so check they are not request limit errors, if they are wait until the new hour and test again.
=> [DEVELOPER-5673] remove disqus requests for non developers.redhat.com requests

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_mq-mixins.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_rich-text-columns.scss
https://issues.jboss.org/browse/DEVELOPER-5670
add a rich text column assembly to a page with three cols, test at portrait tablet size cols should wrap and be underneath each other.
=> [DEVELOPER-5670] - add new breakpoint for medium 992px

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_collection.scss
https://issues.jboss.org/browse/DEVELOPER-5671
go to http://rhdp-jenkins-slave.lab4.eng.bos.redhat.com:37855/node/206785
the grid of articles should break from 4 to 3 to 2 depending on browser size.
=> [DEVELOPER-5671] add desktop small breakpoint

_docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.assembly.product_categories.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.assembly.product_categories.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.product_categories.field_cta_link.yml, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/dp-category-list/dp-category-list.ts, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_product_categories.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/assembly/assembly--product-categories.html.twig
[DEVELOPER-5688 - Assembly: Add CTA to Expandable Product Group](https://issues.jboss.org/browse/DEVELOPER-5688)
Added CTA field to the Product Categories assembly displayed in /products/
1.  Go to /products/edit
2. In the 'Expandable Product Groups - All Products' assembly, fill out the CTA field and save the changes
3. Go to /products/ and check that the CTA is displaying/linking correctly
=> [DEVELOPER-5688] Added CTA to Product Categories Assembly

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/js/terms-and-conditions.js
https://issues.jboss.org/browse/DEVELOPER-5721
check console for TypeError: null is not an object (evaluating 'i.indexOf')
should not be there
=> [DEVELOPER-5721]add null check

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/js/drupal-namespace.js
https://issues.jboss.org/browse/DEVELOPER-5731
go to cdk download and check 3.7.0-2 is downloaded
=> [DEVELOPER-5731] change cdk to 3.7.0-2

_docker/drupal/drupal-filesystem/web/config/sync/views.view.product_groups.yml
https://issues.jboss.org/browse/DEVELOPER-5739
go to products page and check in brows by product group DeveloperTool and check codeready toolchain is removed
=> [DEVELOPER-5739] add published filter to products group view

_docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.curated_links.yml, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_curated-links.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/assembly/assembly--curated-links.html.twig, _docker/environments/drupal-dev/rhd.settings.yml
https://issues.jboss.org/browse/DEVELOPER-5675
This is an update to the Curated Links assembly, to test create a new assembly item you should be able to add links and set the class of the assembly to 'render as horizontal nav' this will display the links as a nav.
=> [DEVELOPER-5675] update curated links to allow as a horizontal nav

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/js/drupal-namespace.js
* https://issues.jboss.org/browse/DEVELOPER-5747
* Navigate to `/products/cdk/download`
* Hover over the red button to make sure the link is for 3.8.0
* Version 3.8.0 should be linked
=> Update CDK downloads to 3.8.0

_docker/drupal/drupal-filesystem/web/config/sync/core.extension.yml, _docker/drupal/drupal-filesystem/web/config/sync/lightning_core.versions.yml, _docker/drupal/drupal-filesystem/web/config/sync/metatag.metatag_defaults.global.yml, _docker/drupal/drupal-filesystem/web/config/sync/metatag.metatag_defaults.node.yml, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_custom_meta/config/schema/rhd_custom_meta.metatag_tag.schema.yml, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_custom_meta/rhd_custom_meta.info.yml, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_custom_meta/rhd_custom_meta.module, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_custom_meta/src/Plugin/metatag/Group/RedHat.php, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_custom_meta/src/Plugin/metatag/Tag/NodeType.php, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_custom_meta/src/Plugin/metatag/Tag/TaxonomyPageSubType.php, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_custom_meta/src/Plugin/metatag/Tag/TaxonomyProduct.php, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_custom_meta/src/Plugin/metatag/Tag/TaxonomyProductLine.php, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_custom_meta/src/Plugin/metatag/Tag/TaxonomyTopic.php, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_custom_meta/tests/src/Functional/LoadTest.php
https://issues.jboss.org/browse/DEVELOPER-5605
* Build goes green
* Look at any page and view the source, verify the rhd:node-type meta tag is in the head section
* I don't know of any other nodes that have the rest of the data correctly set to see this actually work.
=> Developer 5605

_docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Plugin/AssemblyBuild/ProductDownloadHeroBuild.php
* https://issues.jboss.org/browse/DEVELOPER-5700
Go here:
/products/codeready-workspaces/download
Then login to an admin account and go here:
/admin/reports/dblog
You should *not* see error(s) like this:
```
User error: "featured" is an invalid render array key in Drupal\Core\Render\Element::children() (line 97 of /Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/web/core/lib/Drupal/Core/Render/Element.php) #0 
/Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/web/core/includes/bootstrap.inc(584): _drupal_error_handler_real(256, '"featured" is a...', '/Users/jowhite/...', 97, Array) #1 
[internal function]: _drupal_error_handler(256, '"featured" is a...', '/Users/jowhite/...', 97, Array) #2 …
```
=> [DEVELOPER-5700] Product pages invalid array key featured

_docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.content_with_image.yml, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_base.scss
[DEVELOPER-5669 - Assembly: Update Rich Text with Image Assembly](https://issues.jboss.org/browse/DEVELOPER-5669)
1.  Create a page
2. Add a rich text assembly with an image
3. Select the visual style "Image on the left"
4. Fill out assembly and save it
5. The image should be displayed on the left side on desktop, and on the top in mobile
review link: http://rhdp-jenkins-slave.lab4.eng.bos.redhat.com:37881/node/207566
=> [DEVELOPER-5669] Update Rich Text with Image Assembly

_docker/drupal/drupal-filesystem/composer.json, _docker/drupal/drupal-filesystem/composer.lock
I must have not run composer update to write the drupal/core update to
8.6.13 to composer.lock. This commit does that.
* https://issues.jboss.org/browse/DEVELOPER-5752
* We are on Drupal version 8.6.13
* All the tests are green
=> [DEVELOPER-5752] Writes core update to composer.lock

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_bonus_content_list.scss
https://issues.jboss.org/browse/DEVELOPER-5785
check padding is changed from 30px to 10px on on the bonus content list assembly
=> [DEVELOPER-5785] change padding to 10px

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/foundation/_foundation.scss
https://issues.jboss.org/browse/DEVELOPER-5713
check responsive behaviour on rhel8 page
=> [Do not merge][DEVELOPER-5713]-add display block to justify-center for mobile

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_on-page-nav.scss
https://issues.jboss.org/browse/DEVELOPER-5714
go to /rhel8 and check on page nav is not displayed on miblie
=> [DEVELOPER-5714] assembly-type-on_page_navigation hide mobile view

_tests/e2e/specs/drupal/login.spec.js, _tests/e2e/specs/support/pages/drupal/Config.page.js
* [DEVELOPER-5793](https://issues.jboss.org/browse/DEVELOPER-5793): Test that all Drupal configuration changes are successfully imported
* Each PR is tested to ensure that there are no dangling Drupal configuration imports
=> DEVELOPER-5793 Test that all Drupal configuration changes are successful

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/foundation/_foundation.scss
https://issues.jboss.org/browse/DEVELOPER-5712
Check the cta on the /rhel8 page works better in the mobile screen size ( second block on page light blue background )
=> [DEVELOPER-5712] auto center on phone

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/js/query-params-download-links.js, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/tsconfig.json
https://issues.jboss.org/browse/DEVELOPER-5790
Go to a page with a download-manager link add a query param to the page URL and refresh, the query param will be copied to all download-manager links in the page.
go to /books/introducing-istio-service-mesh-microservices/?sc_id=0123131 and check the sc_id is being applied to the links and that the download still works.
=> [DEVELOPER-5790] append query params to download links

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/typography/_heading.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/typography/_paragraph.scss
[DEVELOPER-5774 Update global site typography sizes](https://issues.jboss.org/browse/DEVELOPER-5774)
Link to review the new global text styles defined in the Jira ticket: http://rhdp-jenkins-slave.lab4.eng.bos.redhat.com:37906/node/208047
=> DEVELOPER-5774 - Updates to global typography

_docker/drupal/drupal-filesystem/composer.json, _docker/drupal/drupal-filesystem/composer.lock
This updates Drupal Core to 8.6.15 and updates some dependencies of
Drupal core.
* https://issues.jboss.org/browse/DEVELOPER-5809
* Drupal core is on version 8.6.15
* There is no dangling config
* Tests are all passing
=> [DEVELOPER-5809] SA-CORE-2019-006 Drupal Core 8.6.15

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_content_with_image.scss
https://issues.jboss.org/browse/DEVELOPER-5715
go to /topics/service-mesh/ and check the display of 'content with image' assembly and anywhere else it is used
=> [DEVELOPER 5715] left align on mobile

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_mq-mixins.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_featured_resources.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_learning_paths.scss
https://issues.jboss.org/browse/DEVELOPER-5716
https://issues.jboss.org/browse/DEVELOPER-5717
view the /topics/microservices page and check the responsive behaviour of the 'Microservices Books & Tutorials' section should be 4 columns them 3 then 2 and finally 1 column depending on screen size.
=> [ Waiting UX review ][ DEVELOPER - 5716 & 5717 ] responsive update to content cards

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_dynamic_content_feed.scss
https://issues.jboss.org/browse/DEVELOPER-5776
on the /topics/linux page the 4Developemnt languages cards should split to single column on mobile.
=> [DEVELOPER-5776] - Single Column on mobile

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/dp-category-list/dp-category-item-list.ts, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/dp-category-list/dp-category-item.ts, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/dp-category-list/dp-category-list.ts
https://issues.jboss.org/browse/DEVELOPER-5718
go to /products and check the 'browse by product group' section should reposition arrow and product panel on window resize where needed going from 4col to 3 to 2.
=> [DEVELOPER-5718] Rework Display Logic

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_developer-materials.scss
[DEVELOPER-5779 Article TOC is expanding in width with scroll
](https://issues.jboss.org/browse/DEVELOPER-5779)
This PR fixes a bug with where the TOC in article pages was increasing it's width once it became fixed to the top on scroll.
=> [DEVELOPER-5779] Article TOC fix

_tests/e2e/tests/config/wdio.conf.base.js, _tests/e2e/tests/specs/export/rhd-downloads.spec.js, _tests/e2e/tests/specs/support/pages/website/ProductOverview.page.js, _tests/e2e/tests/specs/support/utils/DownloadDir.js, _tests/node_jenkins_test_runner.rb
* [NO-ISSUE]: fix for failed to generate report.
* Allure report is not generating
* Quick fix until I can install the Allure Jenkins report plugin (it is available). 
The previous reporter is not supported in wdio v5.
* Check that the HTML report is displayed for each e2e test type.
=> [NO-ISSUE]: fix for failed to generate report.

_tests/e2e/tests/specs/support/pages/website/CheatSheets.page.js
* NO-ISSUE: Just noticed PR failing on CheatSheet downloads. Pushing a fix.
* Tests pass.
=> [NO-ISSUE] minor update to flaky cheatsheet test.

_docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.combo.yml, _docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.combo_item_assembly.yml, _docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.combo_item_manual.yml, _docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.combo_item_node.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.assembly.combo.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.assembly.combo_item_assembly.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.assembly.combo_item_manual.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.assembly.combo_item_node.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.assembly.combo.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.assembly.combo_item_assembly.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.assembly.combo_item_manual.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.assembly.combo_item_node.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.combo.field_audience_selection.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.combo.field_background_image.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.combo.field_cards.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.combo.field_content.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.combo.field_title.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.combo_item_assembly.field_assembly_item.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.combo_item_manual.field_image.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.combo_item_manual.field_url.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.combo_item_node.field_node_item.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.assembly_page.field_sections.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.landing_page_single_offer.field_sections.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.topic_page.field_sections.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.assembly.field_assembly_item.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.assembly.field_cards.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.assembly.field_node_item.yml, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_assembly.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_combo.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/assembly/assembly--combo.html.twig
* https://issues.jboss.org/browse/DEVELOPER-5827
1. Go to a content type with sections and add a new Combo assembly
2. Enter content and choose a Card type
Card types include:
1. Assembly reference
2. Node reference
3. Manual (image with link below)
=> [DEVELOPER-5827] Create combo assembly

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_featured_products.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/node/node--product--featured-tile.html.twig
https://issues.jboss.org/browse/DEVELOPER-5824
Go to /products
The three featured products should not show title if they have a logo.
Test deleting a logo and ensure the title is displayed.
=> [DEVELOPER-5824] Don't render title if logo available on featured product cards

_docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.code_snippet.yml
https://issues.jboss.org/browse/DEVELOPER-5828
create a code snippet assembly on a page there should be options to add visual styles for no-padding-top and no-padding-bottom
=> [DEVELOPER-5828] Add no padding top and bottom style option

_docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.assembly.video_hero.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.assembly.video_hero.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.video_hero.field_secondary_video_descriptio.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.video_hero.field_secondary_video_resource.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.video_hero.field_secondary_video_title.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.assembly.field_secondary_video_descriptio.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.assembly.field_secondary_video_resource.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.assembly.field_secondary_video_title.yml, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Plugin/AssemblyBuild/VideoHeroBuild.php, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_video-hero.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/patterns/_author.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/assembly/assembly--video-hero.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/author/node--author--short-teaser.html.twig
[DEVELOPER-5762 - Assembly: Video Hero Updates](https://issues.jboss.org/browse/DEVELOPER-5762)
Added ability to add a second video to the Video Hero Assembly
You should be able to add a secondary video to any Video Hero Assembly.
I created a test page with a dummy Video Hero Assembly so the reviewer can see the styles and / or test editing the assembly: http://rhdp-jenkins-slave.lab4.eng.bos.redhat.com:37934/node/208586
=> DEVELOPER-5762 - Assembly: Video Hero Updates

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_articles.scss
[DEVELOPER-5833 - Center-aligned images don't center align
](https://issues.jboss.org/browse/DEVELOPER-5833)
=> [DEVELOPER-5833] Center-aligned images don't center align

_tests/e2e/tests/specs/export/rhd-downloads.spec.js, _tests/e2e/tests/specs/support/pages/website/ProductOverview.page.js
* Updating download spec due to rhel8 change.
* Tests are passing.
=> [NO-ISSUE]: updated download test for rhel 8

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_articles.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/rhd.scss
[DEVELOPER-5833 - Center-aligned images don't center align
](https://issues.jboss.org/browse/DEVELOPER-5833)
=> [DEVELOPER-5833] Fixed img alignment styles

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_articles.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_table-of-content.scss
[DEVELOPER-5841 - Wrong size for headings in Article body](https://issues.jboss.org/browse/DEVELOPER-5841)
See /rhel8/install-rhel8-vbox#create_the_vm
Some styles specific to Articles were overwriting what the H4 and H3 font size should be.
=> [DEVELOPER-5841] Articles headings fix

_docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.assembly.cta_form.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.assembly.cta_form.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.cta_form.field_navigation_title.yml
Adds in the Navigation Title field to the CTA Form assembly type.
* https://issues.jboss.org/browse/DEVELOPER-5848
* Go here: `/node/add/assembly_page` and create a page with dummy values, and add a new CTA Form assembly to the Section fields within the main Compose tab
* You should see a Navigation Title form field
=> [DEVELOPER-5848] CTA Form Navigation Title

_docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.assembly.dynamic_content_list.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.assembly.dynamic_content_list.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.dynamic_content_list.field_wordpress_category_logic.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.assembly.field_wordpress_category_logic.yml, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Plugin/AssemblyBuild/BlogPostsBuild.php, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Plugin/AssemblyBuild/DynamicContentFeedBuild.php, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Service/RemoteContentApiInterface.php, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Service/WordpressApi.php, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/package-lock.json
https://issues.jboss.org/browse/DEVELOPER-5821
Go to dynamic content list on the homepage in the cms, you should be able to tick an option to enable AND filter logic on the list unselected is an OR filter
=> [DEVELOPER-5821] added or / and select on dynamic content list

_docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.author.tile.yml, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_articles.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_featured_articles.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/patterns/_author.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/author/node--author--tile.html.twig
https://issues.jboss.org/browse/DEVELOPER-5876
Fixed the author tile view that is displayed on Featured Articles, Articles pages, and Related Articles
1. Go to: http://rhdp-jenkins-slave.lab4.eng.bos.redhat.com:37961/coderland/serverless/
2. Check that authors are displayed correctly on the Featured Articles assembly
=> DEVELOPER-5876 Fixes for Author Tile view

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_event_list.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_events-hero.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/events/node--events--teaser.html.twig
https://issues.jboss.org/browse/DEVELOPER-5888
To test this fix:
1. Go to https://developer-preview-2968.ext.us-west.dc.preprod.paas.redhat.com/events/
2. The speakers under the 'DevNation Live Bangalore' event should **not** flow below the event thumbnail image ( like [this screenshot](https://issues.jboss.org/secure/attachment/12452500/12452500_Screenshot+2019-06-24+08.31.57.png) displaying the bug).
=> DEVELOPER-5888 - Events List assembly: Speakers style fix

_docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.cta_form.yml, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_eloqua_embed/templates/rhd-eloqua-embed-page.html.twig
* https://issues.jboss.org/browse/DEVELOPER-5872
1. Create CTA Form with Visual Styles pictured in Jira ticket
=> [DEVELOPER-5872] CTA Form Assembly updates

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_rich_text.scss
* No JIRA, just a UX request
* View home page
* Should not be any background image on the IBM+Red Hat hero
=> Remove Rich Text Assembly Background Image

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_rhd-footer.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/rhd.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/system/block/block--system-menu-block--rhd-footer.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/system/block/block--system-menu-block--universal-footer.html.twig
https://issues.jboss.org/browse/DEVELOPER-5880
The footer width should always match the width of the page's content section. See [this screenshot](https://issues.jboss.org/secure/attachment/12452351/Screenshot%202019-06-20%2015.34.12.png) to see how the width used to be smaller on the footer than the content.
=> [DEVELOPER-5880] Fixes footer layout

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhdp.theme
https://issues.jboss.org/browse/DEVELOPER-5923
go to /products/openjdk/overview and check form loads also check the iframe URL has a ?no_cache= and then a random guid.
=> [DEVELOPER-5923] Fix Eloqua form cache issue

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/js/visual.js
https://issues.jboss.org/browse/DEVELOPER-5816
Go to a page with a sticky nav and check it is not overlapping the disqus or footer areas.
/articles/red-hat-developer-program-benefits
=> [DEVELOPER-5816] change fix position on toc

_docker/drupal/drupal-filesystem/web/config/sync/metatag.metatag_defaults.403.yml, _docker/drupal/drupal-filesystem/web/config/sync/metatag.metatag_defaults.404.yml, _docker/drupal/drupal-filesystem/web/config/sync/metatag.metatag_defaults.front.yml, _docker/drupal/drupal-filesystem/web/config/sync/metatag.metatag_defaults.global.yml, _docker/drupal/drupal-filesystem/web/config/sync/metatag.metatag_defaults.node.yml, _docker/drupal/drupal-filesystem/web/config/sync/metatag.metatag_defaults.node__article.yml, _docker/drupal/drupal-filesystem/web/config/sync/metatag.metatag_defaults.node__assembly_page.yml, _docker/drupal/drupal-filesystem/web/config/sync/metatag.metatag_defaults.node__books.yml, _docker/drupal/drupal-filesystem/web/config/sync/metatag.metatag_defaults.node__topic.yml, _docker/drupal/drupal-filesystem/web/config/sync/metatag.metatag_defaults.node__topic_page.yml, _docker/drupal/drupal-filesystem/web/config/sync/metatag.metatag_defaults.taxonomy_term.yml, _docker/drupal/drupal-filesystem/web/config/sync/metatag.metatag_defaults.user.yml
https://issues.jboss.org/browse/DEVELOPER-5908
part one fix canonical errors
this change had already been made in drupal but got wiped after a deploy since the yml files were not updated, this change is to update the yml files.
check canonical links have no // on the end
Since the rule was put in place to add / to the urls in prod, this config can be removed from the drupal tag config
=> [DEVELOPER-5098-part-1] remove / from metadata tags to prevent //

_docker/drupal/drupal-filesystem/web/config/sync/field.field.node.article.field_content.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.assembly_page.field_sections.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.product.field_content.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.product.field_downloads_page_content.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.product.field_getting_started_content.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.topic_page.field_sections.yml
* https://issues.jboss.org/browse/DEVELOPER-5866
Edit nodes from each content type and confirm the 5 assemblies outlined in the ticket are not available.
=> [DEVELOPER-5866] Remove sub-assemblies from fields in content types.

_docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.events.teaser.yml, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Plugin/AssemblyBuild/VideoHeroBuild.php, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_articles.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_event_list.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/patterns/_author.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/author/node--author--tile.html.twig
https://issues.jboss.org/browse/DEVELOPER-5891
Author tiles should have the following styles: [see screenshot](https://issues.jboss.org/secure/attachment/12452598/Author%20page.png)
Author tiles appear in video heros, featured article cards, article pages and event heros.
Verify that author tiles look as expected on pages such as /events/, /devnation/, /rhel8/install-rhel8-vbox/, etc
=> DEVELOPER-5891 - Updated Author tile styles

_docker/drupal/dev/env.yml
* n/a
* The local build passes with these 'dummy' Disqus ansible variables
I verified this on my localhost, and everything worked well.
=> Add Disqus ansible vars to env.yml

_docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.bonus_content_list.yml, _docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.content_image.yml, _docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.content_pull_quote.yml, _docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.cta_form.yml, _docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.dynamic_content_list.yml, _docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.embedded_content.yml, _docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.events_list.yml, _docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.on_page_navigation.yml, _docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.product_comparison_table.yml
This updates the names/labels and help text for some assembly types
according to the Google sheet linked in DEVELOPER-5870.
* https://issues.jboss.org/browse/DEVELOPER-5870
* The assembly types all have the names/labels and help text described in this Google sheet: https://docs.google.com/spreadsheets/d/1--r2dCbTIMqeDK3yXREtsvv5-_B2UpHAHIEMSfcd7wA/edit#gid=1154163486
=> [DEVELOPER-5870] Update assembly names, help text

_docker/drupal/drupal-filesystem/web/config/sync/core.base_field_override.node.series.promote.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.base_field_override.node.series.status.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.series.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.series.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.series.teaser.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.series.body.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.series.field_series_articles.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.series.field_series_author.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.series.field_series_image.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.series.field_tax_audience_segment.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.series.field_tax_business_unit.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.series.field_tax_campaign.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.series.field_tax_lifecycle.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.series.field_tax_product.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.series.field_tax_product_line.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.series.field_tax_project.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.series.field_tax_promotion.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.series.field_tax_region.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.series.field_tax_stage.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_series_articles.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_series_author.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_series_image.yml, _docker/drupal/drupal-filesystem/web/config/sync/language.content_settings.node.series.yml, _docker/drupal/drupal-filesystem/web/config/sync/node.type.series.yml, _docker/drupal/drupal-filesystem/web/config/sync/simple_sitemap.bundle_settings.node.series.yml, _docker/drupal/drupal-filesystem/web/config/sync/workflows.workflow.00c7e3ae.yml
This implements the configuration necessary to create the Series content
type, as specified in DEVELOPER-5861. There will be a follow-up ticket
to implement an Assembly type and provide styles and designs for this
content type and the related assembly type.
* https://issues.jboss.org/browse/DEVELOPER-5861
Go here: /node/add/series
Do this:
* Add content to the fields in the Content tab of the Compose interface
* Save the form to create the Series
* This should redirect you to your newly created Series content
The content should successfully created and the data types / references should allow the editor to create a Series as defined in https://issues.jboss.org/browse/DEVELOPER-5861
=> [DEVELOPER-5861] Series Content Type

_docker/drupal/drupal-filesystem/composer.json, _docker/drupal/drupal-filesystem/composer.lock
* https://www.drupal.org/sa-contrib-2019-065
=> [SA-CONTRIB-2019-065] Security update for imagecache_external to v1.1

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_rhd-footer.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/system/block/block--system-menu-block--rhd-footer.html.twig
Updated the RHD footer so it can support 3 or 4 columns dynamically. These changes will also be bundled in the Footer Reference implementation, but wanted to push them here first due to Joe's deadline.
-- No Jira ticket
Marvel mockup: https://marvelapp.com/c6c454h/screen/60231484/
1. Check that the footer looks and works properly.
2. To add or remove columns, go to Structure > Menus > RHD Footer
3. Add or remove a column and it's links (Existing columns are Featured Topics, Communicate, Quicklinks)
4. Save the changes 
5. Check that the footer looks and works properly.
=> Footer Updates

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/menu/menu--topics-menu.html.twig
n/a. Change requested by Joe
All Topics link on the main navigation should link to /topics/
=> Updates main nav - minor change

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhdp2.theme, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--rich-text.html.twig
=> [SURGE-3005] Rich text

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--call-to-action.html.twig
* #3022 
Go here: https://developer-preview-3079.ext.us-west.dc.preprod.paas.redhat.com/
=> [SURGE-3022] CTA assembly

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--on-page-navigation.html.twig
This implements the template necessary to meet the design and FE
reference implementation requirements of the DX surge.
* #3049 
Go here: https://developer-preview-3078.ext.us-west.dc.preprod.paas.redhat.com/openshift
Go here: https://developer-preview-3078.ext.us-west.dc.preprod.paas.redhat.com/topics/containers
=> [SURGE-3049] Jump to nav

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/js/katacoda-tracking.js, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/tsconfig.json, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/katacoda/field--node--field-katacoda-embed-id.html.twig
=> Add Katacoda Firebase Tracking

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/system/block/block--system-menu-block--rhd-footer.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/system/block/block--system-menu-block--universal-footer.html.twig
* #3014 
Load homepage and you should see this at the bottom of the page (and on every other page)
=> [SURGE-3014] Update Footer to latest ref implementation

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/components/card-grid.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--dynamic-content-feed.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--featured-products.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--featured-resources.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--katacodas.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--static-content-band.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/node/node--learning-path--card.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/node/node--product--featured-tile.html.twig
* n/a
This does not represent a 'feature complete' state on any component. This simply creates an example within the rhdp2 theme that suggests how we can/should implement card grid based assembly types (or any other Drupal component).
=> Card Grid Base Implementation

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/system/html.html.twig
* n/a
The `pf-c-content` class is present on the <body> element on every page
=> [NO ISSUE] Add pf-c-content to body classes

_docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.article.dynamic_content_list_item.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.video_resource.dynamic_content_list_item.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_mode.node.dynamic_content_list_item.yml, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/rhd_assemblies.module, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Plugin/AssemblyBuild/DynamicContentFeedBuild.php, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Plugin/AssemblyBuild/DynamicContentListBuild.php, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_disqus/js/disqusFetch.js, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_disqus/rhd_disqus.module, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhdp2.theme, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--dynamic-content-list.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/node/node--article--dynamic-content-list-item.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/node/node--video-resource--dynamic-content-list-item.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/rhd-disqus--comment--latest.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/wordpress-post-teaser.html.twig
Implements dynamic content list frontend integration.
* Assembly template using frontend. 
* Template for wordpress posts as dynamic_content_list_item
* Template for disqus comments
* New view mode "Dynamic content list item"
* Implement dynamic content list item view mode for video and article nodes
=> [Surge-3104] Dynamic content list

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/components/card.twig
* n/a
Font Awesome icons properly load in Cards
=> [NO ISSUE] Fix font awesome icons

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/field/field--node--body--topic-page.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/node/node--topic-page.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/system/page.html.twig
* #3135 
Go here: /topics/service-mesh/
=> [SURGE-3135] Title summary on topic pages

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--bonus-content-item.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--bonus-content-list.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--call-to-action.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--code-snippet.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--content-with-image.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--curated-links.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--dynamic-content-list.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--on-page-navigation.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--product-download-hero.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--product-download-list.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--product-try-it-hero.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--rich-text.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--video-hero.html.twig
* n/a/
* The Dynamic Content List renders its Attributes in addition to our custom classes
=> [NO ISSUE] Dynamic content list include attributes

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhdp2.theme
Closes #3160 
Go here: /author/doug-tidwell/
=> [SURGE-3160] Article cards author conditional

_docker/drupal/Dockerfile.mp
Update docker file to include fonts #3182
Fixes #3182 
Check no missing fonts on pr environment
=> Update docker file to include fonts #3182

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/menu/menu--rhd-navigation--mobile.html.twig
Makes the search submit button in the main mobile nav submit the form on mobile
Closes #3196
=> [#3196] Mobile search submit

_docker/drupal/dev/docker-compose.yml
Small update to ensure we fix permission issues for running `composer` commands locally.
=> [#3376] Fixes permissions issues when running composer commands

_docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.static_content_band.yml, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/_rhd-theme.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_cards.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_component-base.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_static_content_band.scss
Fixes #3294 
Fixes #3283 
go to /coderland/reactive/ and check the 'watch the videos' section behaviour in various screen sizes.
Also, check /topics/devops/ 'Getting started with DevOps' section
Added a centered class to the component, in the admin go to either of the above pages and remove the 4 up class and add the centered option
=> Fix left align issue and float on assembly-type-static_content_band

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/scripts/@rhd/rhdp-search/rhdp-search-result.ts
Fixes a regression mentioned in DEVELOPER-5952
https://issues.jboss.org/browse/DEVELOPER-5952
* https://issues.jboss.org/browse/DEVELOPER-5952
Visit /search/?t=test&f=type%7Earticle and make sure that links go to a URL similar to https://developers.redhat.com/download-manager/link/3867444?redirect=
=> Fix SSO bridge link

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/data/components/dynamic-content-list-compact/context/base/default.toml, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/data/components/dynamic-content-list-compact/context/base/details.toml, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/data/components/dynamic-content-list-compact/variants.toml, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/data/components/two-col-hero-layout/context/base/default.toml, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/data/components/two-col-hero-layout/context/base/details.toml, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/data/components/two-col-hero-layout/variants.toml, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/docs/content/components/dynamic-content-list-compact.md, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/docs/content/components/two-col-hero-layout.md, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/_rhd-theme.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_cards.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_rhd-c-dynamic-content-list-compact.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_rhd-c-two-col-hero-layout.scss
Fixes #3406 
http://redhat.alt-media.dyndns.tv/rhd-frontend/3406/components/dynamic-content-list-compact/
http://redhat.alt-media.dyndns.tv/rhd-frontend/3406/components/two-col-hero-layout/
Check prototype matches design
=> Add compact dynamic article list

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_rich-text.scss
Fixes #3388
Go to /devnationlive-austin/
if you inspect the table element and remove the first-child class, table order should remain the same.
=> Add parent class limit to css

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/data/components/jump-to-nav/context/base/default.toml, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_jump-to-nav.scss
* https://github.com/redhat-developer/developers.redhat.com/issues/3387
- Navigate to the rhd-frontend folder
- Start the dev environment
- View the jump-to-nav component
=> Update jump-to-nav layout

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/js/footer.js, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/scripts/js/rhd/footer.js
Fixes #3399 
Build goes green
below 1170px footer menu works as expected then breaks to mobile at 1024px.
=> Fix footer nav breakpoint

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_product-download-hero.scss
Fixes #3414 
Go to. /products/codeready-workspaces/overview on mobile screen sizes image should be above text.
Build should go green
=> Feature/product try it hero needs the image to float above the text when responsive #3414

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_jump-to-nav.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--on-page-navigation.html.twig
* https://github.com/redhat-developer/developers.redhat.com/issues/3387
Fixes #3425 
Fixes #3387 
go to /topics/kubernetes/
validate nav margins are correct and nav works as expected
=> Implement new nav twig and css for jump nav

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/docs/content/components/alerts.md, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/scripts/@rhd/dp-alert.ts
* https://github.com/redhat-developer/developers.redhat.com/issues/3314
Navigate to a page that has an alert/notification block.
They should look like this:
=> Update Alerts to new styles

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/data/components/footer/context/base/rhd_footer.toml, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_footer.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/system/block/block--system-menu-block--rhd-footer.html.twig
Estimate: 2
Fixes #3439 
Check sign up link is aligned with social icons when there is enough space for it to do so. Revised estimate to include changes in comment
=> fix sign up footer

_docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Plugin/AssemblyBuild/OnPageNavigationBuild.php
[RHDX-64](https://projects.engineering.redhat.com/projects/RHDX/issues/RHDX-64)
2 nodes in production have orphaned Assemblies affecting these urls. This resolves the PHP fatal error.
There 2 URLs in Prod will not load, because of a PHP error:
https://developers.redhat.com/appenv/
https://developers.redhat.com/oraclejdkalternative/
There 2 URLs in this PR environment should load properly:
https://developer-preview-3441.ext.us-west.dc.preprod.paas.redhat.com/appenv/
https://developer-preview-3441.ext.us-west.dc.preprod.paas.redhat.com/oraclejdkalternative/
Also performed some PHPCS clean up. 
@jordanpagewhite
=> [RHDX-64] Error: Call to a member function isPublished() on null

_docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.static_content_band.yml, _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/templates/wordpress-post-tile.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/components/card-grid.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/components/card.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_cards.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_component-base.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_rhd-c-two-col-hero-layout.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_static_content_band.scss
https://projects.engineering.redhat.com/browse/RHDX-82
check card alignment on homepage two column assembly
=> [RHDX-82] Rework cards for static band

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/_pf4-custom-globals.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/_pf4-import.scss
https://projects.engineering.redhat.com/browse/RHDX-98
go to /articles/istio-service-mesh-intro/ and check Iframes are the correct height, sanity check of the site for any issues
=> [RHDX-98] Remove height auto from PF globals add custom globals

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/docs/content/pages/articles.md, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/_rhd-theme.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_articles.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_code-snippet.scss
https://projects.engineering.redhat.com/browse/RHDX-83
On the demo site, visit the `pages/articles` page. You should see the demo for the new Articles page, which includes the proper positioning and layout of the Series Assembly.
A demo of the work can be found here: https://rhd-frontend-demo.netlify.com/pages/articles/
=> Add Articles example page

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/_pf4-base-variable-overrides.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_rhd-c-two-col-hero-layout.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_static_content_band.scss
https://projects.engineering.redhat.com/browse/RHDX-146
Go to  /openshift and check card spacing.
=> [RHDX-146] Fix card justification

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_footer.scss
https://projects.engineering.redhat.com/browse/RHDX-122
check the footer on mobile and check the specs in the above story.
=> [RHDX-122] Fix footer spacing

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_cta.scss
https://projects.engineering.redhat.com/browse/RHDX-148
go to /products/openjdk/overview the cta background should run to the edge of the component
=> [RHDX-148] Fix background position on CTA component

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/scripts/js/2018/visual.js, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/scripts/js/microsites/microsite.js
https://projects.engineering.redhat.com/browse/RHDX-168
check js console for 'top' errors on https://developer-preview-3478.ext.us-west.dc.preprod.paas.redhat.com/articles/amq7beta/
=> remove sticky navs and equalize bottoms

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/_rhd-drupal-admin-overrides.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/_rhd-theme.scss
https://projects.engineering.redhat.com/browse/RHDX-229
view a draft page, the background should not be pink. Also In the admin, the visited menu links should be the same as the non-visited links.
=> [RHDX-229] Fix draft pink background and visited link color.

_docker/drupal/drupal-filesystem/web/config/sync/language.negotiation.yml, _docker/drupal/drupal-filesystem/web/config/sync/system.site.yml, _tests/e2e/tests/config/wdio.conf.base.js, _tests/e2e/tests/specs/export/rhd-403-error.spec.js, _tests/e2e/tests/specs/export/rhd-downloads.spec.js, _tests/e2e/tests/specs/support/Browser.Manager.js, _tests/e2e/tests/specs/support/pages/drupal/Config.page.js, _tests/e2e/tests/specs/support/pages/drupal/Home.page.js, _tests/e2e/tests/specs/support/pages/drupal/Login.page.js, _tests/e2e/tests/specs/support/pages/keycloak/Login.page.js, _tests/e2e/tests/specs/support/pages/keycloak/Register.page.js, _tests/e2e/tests/specs/support/pages/website/403-error.page.js, _tests/e2e/tests/specs/support/pages/website/CheatSheets.page.js, _tests/e2e/tests/specs/support/pages/website/NavigationBar.section.js, _tests/e2e/tests/specs/support/pages/website/ProductOverview.page.js, _tests/e2e/tests/specs/support/pages/website/Search.page.js, _tests/e2e/tests/specs/support/pages/website/components/search/SearchBox.js, _tests/e2e/tests/specs/support/pages/website/components/search/SearchFilter.js, _tests/e2e/tests/specs/support/pages/website/components/search/SearchOneBox.js, _tests/e2e/tests/specs/support/pages/website/components/search/SearchResultSort.js, _tests/e2e/tests/specs/support/pages/website/components/search/SearchResults.js, _tests/e2e/tests/specs/support/utils/DownloadDir.js, _tests/e2e/tests/specs/support/utils/Utils.js
https://projects.engineering.redhat.com/browse/RHDX-158
go to /user/172125/moderation/dashboard when not logged in should get 403 page.
I have added an e2e test for the 403 page and cleaned some of the styles of js test code
=> [RHDX-158] Add 403 page config

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/package.json
* n/a
The ./build-theme.sh script can be executed successfully
=> Update node-sass and highlightjs versions

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/package.json
https://projects.engineering.redhat.com/browse/RHDX-297
Tests and build should go green, site appearance should be unaffected.
=> [RHDX-297] Upgrade PatternFly Package Version

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_cards.scss
https://projects.engineering.redhat.com/browse/RHDX-296
Check the cards on the homepage have the correct font and colour for the label.
=> [RHDX-296] Feature/card labels are overpass and not the correct color

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/_pf4-import.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_component-base.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_visual-styles.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--content-with-image.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--rich-text-columns.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--rich-text.html.twig, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/node/node--katacoda-course.html.twig
https://projects.engineering.redhat.com/browse/RHDX-286
Check site still functions as before, the site appearance should be unchanged.
=> [RHDX-286] Split out patternfly imports / update base component styles

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_code-snippet.scss
https://projects.engineering.redhat.com/browse/RHDX-162
Check that the code blocks on these 2 pages display and function as intended in RHDX-162:
* https://developer-preview-3521.ext.us-west.dc.preprod.paas.redhat.com/che-custom-stacks/
* https://developer-preview-3521.ext.us-west.dc.preprod.paas.redhat.com/quickstarts/eap/ha-singleton-deployment/
=> [RHDX-162] Overflow x issue on code blocks 

_docker/drupal/drupal-filesystem/web/modules/custom/rhd_katacoda/rhd_katacoda.module
This provides some code style improvements to the rhd_katacoda.module,
and I have commented out (in 1 instance) or removed (in another
instance) code that is not being executed.
* n/a
* All Katacoda functionality remains exactly the same
* There are no CodeSniffer errors in rhd_katacoda.module
* We are not including `rhd_katacoda.tokens.inc`
=> [NO ISSUE] Clean up rhd_katacoda.module

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/2019/_learning-paths.scss, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/node/node--learning-path--full.html.twig
https://projects.engineering.redhat.com/browse/RHDX-361
go to https://developer-preview-3530.ext.us-west.dc.preprod.paas.redhat.com/learn/microservices/ on a mobile screen size and click the show more button, it should sow additional text.
=> [RHDX-361] add js library to learning-path twig

README.md
This is a long overdue change to the README.md to properly reflect
changes to the team as the project transitioned from MWES to CXnO.
* n/a
* The README.md is updated to provide accurate, helpful contact info for each role on the project
=> [NO ISSUE] Update contact info in README.md

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/scripts/@rhd/rhdp-search/rhdp-search-box.ts, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/pages/_searchapp.scss
https://projects.engineering.redhat.com/browse/RHDX-420
Go to search page, check the. hover state for the search button hover state matches a heavy cta button. Clicking the button should also trigger a new search.
=> [RHDX-420]update search button css and add trigger event

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/_rhd-theme.scss
[RHDX-455](https://projects.engineering.redhat.com/browse/RHDX-455)
Verify highlight JS css is working on code snippets.
/coderland/serverless/building-a-serverless-service/
/articles/quarkus-quick-start-guide-kubernetes-native-java-stack/
=> [RHDX-455] Fix styles for highlight js

_docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.katacoda_individual_lesson.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.katacoda_individual_lesson.card.yml, _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.katacoda_individual_lesson.default.yml, _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.katacoda_individual_lesson.field_sections.yml
https://projects.engineering.redhat.com/browse/RHDX-457
go to a katacoda lesson page and add an assembly to the section, then test the assembly appears at the bottom of the lesson iframe.
=> [RHDX-457] add field_sections to katacoda course

Jenkinsfile
* https://projects.engineering.redhat.com/browse/RHDX-502
* We can successfully build PRs and status checks pass as consistently as is possible
https://master-jenkins-csb-rhdev.cloud.paas.psi.redhat.com/job/Developer%20Drupal%20-%20Pull%20Request%20Trigger/
=> [RHDX-502] Increase PR trigger timeout to 2 hours

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/node/node--product--card.html.twig
https://projects.engineering.redhat.com/browse/RHDX-508
go to /products and check the featured products have product logos
=> [RHDX-508] Restore hero_image field

_docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/scripts/js/rhd/5-sso.js, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_jump-to-nav.scss
https://projects.engineering.redhat.com/browse/RHDX-491
As an unauthenticated (Keycloak/SSO) user, 
Go to https://developer-preview-3589.ext.us-west.dc.preprod.paas.redhat.com/topics/serverless-architecture/
* ensure in page nav links are visible, try setting one of the assemblies on that page to authenticated and
* ensure its removed from the page and the link is not visible
Then,
* Login in using sso and the content should be visible.
=> [RHDX-491] Add functionality to hide nav item

.gitignore, _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_articles.scss
https://projects.engineering.redhat.com/browse/RHDX-636
go to https://developer-preview-3593.ext.us-west.dc.preprod.paas.redhat.com/products/fuse/hello-world-fuse-tooling/#fndtn-macos and check TOC words should only hyphenate if needed.
=> [RHDX-636] Fix hyphens on toc
