redhat-developer/developers.redhat.com

- javascripts/connectors.js
- javascripts/namespace.js
- javascripts/projects.js
See <https://issues.jboss.org/browse/RHD-571>
Please comment on this PR. I am not sure if changes to `Gemfile.lock` file should be part of this PR.
Also note that at the Searchisko REST API we are moving from general Search API to registered query called [suggest_project_name](https://github.com/searchisko/configuration/blob/v2.0.2/data/query/suggest_project_name.md) (more specifically the `suggest_project_name_ngram_more_fields` variant).
> Migrate Upstream Projects page to Searchisko 2.

- README.md
- _docker/control.rb
This makes sure that if the -d flag is provided then a parameter is given 
```
./control.rb -bd
```
will fail, but 
```
./control.rb -bd "tcp:localhost:888"
```
will be fine.
Also fixed instructions
> Docker options

- _partials/developer-materials-results.html.slim
- javascripts/developer-materials.angular.js
- stylesheets/_developer-materials.scss
Adds an external link icon to external links
Might not work perfectly in staging since we do the "urlfix", which changes links from pr.developer.redhat.com to localhost, but that won't be an issue on production
This also includes a fix to the `urlFix` function which was flooding the console with errors when there was no link available.
> added external icon RHD-415

- _ext/stacks.rb
- _partials/bom-replaced_advise.html.slim
Previously the code to link to a bom which replaced an old bom was
broken and the links did not exist. This fixes that problem, though I've
just thought of another solution: Why send boms to the DCP which have
replaced product boms anyway? Yes, we'd need to erase the current set of
BOMs in the DCP, but if we're going to have a link to a replacement bom,
why even include the old bom in the first place?
> Fixing BOM replacement URL

- Rakefile
We should consciously make updates to the dependency versions, rather than routinely doing them on every build.
> Removing Bundle Update from build

- Gemfile.lock
We are having problems with the Gemfile.lock on the build servers. Currently they are running bundler version 1.10.4 or earlier. This causes a miss match with people running 1.10.5 or later. https://github.com/bundler/bundler/issues/3697
The real fix will be to upgrade all the bundles on the build servers, but this will fix it for now. I'll probably go through this with you on Wednesday @paulrobinson.
> Removing bundler tag

- Gemfile.lock
Seems we have 1.9.9 or less on the build servers.
> Gemfile compatible with bundler < 1.9.10

- Gemfile.lock
- _ext/jboss_developer.rb
- _layouts/get-started-item.html.slim
This does conflict a bit with the work I've done in
LightGuard/developers.redhat.com/feature/ongoing-blinkr-fixes, but
ultimately I think the fix there is correct and should be used.
> Fixes RHD-764 allow 1+ target_products in demos

- _docker/awestruct/Dockerfile
Using a binary of phantomjs so the install is quicker. We are not using any 2.0 specific features so we're fine. All the tests run.
> Using a pre built binary of phantom js

- Rakefile
With this change the site runs through the pipeline but doesn't generate
anything until you actually access the page.
> Enable livereload and on-demand building

- _config/site.yml
Undoing what we did here. https://github.com/redhat-developer/developers.redhat.com/commit/2e6cbad311446a3d259712b51bef0ff3ae864ac6.
This is because the nightly build now has a stable port
> Using the nightly build searchisko location

- _config/site.yml
The environment variables are now set in the build https://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/jboss.org/job/developers.redhat.com-pull-player-executor/configure
Currently these are
```
STAGE_SEARCHISKO_HOST=10.3.9.71
STAGE_SEARCHISKO_PORT=32778
```
> Environment variables for stage searchisko

- _ext/pipeline.rb
Had a chat with @LightGuard about this issue and it seems to come down to everything being a lowercase path when many of the images are mixed/camelCased
We're going to see what blinkr finds, if anything.
> Fixed image loading issue RHD-1041

- javascripts/experiments.js
When cxApi (a global var put in there by some A/B testing script) is unavailable, the JS that come after it breaks.
> check if experiments API exists before running variations. 

- _ext/pipeline.rb
- register.html.slim
Okay - the reason we were linking to a static version of keycloak is because our build process doesn't serve up individual JS files - just a bundle of everything. 
The register page only needs keycloak.js so a simple solution to that is to just inline the JS at build time.
> use current keycloak by inlining js RHD-1347 

- _layouts/product-developer-materials.html.slim
- _layouts/solution-learn.html.slim
- community/contributor/index.html.slim
- vjbug/index.html.slim
We had javascript yml keys which weren't unique, so every build it was
getting something different depending on which page was generated first
by the site.
Also some of the instances weren't needed as we're already including the javascript file in the main layout.
> Fixes DEVELOPER-1751 (cdn.yml updating)

- javascripts/developer-materials.angular.js
I've added in the case for docker-nightly. Here's the output of the
console testing I've done. I think everything looks correct.
> dcp_url = "http://it-developers-pr.stage.redhat.com/pr/684/build/500/video/youtube/Cl3SiavsBF4"
"http://it-developers-pr.stage.redhat.com/pr/684/build/500/video/youtube/Cl3SiavsBF4"
> base_url = "http://it-developers-pr.stage.redhat.com/docker-nightly"
"http://it-developers-pr.stage.redhat.com/docker-nightly"
> dcp_url.replace(/^http(s)?:\/\/(\w|\.|\-|:)*(\/pr\/\d+\/build\/\d+)?/, base_url)
"http://it-developers-pr.stage.redhat.com/docker-nightly/video/youtube/Cl3SiavsBF4"
> dcp_url_2 = base_url
"http://it-developers-pr.stage.redhat.com/docker-nightly"
> base_url_2 = "http://it-developers-pr.stage.redhat.com/pr/684/build/500" …
> Fix the regex for urlFix (DEVELOPER-2436)

- _cucumber/lib/helpers/customer.rb
fixing randomly failed test for forgot password.
adding wip
added more password reset users
> DEVELOPER-2475 - Password reset Acceptance test is randomly failing causing unnecessary PR fails

- _config/site.yml
@paulrobinson We'll need this merged for the nightly to work. I'll fill you in tomorrow but we were very lucky/unlucky with a change and the last build.
I also suspect that dcp_base_protocol_relative_url is no longer used, but we can look at this tomorrow outside of this PR. 
https://github.com/redhat-developer/developers.redhat.com/search?utf8=%E2%9C%93&q=dcp_base_protocol_relative_url
> Using correct docker link

- Gemfile.lock
- _ext/events.rb
Also there is no `as_json`, it's `to_json`.
We'll need to clear quickstarts and probably run this again after that happens.
> Updating aweplug to change searchisko ids

- javascripts/book-download.js
- javascripts/extensions.js
- javascripts/terms-and-conditions.js
- stylesheets/_global-wrapper.scss
This is where 70% of our errors were coming from in Sentry and were most likely causing the user from not being able to download the book and other products. See JIRA for more info.
> Fix book download JS errors

- README.md
I'm making some small changes to the README regarding long running branches, or the staging integration branch. I took out the names of the branches as I didn't see the point in 1) exposing our upcoming secrets to the world, even though this is a public repo 2) trying to keep these up to date every time we need a new staging branch
> Update README.md to reflect staging branch changes

- Rakefile
We're now exiting with an error regardless of the enviroment we're
building. Previously we only failed if we were in production. We'd still
push a broken site.
> Fixes DEVELOPER-2795

- products/rhel/get-started.adoc
This section is no longer required because we incorporated Customer Portal T&C agreements into the RHDev registration page.
> remove temp portal reg for RHEL get started - Dev-2806

- Gemfile.lock
Updated the jwt dependency to version 1.5.4 as version 1.5.3 has been yanked from the repository.
> [DEVELOPER-2861] Bumped jwt dependency to 1.5.4 to fix build issues

- Gemfile.lock
Fixed the revision of the awestruct gem that is referenced in Gemfile.lock so that builds will work on machines without the old revision cached.
> [DEVELOPER-2898] Updated to the latest revision of the awestruct gem

- README.md
- _cucumber/features/login_register/basic_login.feature
GMail seems to be blocking connection attempts from the new build slaves. We have manually approved the new IP address and also ensured that the GMail account settings are set to allow connections.
After discussing with Ian, we have decided to temporarily ignore the tests as they often cause failures on the build due to timeouts, emails not showing up on time etc.
> [DEVELOPER-2855] Temporary @ignore email based tests due to Gmail blocking new build server

- products/cdk/overview.adoc
CDK 2.0 is releasing 2016-04-19 and will no longer be in Beta.
> Remove "beta" from CDK2 info.

- _layouts/topics-dotnet.html.slim
Now that the .NET webinar vide is live, I think we should link directly to it from the topic page, rather than linking to the webinar registration page.
@lincolnthree can you review please?
> Link direct to .NET preview video

- _layouts/video_page.html.slim
I'm not sure why we switched to active_support's Object::present? method
but I'm switching back to core Ruby methods in an attempt to fix the
production builds.
> [URGENT] Switching from `present?` to core ruby methods

- javascripts/sso.js
- promotions/devnation-discount-code.html.slim
This includes #1057. It hides all the text about the promotion unless you're logged in.
> DEVELOPER-2914 (hide promo code for devnation)

- _lib/reaper.rb
- _tests/test_reaper.rb
An update to the Reaper class to ensure that is also deletes the Docker network associated with a pull request.
> [DEVELOPER-2991] Remove Docker network when a pull request is closed

- _docker/base/Dockerfile
* curl of /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release was failing
silently due to a 301. curl doesn't follow the rediect by default.
* Changed URL from https://www.redhat.com/security/data/fd431d51.txt
to https://www.redhat.com/security/data/fd431d51.txt
> base/Dockerfile Red Hat GPG key location URL update

- products/developertoolset/updates.adoc
* Add an updates page covering Devloper Toolset 4.1 Beta
* (An Updates link in the left nav should automatically be added)
> DEVELOPER-2978 DTS 4.1 Beta product updates page

- products/datagrid/_common/product.yml
Need to update the developers.redhat.com documentation links for JDG 6.6.
> Updated product version and links for 6.6

- products/softwarecollections/updates.adoc
* PR #1090 renamed `products/softwarecollections/get-started-rhel7-nodejs-beta.adoc -> get-started-rhel7-nodejsbeta.adoc`
* Fix  `products/softwarecollections/updates.adoc` to point to the new name.
> DEVELOPER-3017 Fix broken link due to rename

- _docker/drupal/modules/custom/redhat_developers/config/install/filter.format.as_is_html.yml
- _ext/jboss_developer.rb
- _tests/test_drupal8service.rb
Please see https://issues.jboss.org/browse/DEVELOPER-2947 for details.
In Drupal it was 'fixing' bad HTML. Well, turns out it thought the HTML
in the script tags was bad (probably because of our template marker
choice), so it did it's best to fix it. Turns out it actually broke it.
I've created a new html text format that only administrators can use
which doesn't do this correction. I named it 'as-is HTML' so Drupal
doesn't try to fix anything.
In order to test this you'll have to start up Drupal:
```
cd _docker
bundle exec ./control.rb -u --run-the-stack
```
Once that finishes you'll need to visit the fuse connectors page to
verify things are working correctly.
> Fixes DEVELOPER-2947 (fuse connector page)

- _docker/control.rb
- _docker/lib/options.rb
- _docker/test/test_control.rb
- _docker/test/test_options.rb
The PR reaper job is failing: http://jenkins.mw.lab.eng.bos.redhat.com/hudson/view/jboss.org/job/developers.redhat.com-pr_reaper/
This is because the job is trying to wait for searchisko to start, but there is no searchisko container for that scenario.
This update to control.rb ensure that we only wait for Drupal and Searchisko if they are part of the supporting_services required by the job that is executing.
> [DEVELOPER-3025] Only wait for Drupal and Searchisko if necessary

- products/rhel/get-started-dcr7-nodejsbeta.adoc
- products/softwarecollections/get-started-rhel7-nodejsbeta.adoc
- products/softwarecollections/updates.adoc
* Add node.js v4 in a container beta TTHW
* Add link to container TTHW from updates page
* Formatting improvements on RHSCL node4 beta TTHW
> DEVELOPER-3012 RHSCL 2.2 Beta Node.js v4 TTHWs

- _docker/docker-compose.yml.erb
Another attempt to resolve the problem with "port in use" errors. This time we only expose the awestruct port if we're running in a local development environment i.e. not on Jenkins.
> [DEVELOPER-3041] Do not expose Awestruct port on Jenkins

- Gemfile
- Gemfile.lock
Whilst trying to get things to build on the new VMs for the Drupal environment, a persistent stumbling block was the fact that a couple of dependencies are pulled in using the git:// protocol.
The problem occurs on the VMs in that they are behind a proxy and I could not get bundle install to work behind the proxy.
As soon as I moved fetching the dependencies to using HTTPs, then everything works absolutely fine. It would also appear that HTTPS is the recommended approach for Git dependencies as-per the "Security" section on this page: http://bundler.io/git.html
> [DEVELOPER-2936] Updated Gemfile to use HTTPS to fetch Git dependencies

- products/rhel/_common/product.yml
- products/rhel/get-started.adoc
* Add missing Node.js jab to Step 4.
* Fix incorrect links in Step 4.
* Clean up step 4 TTHW for consistency and accuracy.
* Re-org FAQ into installation and development.
* make better use of RHdev content in FAQ
> DEVELOPER-3043: Missing node.js tab on rhel get started

- products/cdk/download.adoc
- products/cdk/get-started.adoc
* Added vagrant box links on download page though
in general people wouldn't see those because after
downloading cdk.zip through the download manager
they would get redirected to the Get Started page.
* Made the download page more consistent with the
Get Started Page.
* Note: given the content of the Get Started Page,
the download page is pretty redundant and should
possibly be replaced with a redirect.
> DEVELOPER-2976 CDK Download Page Add Vagrant box links

- community/contributor/signup.html.slim
This is simple change to prevent two pages having the same description. I'm checking that making this fix percolates through the DCP instances and improves the site search.
> Made description unique

- _docker/control.rb
- _docker/tests/test_control.rb
Small update to control.rb to ensure that we invoke 'npm install' if we're running in a Drupal-based environment.
> [DEVELOPER-3081] Ensured that we invoke npm install during Drupal builds

- _config/site.yml
- _docker/control.rb
- _docker/environments/drupal-dev/docker-compose.yml
- _docker/environments/drupal-production/docker-compose.yml
- _docker/environments/drupal-pull-request/docker-compose.yml
- _docker/environments/drupal-staging/docker-compose.yml
- _docker/lib/options.rb
- _docker/tests/test_options.rb
This pull request introduces the following changes:
- Creates an Awestruct profile for each of the Drupal environments
- Moves the default Awestruct command to be run into the docker-compose.yml file for each environment
- Removes support for the --drupal-nightly option in control.rb
- Correctly sets the Drupal and Searchisko ports in drupal-dev environment to support hard-coded endpoints in twig files
- Updates to options.rb to support the above
> [DEVELOPER-3022] Deploy Awestruct content changes into Drupal

- _layouts/product-base.html.slim
This pull request allows overriding page title on pages inheriting from product-base.html.slim layout.
> Added option to override title on product pages.

- _docker/control.rb
- _docker/tests/test_control.rb
control.rb::determine_docker_host_for_container_ports was trying to
get the IP address of the system hostname, which might not be defined on
developer's machines, before checking whether the hostname `docker`
would resolve.
The expectation is developer's machines with an RHDev docker
environment will have docker defined as a hostname with an
ip address for localhost.
This workaround will still fail cryptically if the hostname docker isn't
defined and the current hostname doesn't resolve to an ip address.
> docker env determine_docker_host fix

- _docker/lib/options.rb
- _docker/tests/test_options.rb
When taking a backup, we do not need to start or wait for any supporting services.
> [DEVELOPER-2937] No supporting services for backup

- _docker/lib/options.rb
To try and lower resource contention on stumpjumper, reduce the number of chrome nodes to 2 per pull request.
> [DEVELOPER-3134] Reduced the number of chrome nodes to 2 by default

- products/softwarecollections/_includes/get-started-rhel7-prereq.adoc
- products/softwarecollections/_includes/get-started-rhel7-step1.adoc
- products/softwarecollections/get-started-rhel7-nodejs.adoc
- products/softwarecollections/get-started-rhel7-python.adoc
* The goals are RHSCL 2.2 updates and making the 30+ get started guides easier to maintain.
* Working: using AsciiDoc to parameterize the text where possible.
* Not Working: Trying to include redundant text from a file. The includes are being rendered as links instead of showing the text.  I can make this work on a plain .adoc processed through awestruct, with no explicit layout or slim file.
* See products/softwarecollections/get-started-rhel7-node.js/  to see how it is failing.   I suspect the layout might be tripping this up.  Hoping @LightGuard, @adelasofia, or someone else could shed some light on this.
> [WIP] [HOLD] DEVELOPER-3049 RHSCL 2.2 Updates with included text

- _docker/tests/test_control.rb
Ensured that we revert the value of the cdn_prefix back to what it originally was after each test run.
> [DEVELOPER-3174] Prevent intermittent unit test failure due to env variable clash.

- _docker/environments/drupal-production/docker-compose.yml
YAML formatting to ensure that Docker Compose can parse the docker-compose.yml for drupal-production environment.
> [DEVELOPER-3175] Fix Drupal Backups

- Rakefile
- _docker/environments/awestruct-dev/docker-compose.yml
- _docker/environments/awestruct-pull-request/docker-compose.yml
- _docker/environments/drupal-dev/docker-compose.yml
- _docker/environments/drupal-production/docker-compose.yml
- _docker/environments/drupal-pull-request/docker-compose.yml
- _docker/environments/drupal-staging/docker-compose.yml
- _docker/lib/default_logger.rb
- _docker/lib/options.rb
- _docker/lib/process_runner.rb
- _docker/lib/pull_request/README.md
- _docker/lib/pull_request/exec_with_git_hub_status_wrapper.rb
- _docker/tests/pull_request/test_exec_with_git_hub_status_wrapper.rb
- _docker/tests/test_options.rb
This pull request adds in initial support for running pull requests against a Drupal-based environment. In particular it adds the ability to be able to send statuses to Github for various parts of the Drupal pull request process without impacting the statuses for the Awestruct build.
The main purpose of this pull request is to make as few changes as possible to the existing Github status framework, whilst integrating the new control.rb functions e.g. --export into status updates.
The main part of this work is more fully documented in the accompanying README.md.
I additionally had to re-add the `unit_tests` service definition in the docker-compose.yml for each environment as I needed a separate container definition to run the tests and run awestruct in the drupal-pull-request environment. …
> [DEVELOPER-1960] Support for Drupal Pull Requests

- _docker/tests/test_rhd_environment.rb
Ensure that we set env variables to nil after the test runs to prevent interference with subsequent tests.
> [DEVELOPER-3200] Fix intermittent test failure

- products/rhel/docs-and-apis.adoc
* update/correct version numbers
* update/correct some RHDev links
* remove RHEL from headings/text.
> DEVELOPER-3219: RHEL Docs and APIs minor fixes

- events/devnation/2016/index.html.slim
This is a simple fix to stop the third video auto-playing. See: http://developers.redhat.com/events/devnation/2016/ for what it shouldn't do.
@insectengine should be able to approve this, as he spotted it.
> Disabled autoPlay on DevNation 2016 page

- products/cdk/get-started.adoc
Should fix: http://developers.redhat.com/products/cdk/get-started/#tab-macLinux. See these broken links: https://www.dropbox.com/s/pekrylxagjrqrzp/Screenshot%202016-06-28%2015.03.02.png?dl=0
> Fixed Vagrant links

- events/devnation/2016/_common/event.yml
This should fix the issue where the morning session refuses to play, claiming that the live event has ended.
> Updated Morning Keynote to fixed video

- _docker/backup/Dockerfile
- _docker/backup/mariadb/MariaDB.repo
- _docker/environments/drupal-production/docker-compose.yml
This PR fixes the failing push of Drupal backups to Github. To do that I have:
1. Introduced a new backup image that has correctly configured version of Git that supports LFS
2. Updated the docker-compose.yml for the drupal-production environment to use this new image.
> [DEVELOPER-3270] Fix failing push of Drupal backup to Github

- _docker/lib/export/export_inspector.rb
- _docker/tests/export/test_export_inspector.rb
In trying the staging export I ran into this error:
/home/awestruct/developer.redhat.com/_docker/lib/export/export_inspector.rb:13:in `determine_expected_filesystem_path': bad value for range (ArgumentError)
from /home/awestruct/developer.redhat.com/_docker/lib/export/export_inspector.rb:47:in `block (2 levels) in inspect_export'
from /home/awestruct/developer.redhat.com/_docker/lib/export/export_inspector.rb:44:in `each_line'
from /home/awestruct/developer.redhat.com/_docker/lib/export/export_inspector.rb:44:in `block in inspect_export'
from /home/awestruct/developer.redhat.com/_docker/lib/export/export_inspector.rb:43:in `open'
from /home/awestruct/developer.redhat.com/_docker/lib/export/export_inspector.rb:43:in `inspect_export'
from …
> Improving ExportInspector

- _docker/lib/backup/backup.rb
- _docker/tests/backup/test_backup.rb
In the code review I missed that the changes to backup were not properly committing the .gz archive of the SQL dump.
> [DEVELOPER-3282] Ensure backup.rb commits .gz archive

- _docker/drupal/drupal-filesystem/web/modules/custom/redhat_developers/config/install/node.type.rhd_microsite.yml
All of the created node types should have this set to false, looks like
this one missed it.
I fixed this in production drupal, but this should fix it even if creating a new drupal instance from scratch.
> DEVELOPER-3288 - Removing the display_submitted text

- _docker/lib/export/sitemap_diff.rb
- _docker/tests/export/diff-sitemap-1.xml
- _docker/tests/export/diff-sitemap-2.xml
- _docker/tests/export/test_sitemap_diff.rb
A small utility class that allows us to manually compare the sitemap.xml within a Drupal instance to that of the current developers.redhat.com site. This is to give us extra confidence that all expected content is in place.
> [DEVELOPER-3284] Allow comparison of Drupal sitemap to current RHD site

- _config/blinkr.yaml
- products/amq/_common/product.yml
- products/amq/get-started.adoc
- products/bpmsuite/_common/product.yml
- products/brms/_common/product.yml
- products/datagrid/_common/product.yml
- products/datavirt/_common/product.yml
- products/datavirt/get-started.adoc
- products/devstudio/_common/product.yml
- products/devstudio/get-started.adoc
- products/devsuite/_common/product.yml
- products/eap/_common/product.yml
- products/eap/get-started.adoc
- products/fuse/_common/product.yml
- products/mobileplatform/_common/product.yml
- products/openshift/_common/product.yml
- products/rhel/_common/product.yml
- products/softwarecollections/_common/product.yml
- products/webserver/_common/product.yml
All products should now show up without GA; however, I need to review Blinkr to make sure that this doesn't cause problems with the documentation.
> DEVELOPER-3273 - Updated products to no longer list GA variables

- products/datagrid/_common/product.yml
JDG 7.0.0 GA'd yesterday, and I have updated the references to point to the latest docs.  Note that the Infinispan Query guide has been removed, while a few additional books have been added to this list.
> Updated references for JDG 7.0.0 GA

- _docker/drupal/drupal-filesystem/web/robots.txt
- _docker/lib/export/drupal_page_url_list_generator.rb
- _docker/tests/export/magic_drupal_sitemap.xml
- _docker/tests/export/test_drupal_page_url_list_generator.rb
This PR works around the fact that at times, the hostname in the Drupal sitemap.xml gets re-written to be 'default'. It parses the list of links from the sitemap.xml and then ensures that it replaces the 'default' hostname with the one specified in the initialisation of the export process.
> [DEVELOPER-3324] Workaround default hostname in drupal sitemap.xml

- _layouts/base.html.slim
See https://issues.jboss.org/browse/RHD-1625. 
I think this is simple enough to just require an engineering-team review.
> RHD-1625 replace "contact us" email to developers@redhat.com

- _layouts/product-base.html.slim
Please see https://issues.jboss.org/browse/DEVELOPER-3318 for full
information.
I've switched to building up the correct URL now instead of using a
relative URL. I also noticed the community links had the same problem,
so I fixed that here as well.
> [DEVELOPER-3318] "Get Started" button on product pages gives a 404

- articles/no-cost-rhel-faq.adoc
- products/rhel/download.adoc
- products/rhel/get-started.adoc
* Provide more prominent instructions for how to get alternate RHEL versions
* Clean up FAQ steps now that downloading is no longer required to upgrade RHdev accounts. (All new RHDev accounts are automatically upgraded as RHDENG-275 from June)
* Fix RHEL get started step 4 formatting typo.
> RHD-1644 Clearer instructions for other RHEL versions

- _docker/lib/export/export.rb
- _docker/lib/export/form_action_rewrite.rb
- _docker/lib/export/httrack_export_strategy.rb
- _docker/tests/export/test_export_form_rewrite/containers.html
- _docker/tests/export/test_export_form_rewrite/nested_directory/more-containers.html
- _docker/tests/export/test_form_action_rewrite.rb
- _docker/tests/export/test_httrack_export_strategy.rb
This PR adds in the re-write of form target URLs to the export process if the target URL for the form matches the Drupal host from which it was exported.
> [DEVELOPER-3323] Added re-write of form action URLs as part of export

- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/system/html.html.twig
See https://issues.jboss.org/browse/DEVELOPER-3366 for more information.
This moves the page top section in Drupal to the very top of the page,
above our navigation.
> [DEVELOPER-3366] Navigation is broken while in Admin

- Gemfile.lock
See https://issues.jboss.org/browse/DEVELOPER-3361 for more information.
The fix was applied at
https://github.com/awestruct/aweplug/commit/4a7a9a1ef69af7a6cf96d9d517f5b5014d07b578
> [DEVELOPER-3361] Missing /quickstarts/sandbox/contributing page in Drupal

- _docker/environments/drupal-dev/rhd.settings.php
- _docker/environments/drupal-pull-request/rhd.settings.php
This PR disables automatic execution of cron in the dev and pull request environments.
To test:
1. bundle exec ./control.rb -e drupal-dev --run-the-stack
2. Navigate to http://docker/admin/config/system/cron
3. Notice that "Run cron every" setting is set to "Never".
> [DEVELOPER-3326] Disabled automatic Cron execution

- _config/site.yml
I'm attempting to hack around vimeo limits by using a local cache that
we'll pull from a know location in the build pipeline.
> Hacking around vimeo limits

- _docker/drupal/scripts/drupal_install_checker.rb
- _docker/tests/drupal/drupal_install_checker_test.rb
Ensures that we automatically answer 'yes' to any prompt from the drush updb command. This prevents the update process from failing otherwise.
> [DEVELOPER-3389] Fixes Drupal not booting in production

- _docker/lib/export/static_export_rsync.rb
- _docker/tests/export/test_static_export_rsync.rb
This PR ensures that we exclude the .snapshot directory from the rsync process. Currently this is causing rsync to staging and production file system locations to fail.
In the absence of being able to integration test the rsync in a local dev environment, I have tested this manually in the staging environment and confirmed that it works as expected.
> [DEVELOPER-3414] Exclude .snapshot directory from rsync

- _docker/environments/drupal-production/docker-compose.yml
- _docker/environments/drupal-staging/docker-compose.yml
This PR fixes an incorrect bind-mount for the Drupal files directory, which is causing uploaded images to be lost each time we re-build Drupal.
> [DEVELOPER-3418] Fix incorrect bind mount for Drupal files directory

- products/cdk/_includes/get-started-cdk2-next-and-faq.adoc
- products/rhel/_includes/get-started-dcr7-intro-step1.adoc
- products/rhel/_includes/get-started-dcr7-next-and-faq.adoc
- products/softwarecollections/_includes/get-started-rhel7-prereq.adoc
- products/softwarecollections/_includes/get-started-rhscl-faq.adoc
- products/softwarecollections/_includes/get-started-rhscl-more-resources.adoc
Fixes DEVELOPER-3432, which is also github issue #1366, the awestruct macros for site base and download manager were not being interpreted correctly.
> DEVELOPER-3432 Fix broken site/download links

- _docker/environments/drupal-production/docker-compose.yml
- _docker/environments/drupal-staging/docker-compose.yml
This PR fixes the bind-mount location for the active configuration directory in Drupal in both staging and production environments.
> [DEVELOPER-3356] Fix incorrect bind-mount location for Drupal config 

- README.md
- _docker/export/Dockerfile
- _docker/lib/options.rb
Small changes to ensure that Drupal pull requests can work.
1. Needed to install the octokit Gem into the export container as a dependency which running the export with the GitHub status wrapper
2. Ensured that we bind all required environment variables when running the export in the PR environments.
> [DEVELOPER-3445] Fixes for Drupal pull requests

- products/dotnet/get-started.adoc
This updates the .NET Getting Started guide to match the style, language and steps used in other guides.
Specifically:
- Let the users use either the GUI or CLI from Subcription Manager
- Don't use sudo (which doesn't work out of the box in all versions of RHEL)
- Mention how `scl` work and how to enable the collection generally
- Add links to upstream repositories and documentation
> Update the .NET Getting Started guide to match the other guides

- _docker/lib/options.rb
- _docker/tests/test_options.rb
This PR adds a '--no-kill' option to control.rb that prevents it from killing the currently running environment. This is required during the transition to Drupal PR building so that any environment started by the current PR job is left intact and not destroyed.
> [DEVELOPER-3445] Added the --no-kill option to control.rb 

- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/rhd.theme
- _docker/environments/drupal-dev/rhd.settings.yml
Please see https://issues.jboss.org/browse/DEVELOPER-3448 for full
information.
I've added the correct location for the account url and also fixed a bug
I had in drupal for which value to use. I've also made the corresponding
changes in prod and staging.
> Fixes DEVELOPER-3348 - Link to user account information page does not work

- javascripts/search.js
- stack-overflow.html.slim
Please see https://issues.jboss.org/browse/DEVELOPER-3453 and
https://issues.jboss.org/browse/DEVELOPER-3454 for full information.
Switched to using `ng-href` in the stack-overflow page.
Modified the javascript to correctly use the right history push.
> Fixes DEVELOPER-3453 and DEVELOPER-3454

- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/system/html.html.twig
- _docker/environments/drupal-production/docker-compose.yml
- _docker/environments/drupal-staging/docker-compose.yml
This PR updates the rollback rsync locations for the staging and production environments to their correct long-term locations.
It also removes the erroneous `#}` at the bottom of each Drupal page as I just noticed it hadn't been fixed.
> [DEVELOPER-3460] Updated rollback locations for staging and production

- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/rhd.theme
- _docker/environments/drupal-dev/rhd.settings.yml
- _docker/environments/drupal-pull-request/rhd.settings.yml.erb
This PR adds the ability to define the protocol over which the DCP should be accessed. This means that environments that need to support HTTPS, can be configured to use the HTTPS endpoint of the DCP to avoid browser security warnings.
> [DEVELOPER-3464] Support HTTPS for site export

- _config/site.yml
- _docker/environments/drupal-dev-local-dcp/apache/httpd-vhosts.conf
- _docker/environments/drupal-dev-local-dcp/apache/httpd.conf
- _docker/environments/drupal-dev-local-dcp/docker-compose.yml
- _docker/environments/drupal-dev-local-dcp/rhd.settings.php
- _docker/environments/drupal-dev-local-dcp/rhd.settings.yml
- _docker/environments/drupal-dev/apache/httpd.conf
- _docker/environments/drupal-dev/rhd.settings.yml
- _docker/environments/drupal-pull-request/rhd.settings.yml.erb
- _docker/lib/rhd_environment.rb
- _docker/tests/test_rhd_environment.rb
Updates to environments:
drupal-dev-local-dcp: Uses local dockerized DCP, and pushes content to it.
drupal-pull-request: Uses dcp.stage.jboss.org, and does not push content to it.
drupal-dev: Uses dcp.stage.jboss.org, and does not push content to it.
This ensures the DCP content is available by default in development mode and in PR builds. In the case where local standalone DCP is required, the 'drupal-dev-local-dcp' environment can be used.
> [DEVELOPER-3465] Switch Dev and PR builds to use staging DCP

- _layouts/product-get-started-dotnet.html.slim
- products/dotnet/_common/product.yml
- products/dotnet/get-started.adoc
- Fix capitalization in banner text
- Remove unexpected step 4; resize rest of the buttons on top
- Fix link to RHEL 7
- Link to steps for registering RHEL 7
- Add a one-liner for quick registration/attaching
- Suggest enabling the dotnet collection permanently
- Fix incorrectly escaped text at the end of the page
> Clean up dotnet docs

- _docker/drupal/scripts/drupal_install_checker.rb
- _docker/tests/drupal/drupal_install_checker_test.rb
This PR puts the fix for the workspace bug into the Drupal start-up scripts so that if we have to re-build the environment, we don't forget to take that step.
> [DEVELOPER-3461] Workspace bug workaround into start-up scripts

- register.html.slim
This introduces a few changes to register.html.slim to ensure that the in-lined Javascript works as expected in the site export from Drupal.
> [DEVELOPER-3509] Ensure /register works on site export

- javascripts/drupal-namespace.js
The `endsWith()` JS function is not supported by IE, therefore we need to use something else to work out where to send the user after they have successfully registered.
> [DEVELOPER-3518] Removed the use of the endsWith() JS function in IE

- _docker/lib/export/export.rb
- _docker/lib/export/export_html_post_processor.rb
- _docker/lib/export/static/.htaccess
- _docker/lib/export/static/robots.txt
- _docker/tests/export/test_export_html_post_processor.rb
- _docker/tests/export/test_static_resources/.htaccess
- _docker/tests/export/test_static_resources/nested/nested-file.txt
- _docker/tests/export/test_static_resources/robots.txt
This PR introduces the `static` directory concept in the export process. You can place any files you want into the `static` directory, and they will be copied into the root of the export.
This process is perfect for copying in things like a `robots.txt` file or a `.htaccess` file (basically anything that would not be fetched by httrack.
> [DEVELOPER-3480] Copy static resources into export directory

- _ext/jboss_developer.rb
- _tests/test_drupal8service.rb
See https://issues.jboss.org/browse/DEVELOPER-3538 for more information.
This addresses content pages (note things like video pages and some
resource pages will still always be updated) going forward. They will
not be updated unless the source is newer than what's already within
Drupal.
To mitigate the extraneous aliases we'll need to run the following SQL
on the production database:
```
CREATE TEMPORARY TABLE tmp_alias
SELECT pid, source, alias
FROM url_alias
WHERE url_alias.pid <> (SELECT MAX(pid)
FROM url_alias AS inner_alias
WHERE inner_alias.alias = url_alias.alias);
DELETE url_alias
FROM url_alias
INNER JOIN tmp_alias
ON url_alias.pid = tmp_alias.pid
```
> FIXES DEVELOPER-3538 (lots of url_aliases)

- _docker/ruby/Dockerfile
Found that with the latest bundler version things with awestruct just weren't working. This fixed that issue.
> Set specific bundler version to prevent errors

- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.promotion_card.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.promotion_card.teaser.yml
See https://issues.jboss.org/browse/DEVELOPER-3405 for full information.
It was decided we'd remove the tags on the promotion page display.
> Fixes DEVELOPER-3405 (tags on promo cards)

- stylesheets/app.scss
Flex short-hand caused IE to set the flex-basis property of the .wrapper class to 0%, which pulled the footer up into the content.
https://issues.jboss.org/browse/DEVELOPER-3570
> [DEVELOPER-3570] Fix Wrapper Class Flex Basis

- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.topic.field_tags.yml
- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/topic/node--topic.html.twig
See https://issues.jboss.org/browse/DEVELOPER-3576 for full information
Blue card tags are no longer required (but should be added for taxonomy purposes) and they are also no longer being displayed on the view.
> Fixes DEVELOPER-3576 (blue card tags)

- products/amq/get-started.adoc
The current developers.redhat.com 's A-MQ getting started page is still on 6.2.1 instead of 6.3. Please update!
JIRA: https://issues.jboss.org/browse/DEVELOPER-3548
> Update Getting started Page to A-MQ 6.3

- _docker/environments/drupal-pull-request/docker-compose.yml
- _lib/github.rb
- _tests/test_github.rb
This PR removes the Blinkr statues from GitHub for each pull request. This will mean you can actually tell if all checks for a PR failed or succeeded without having to browse through them.
> [DEVELOPER-3607] Removed Blinkr GitHub statuses from build pipeline

- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/system/html.html.twig
@MikGue has asked that we point people to use developers@redhat.com rather than developer@redhat.com. 
We made the change earlier, here: https://github.com/redhat-developer/developers.redhat.com/blob/master/_layouts/base.html.slim#L267. But it was not done in the twig version of the file.
> Fixed "contact Us" email in site chrome

- _docker/lib/export/static_export_rsync.rb
- _docker/tests/export/test_static_export_rsync.rb
This PR updates the rsync command used to copy the static HTML export to the Apache server. It prevents the receiving side from deleting any .css files even if they do not exist on the sending side.
This should mean that all .css files continue to exist on the receiving side forever, which will mean that MouseFlow functionality should work as expected.
I have tested this by running the rsync command locally, but I do not believe we actually have a method of testing the rsync command between two hosts until we push it into production as each pull-request build rsyncs to a different location.
> [DEVELOPER-3613] Do not delete CSS from receiving side in rsync

- _cucumber/cucumber.rake
It would appear that we are no longer having the test reports being generated as a result of #1545. As well as being inconvenient that we no longer have the reports, it also causes the build to fail each time as the archive of artefacts build step fails. This attempts to resolve that issue.
Before merging this, please click through to the actual acceptance test job and make sure you can browse to the report!
> [DEVELOPER-3621] Ensure that test reports are generated 

- _docker/environments/drupal-pull-request/docker-compose.yml
This PR updates the URL used in the `Drupal: Acceptance Tests` GitHub status URL to point to the test report rather than the build job itself.
**Note:** I have not updated the Awestruct acceptance test URL as this is very shortly going to be removed.
> [DEVELOPER-3620] Updated acceptance test GitHub status check URL 

- CONTRIBUTING.md
We no longer want to pull from the Google Books API as it is too unreliable. The docs now mandate that all information is provided.
> Updated docs for adding books

- javascripts/events.js
https://issues.jboss.org/browse/DEVELOPER-3429
This fix pre-supposes that all dates coming into the event moment filter are UTC times and that the day, month, and year are the only relevant data points coming back from the service. If dates are encoded to a specific timezone this may skew the displayed dates.
> DEVELOPER-3429 - Event dates not displaying correctly

- _docker/environments/drupal-dev/docker-compose.yml
- _docker/environments/drupal-production/docker-compose.yml
- _docker/environments/drupal-pull-request/docker-compose.yml
- _docker/environments/drupal-staging/docker-compose.yml
- _docker/lib/export/README.md
- _docker/lib/export/drupal_page_url_list_generator.rb
- _docker/lib/export/export_inspector.rb
- _docker/tests/export/test_drupal_page_url_list_generator.rb
- _docker/tests/export/test_export_inspector.rb
This PR updates the export process to fail if there are missing pages. Previously the behaviour was to simply emit a warning if there were pages missing from the export, however these were going un-noticed and the site was being published with pages missing.
I have also included a mechanism to override this default failure behaviour if you absolutely need to. By setting the `drupal.export.fail_on_missing` environment variable to `false`, you can disable the failure behaviour. This allows you to push an export in times when bad things are happening and you just need to get something up. 
I've added the `drupal.export.fail_on_missing` variable to the `export` container definitions in docker-compose.yml for each environment. The variable is currently set to nothing meaning that the failure …
> [DEVELOPER-3605] Export process should fail if there are pages missing

- _docker/control.rb
- _docker/environments/drupal-pull-request/docker-compose.yml
- _docker/lib/rhd_environment.rb
- _docker/tests/test_control.rb
- _docker/tests/test_rhd_environment.rb
This pull request updates our start-up scripts to pre-select the Drupal port in a pull request environment to ensure that it is consistent throughout the life of a pull-request.
> [DEVELOPER-3638] Ensure Drupal port is consistent throughout life of PR

- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/system/html.html.twig
- javascripts/search.js
https://issues.jboss.org/browse/DEVELOPER-3641
This replaces the URL-like string in the HTML with a regex with the hopes that it will not be parsed by the site export. Also sneaking in an additional DTM-related data point because it was there too.
> DEVELOPER-3641 - Site export breaking inline DTM JavaScript

- products/fuse/get-started.adoc
This pull requests implements [FUSEDOC-1661](https://issues.jboss.org/browse/FUSEDOC-1661), which is an enhancement request to document the steps for installing the Fuse on EAP runtime explicitly in the Get Started doc, instead of referencing the JBoss Fuse product docs on the customer portal.
> FUSEDOC-1661 Refactored EAP tab in Fuse Get Started

- products/openjdk/overview.adoc
Update the title to say "OpenJDK" instead of "Red Hat OpenJDK"
> Updated title to 'OpenJDK'

- products/dotnet/get-started.adoc
.NET Core 1.0 is now available for Workstation and ComputeNode as well as Server. Update the text to match that of the python collection, which is also available for all variants of RHEL.
> .NET Core 1.0 is available on all RHEL variants

- register.html.slim
The #{site.base_url} needs to be set based on the correct environment. If not, tests will fail as /register on staging will redirect to the production download manager. I'm not aware of a site variable that can be used to parametrise this.
> Reverted to pushing /register via awestruct

- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/system/html.html.twig
- _layouts/base.html.slim
https://issues.jboss.org/browse/DEVELOPER-3469
Updates the GTM include to be HTTPS-only, to prevent protocol incompatibilities between secure and non-secure access.
> DEVELOPER-3469 - Google Tag Manager script HTTPS always

- products/eap/download.adoc
This link is unlikely to get updated as new versions are released. It also adds little value, so I've simplified the text.
> Removed version number text from WildFly link

- _lib/reaper.rb
- _tests/test_reaper.rb
This PR ensures that we clean-up all Docker  images generated by the pull request when the pull request is closed.
> [DEVELOPER-3653] Clean-up Docker images associated with a pull request

- _docker/control.rb
- _docker/lib/options.rb
- _docker/tests/test_control.rb
- _docker/tests/test_options.rb
This PR adds support for a `--no-pull` option on control.rb. Using this you can bypass the pull of the `redhatdeveloper/drupal-data` image from DockerHub if it already exists on your machine.
For example:
```
bundle exec _docker/control.rb -e drupal-dev --run-the-stack --no-pull
```
This will use the pre-existing `redhatdeveloper/drupal-data` Docker image on your machine. 
Note: If the `redhatdeveloper/drupal-data` image does not exist locally, then the `--no-pull` option has no effect. You must pull the image in this scenario.
> [DEVELOPER-3667] Added --no-pull option to control.rb to bypass Docker Hub

- _docker/drupal/drupal-filesystem/composer.json
- _docker/drupal/drupal-filesystem/composer.lock
- _docker/drupal/drupal-filesystem/web/config/sync/core.extension.yml
- _docker/drupal/drupal-filesystem/web/config/sync/smtp.settings.yml
- _docker/drupal/drupal-filesystem/web/config/sync/system.mail.yml
This pull request enables SMTP for email sending within Drupal. This is achieved by installing and configuring the [Drupal SMTP module](https://www.drupal.org/project/smtp). Please note that we install version 1.0.0-alpha2 and not beta-1 as email sending is broken in beta1.
The Drupal instance is configured to send via smtp.corp.redhat.com which does not require any authentication details.
> [DEVELOPER-3614] Added SMTP support to Drupal for sending of emails

- _docker/environments/drupal-staging/docker-compose.yml
…ging docker-compose file.
corrected typo
acceptance status should match the drupal PR docker-compose file.
removed apache docker from firefox
edited docker firefox task.
reverted changed to drupal dev
removed Service 'docker_firefox' has a link to service 'apache:docker' which is undefined error.
enabling download manager related tests
Ignore download tests
> DEVELOPER-3666: Run Keycloak/DM tests in staging

- javascripts/vendor/keycloak.js
The data being sent to this function is set up to be a specific string. The object being sent in is unrelated to the processing being done here.
> DEVELOPER-3680 - Stop event when messageCallback is not a string

- _docker/lib/export/static_export_rsync.rb
- _docker/tests/export/test_static_export_rsync.rb
We need to host some static files on developers.redhat.com that are not served via Drupal. These will go in the '/cdn' dir on Apache. This PR is to prevent that dir from being removed during an rsync.
I based this PR on: https://github.com/redhat-developer/developers.redhat.com/pull/1643
> Adding exclude for 'cdn' dir

- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/paragraph/paragraph--download.html.twig
Please see https://issues.jboss.org/browse/DEVELOPER-3718 for full information and definition of done.
A `div` tag was closed before it should have been.
> Fixing DEVELOPER-3718 Layout bug on download page

- resources.html.slim
Removed white space below page banner and made filters width fit within the page's content section
> Small style fixes for Resources page

- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/templates/product-pages.html.twig
Should fix product pages' failing referral alert test as there will not be a hard-coded node on the page.
> FIX: Remove hard-coded referral-alert from product page template

- javascripts/sso.js
https://issues.jboss.org/browse/DEVELOPER-3728
Moves the user auth event outside of the authentication to push whether the user is authenticated or not. May change at some point to a different event name based on Search Discovery's input after the New Year.
> DEVELOPER-3728 - Adobe DTM User Auth Events Double-counting

- _docker/drupal/drupal-filesystem/web/config/sync/field.field.paragraph.get_started.field_overview_url.yml
- _docker/drupal/drupal-filesystem/web/config/sync/paragraphs.paragraphs_type.get_started.yml
- _docker/drupal/drupal-filesystem/web/config/sync/paragraphs.paragraphs_type.getting_started_section.yml
- _docker/drupal/drupal-filesystem/web/config/sync/paragraphs.paragraphs_type.getting_started_tab_section.yml
- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/rhd_common.install
- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/paragraph/paragraph--get-started.html.twig
- _docker/lib/export/static_export_rsync.rb
- _docker/tests/export/test_static_export_rsync.rb
Please see https://issues.jboss.org/browse/DEVELOPER-3688 for full information.
We want to move the "Get Started" pages to be called "Hello World". We should also be able to keep the "Get Started" pages for now so we can do the redirects, then remove the old pages.
> Fixes DEVELOPER-3688 Get Started -> Hello World

- stylesheets/app.scss
https://issues.jboss.org/browse/DEVELOPER-3776
Removes the border from code tags when they are within a pre tag.
> DEVELOPER-3776 - Fix styles for code within pre tag

- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/templates/product-pages.html.twig
Fixing the URL of the "Get Started" button to point to the Hello World pages instead of Get Started pages.
> DEVELOPER-3771 Changing the url for the "Get Started" Button

- _docker/lib/export/README.md
- _docker/lib/export/export_html_post_processor.rb
- _docker/lib/export/httrack_export_strategy.rb
- _docker/tests/export/test_export_form_rewrite/remove-drupal-url/index.html
- _docker/tests/export/test_export_html_post_processor.rb
- _docker/tests/export/test_httrack_export_strategy.rb
This PR tries as much as possible to remove all references to the Drupal host from the export of the site.
I've updated the export process to do a few more things:
1. Prevent httrack from adding the "Mirrored from..." to the source of every HTML file. Ideally I wanted to make it add nothing to the file, but this doesn't work when updating a cache of an existing export. So I've configured it to add an empty HTML comment instead
2. It will remove any of the following HTML elements from the DOM of each HTML file in the export:
- `<link rel="shortcut">`
- `<link rel="revision">`
- `<meta name="Generator">`
I've ensured that we only re-write each HTML file once, so the export process needed slightly more tweaking than I originally hoped.
Please note that currently I cannot remove the reference …
> [DEVELOPER-3500] Remove references to Drupal host from site export

- _docker/lib/export/static/googlead73883659545ab5.html
- googlead73883659545ab5.html
This file is needed by Jairus Mitchell in order to convince Google that we have authority to access Google Web master tools for developers.redhat.com.
This works if you see 'google-site-verification: googlead73883659545ab5.html' when browsing to https://developers.redhat.com/googlead73883659545ab5.html (or the equivalent when verifying the PR).
> Google Webmaster Tools authentication file

- javascripts/search.js
https://issues.jboss.org/browse/DEVELOPER-3752
Added logic to prevent timeout call in addition to initialization call. If on resources page, just always restore filters as it will call the updateSearch function.
May also resolve - https://issues.jboss.org/browse/DEVELOPER-3691 due to two calls to the search service being made.
> DEVELOPER-3752 - Fix double-call of search on resources

- stylesheets/_error-pages.scss
Changes the text in buttons on error page buttons to be white.
> Fixes DEVELOPER-3539 error page button text color

- _cucumber/features/help/stack_overflow/DEVELOPER-3035_stackoverflow.feature
- _cucumber/features/step_definitions/edit_account_steps.rb
- _cucumber/features/step_definitions/resources_steps.rb
- _cucumber/features/step_definitions/topics.rb
- _cucumber/lib/helpers/driver_helper.rb
- _cucumber/lib/pages/abstract/site_base.rb
- _cucumber/lib/pages/edit_account_page.rb
This PR is a fix for the random failing SO tests that sometimes occur on PR test runs.
Tests were failing when a scenario clicked on a link that takes the user to stackoverflow.com, the driver was closing the window before the the  stackoverflow.com tab was opened, therefore tests were bombing out.
> DEVELOPER-3812 - Investigate & fix random failing SO tests 

- _docker/lib/backup/reset/backup_reset.rb
- _docker/lib/backup/reset/run.rb
- _docker/tests/backup/reset/test_backup_reset.rb
- _docker/tests/backup/reset/test_run.rb
This pull request introduces a couple of utility classes that help us reset the Git LFS repository checkout on the production VM.  The purpose for doing this is to prevent the Git repository consuming all available disk space on the VM.
The process here is pretty simple, it basically:
1. Deletes the current checkout of the rhd-backups repository
2. re-clones the repository using `git lfs clone`
`git lfs clone` is smart enough to only pull the files within the current branch i.e. master branch for a fresh checkout. Therefore we immediately reclaim the disk-space in use by the repository.
The `backup_reset.rb` class here is designed to run with the `backup` service Docker container definition in the `drupal-production` environment. It is designed this way so that credentials for the Git …
> [DEVELOPER-3758] Prevent backup from using all disk space on production VM

- _docker/environments/drupal-dev/docker-compose.yml
- _docker/environments/drupal-pull-request/docker-compose.yml
- _docker/environments/drupal-staging/docker-compose.yml
- _docker/export/Dockerfile
- _docker/lib/export/export_html_post_processor.rb
- _docker/tests/export/test_export_form_rewrite/404-error/index.html
- _docker/tests/export/test_export_html_post_processor.rb
This PR fixes broken error pages on the site export from Drupal.
It does this by re-writing all absolute links on the error pages back to an absolute form. The value used to replace the relative form of the link is read from the environment variable `drupal.export.final_base_url`. If this value is not set, then it will default to `https://developers.redhat.com`. Any other environment than production should set this variable on the `export` container definition in the environment to ensure that 404 and other error pages are re-written as expected.
At the minute this change only gets applied to the `404-error` and `general-error` page.
**For reviewers:**
1. Navigate to the export of this PR
2. Ensure that `/404-error` page renders correctly, that there are no load errors in the console, and …
> [DEVELOPER-3552] Fix broken 404 error page in export

- Gulpfile.js
- javascripts/vendor/includes.js
PhantomJS and IE do not include the Array.prototype.includes function. This is a polyfill to make that call work as it is used in the urlFilters from search.js around line 606
> Bugfix - Adding Polyfill for Array.includes function

- _docker/drupal/drupal-filesystem/web/config/sync/user.role.product_team.yml
I'm helping some product people and noticed some changes to the permissions that need to be made.
> Allowing product editors access to edit products

- _cucumber/features/primary_nav/primary_nav.feature
- _cucumber/features/step_definitions/common/navigation_steps.rb
- javascripts/sso.js
- stylesheets/_header.scss
Jira: [DEVELOPER-1754](https://issues.jboss.org/browse/DEVELOPER-1754)
- During page rendering we only display Login | Register links .
- Login | Register should then be replaced by user name and logout link once Keycloak JS client detects logged in user.
> DEVELOPER-1754 Fixed visibility of logout link

- _cucumber/features/register/basic_registration.feature
- _cucumber/features/user_profile/user_profile_edit.feature
Company field is no longer required when registering. Removed tests for this.
NOTE: Registrations will continue to fail as the IT backends still return a 500 error so it's not possible to register.
> DEVELOPER-3914 - Remove company field from manditory checks

- stylesheets/_home.scss
See: https://issues.jboss.org/browse/DEVELOPER-3916
So as to avoid insecure content load warnings on the developers.redhat.com homepage, I've updated the image src URLs to be HTTPS endpoints.
To test:
- Visit the homepage of the exported site and verify that all images are loaded from a HTTPS endpoint
> [DEVELOPER-3916] Updated homepage image src URLs to be HTTPS 

- _docker/lib/export/README.md
- _docker/lib/export/httrack_export_strategy.rb
- _docker/tests/export/test_httrack_export_strategy.rb
Please see DEVELOPER-3821.
This PR incorporates the work-around to the httrack SIGFAULT error after a given number of exports has run into the export process itself. The work-around to the SIGFAULT error is to simply delete the httrack cache to get it to run from fresh. This PR adds a monitor to the number of times we have run the export process and once that count exceeds a threshold, performs the delete of the httrack cache automatically.
The default number of allowed exports has been set to 750, which is a "safe" number for production. We typically see the SIGFAULT error in httrack at around the ~1000 update mark in production.
**How to test**
Clone the branch for this PR into your local environment.
1. In the `drupal-dev` docker-compose.yml, add the following to the `export` container …
> [HOLD] [DEVELOPER-3821] Include httrack SIGFAULT workaround into export process

- stylesheets/_topics.scss
[DEVELOPER-3585](https://issues.jboss.org/browse/DEVELOPER-3585)
Fixes the ovelapping text in Topics pages' blue box.  [See screenshot](https://www.dropbox.com/s/7x92w5maqkbu250/Screenshot%202017-03-08%2013.04.38.png?dl=0)
> DEVELOPER-3585 Fixes topics main promo mobile height

- javascripts/downloads.js
OpenJDK has an early access (EA) release of OpenJDK 9. Currently this is not recognized as a pre-GA release, and thus takes the primary slot on the page. 
I've updated the code to recognize this as a pre-release, resulting in both the EA of OpenJDK 9 and the latest OpenJDK 8 GA being shown. 
See: https://developers-pr.stage.redhat.com/pr/1791/export/products/openjdk/download/
The OpenJDK team are happy with this change.
> Recognize 'EA' as a pre-GA release on download pages

- _cucumber/features/register/basic_registration.feature
- _cucumber/features/step_definitions/register_steps.rb
This PR fixes the broken registration flow for KC DM tests. Until recently the flow was broken, now it has been fixed and verify email address has been introduced.
> Developer 3945 - Update Registration tests

- _ext/pipeline.rb
Now that connectors and books are indexed directly from Drupal. We no longer need the awestruct pipeline to push either into Searchisko. Because this is still happening, we are having duplicate issues.
> Removed unnecessary pushes to searchisko

- 404-error.html.slim
- general-error.html.slim
- search.html.slim
Minor changes:
- Added back 'ignore_export: true' to 404-error.html.slim and general-error.html.slim which had been removed as part of https://github.com/redhat-developer/developers.redhat.com/pull/1797
- Commented out the 'tags' portion of search results. These were not being displayed, per UX request, but the code was causing odd spacing.
> Added ignore_export to error pages

- _cucumber/features/downloads/downloads_page.feature
- downloads.html.slim
https://issues.jboss.org/browse/DEVELOPER-3936
Should replace the third item "JBoss Developer Studio" with "Red Hat Development Suite" in the Most Popular section on /downloads
> DEVELOPER-3936 - Replace JBDS downloads with Dev Suite

- javascripts/downloads.js
https://issues.jboss.org/browse/DEVELOPER-3924
Product download pages should have a proper-looking table that lists downloads by version, with the same version and description not repeated between files. Also fixed the alignment of the previous downloads section.
Example URLs would be /products/rhel/download AND /products/devsuite/download
> DEVELOPER-3924 - Download artefacts incorrectly grouped for devsuite

- _cucumber/environments/docker-compose.yml
- _cucumber/features/downloads/downloads_page.feature
- _cucumber/features/support/browsers.rb
- _cucumber/lib/options/run_tests_options.rb
- _cucumber/lib/pages/abstract/generic_base_page.rb
- _tests/_cucumber/test_run_tests_options.rb
Updated the --run-tests and run-test-options to enable running tests via browserstack (in docker and outside)
> DEVELOPER-3912: Update Browserstack configuration for running on jenkins

- javascripts/search.js
This should hopefully fix the issues with resources page errors for time-based searches.
> Remove timezone-specific data from dates on search results

- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/paragraph/paragraph--download.html.twig
[DEVELOPER-3968](https://issues.jboss.org/browse/DEVELOPER-3968)
Fixes title/content alignment in product download pages. [screenshot](https://www.dropbox.com/s/pswiam6hvbc24ef/Screenshot%202017-03-28%2010.14.37.png?dl=0)
Pretty minor change, just added `<div class="large-24 columns"></div>` to fix the grid.
> DEVELOPER-3968 Fixed alignment in product download pages

- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/node--article.html.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/video/node--video-resource.html.twig
- _layouts/quickstart.html.slim
- _layouts/ticket-monster.html.slim
- _layouts/video_page.html.slim
- events/devnation/2016/index.html.slim
- events/devoxx/2015/index.html.slim
- events/devoxxfrance/2016/index.html.slim
- events/gids/2016/index.html.slim
- events/javaone/2015/index.html.slim
- events/javaone/2016/index.html.slim
- events/judcon/2016/brno/index.html.slim
- events/msbuild/2016/index.html.slim
[DEVELOPER-4053](https://issues.jboss.org/browse/DEVELOPER-4053)
Add `<meta name="DCP:WebpageSearchExclude" content="true">` to webpages that should not appear in the rht_website results. I.e those that have a more specific version of the content.
> DEVELOPER-4053 Added WebpageSearchExclude meta tag

- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.media.image.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.media.image.media_browser.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.scheduled_update.multiple_node_embargo.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.scheduled_update.node_embargo.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.media.image.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.media.image.embedded.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.media.image.thumbnail.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.extension.yml
- _docker/drupal/drupal-filesystem/web/config/sync/editor.editor.rhd_html.yml
- _docker/drupal/drupal-filesystem/web/config/sync/embed.button.media_browser.yml
- _docker/drupal/drupal-filesystem/web/config/sync/entity_browser.browser.image_browser.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.media.image.image.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.scheduled_update.multiple_node_embargo.field_moderation_state.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.scheduled_update.node_embargo.field_moderation_state.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.scheduled_update.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.storage.scheduled_update.field_moderation_state.yml
- _docker/drupal/drupal-filesystem/web/config/sync/filter.format.rhd_html.yml
- _docker/drupal/drupal-filesystem/web/config/sync/media_entity.bundle.image.yml
- _docker/drupal/drupal-filesystem/web/config/sync/scheduled_updates.scheduled_update_type.multiple_node_embargo.yml
- _docker/drupal/drupal-filesystem/web/config/sync/scheduled_updates.scheduled_update_type.node_embargo.yml
- _docker/drupal/drupal-filesystem/web/config/sync/views.view.moderation_history.yml
JIRA: https://issues.jboss.org/browse/DEVELOPER-3976
Within CKEditor (the WYSIWYG editor in Drupal) you should see two new icons: a star and an 'E'. The star is for media (there may be two already in the view). The 'E' is for embedding nodes.
You should be able to click on the star, upload a new image into the media library and place an image from the library into the editor.
> DEVELOPER-3976 CKEditor buttons for media library

- _cucumber/features/help/forums/DEVELOPER-3057_forums.feature
- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/system/html.html.twig
- _layouts/base.html.slim
- products/dotnet/_common/product.yml
[DEVELOPER-4042](https://issues.jboss.org/browse/DEVELOPER-4042)
Changed ".NET Runtime for Red Hat Linux" to ".NET Runtime for Red Hat Enterprise Linux" in:
- /products/
- /downloads/
- Main navigation
- /forums/
and updated acceptance tests
> DEVELOPER-4042 Fixed .Net product name

- stylesheets/_global-wrapper.scss
[DEVELOPER-4056](https://issues.jboss.org/browse/DEVELOPER-4056)
Fixed: Side navigation in Article pages runs over footer when the height of the window is not tall enough to fit it in the content area.
> DEVELOPER-4056 Fixed articles layout nav

- _docker/drupal/drupal-filesystem/web/config/sync/views.view.cheat_sheets_rest_export.yml
For the tag field, I changed the REST export so that it lists a comma delimited string.  This allows for the name of the tag to be exported instead of the taxonomy id associated with it.
> DEVELOPER-3846 - Fixed the tag export to reflect string representation

- _docker/lib/export/drupal_page_url_list_generator.rb
- _docker/lib/export/export_html_post_processor.rb
- _docker/lib/export/export_urls.rb
- _docker/tests/export/test_drupal_page_url_list_generator.rb
- _docker/tests/export/test_export_urls.rb
This PR updates the fetch, save and re-write of the sitemap.xml during the export process to take into account the `drupal.export.final_base_url` environment parameter.
This allows the user to set the URL that should appear within the exported sitemap.xml on a per-environment basis. We already use this parameter to re-write URL locations on error pages as part of the export HTML post-processing, so integration here was fairly trivial.
For reviewers:
1. Allow the export for this PR to run
2. Visit the sitemap.xml for this PR and ensure that it has the correct URL for the export location and not https://developers.redhat.com
3. Ensure that the links within the sitemap.xml are pointing to genuine locations.
> [DEVELOPER-4023] Ensure sitemap.xml contains correct URL for each environment

- javascripts/downloads.js
To test: Navigate to '/products/cdk/download/' and notice that 2.4 should now be appearing in the download table.
The reason this was not being displayed is that the description 'Red Hat Container Tools' mirrored the 3.0 Beta version. As a result, 'Red Hat Container Tools' was being clipped off for version 2.4.
> DEVELOPER-4064 - CDK download page does not mention CDK 2.4 for the CDK 2.4 bits

- .gitignore
- package.json
This PR locks the versions of the npm dependencies used by the project to prevent using newer dependency versions that may not work.
> [DEVELOPER-4077] Lock npm dependency versions

- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.books.field_isbn.yml
- _docker/drupal/drupal-filesystem/web/config/sync/views.view.books_rest_export.yml
- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/rhd_common.module
This fixes the ISBN requirement. The export view should display an empty string if there is no ISBN available.
> DEVELOPER-4071 - Remove the requirement for an ISBN for books

- _layouts/get-started-item.html.slim
Adds 'DCP:WebpageSearchExclude' meta tag to quickstart, ticket-monster, and demo pages. This should have been part of [DEVELOPER-4053](https://issues.jboss.org/browse/DEVELOPER-4053)
To review: 
1.  go to https://developers-pr.stage.redhat.com/pr/1869/export/quickstarts/portal/
2.  open the page source
3.  search for the meta tag by doing a keyword search of 'DCP:WebpageSearchExclude'
> DEVELOPER-4053 Fixed WebpageSearchExclude meta tags

- _cucumber/features/help/forums/DEVELOPER-3057_forums.feature
- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/system/html.html.twig
- _layouts/base.html.slim
- products/amq/_common/product.yml
[DEVELOPER-4079](https://issues.jboss.org/browse/DEVELOPER-4079)
Took the '-' out of the name of the Red Hat JBoss AMQ product.
This should have been done in 2 places:
- 'Technology' menu drop-down under the INTEGRATION AND AUTOMATION section.
- downloads page in /downloads/
> DEVELOPER-4079 Renamed Red Hat JBoss AMQ

- _docker/drupal/drupal-filesystem/db-migrations/20170518195752_fuse_overview_fix.php
I'm attempting to "restore" the Overview page with this.
JIRA: https://issues.jboss.org/browse/DEVELOPER-4095
Hopefully, you don't need to flush the cache, but maybe it will be needed. You can test this by navigating to the Fuse Product Page and NOT receive a 404.
> DEVELOPER-4095 No more 404/error for Fuse Overview

- _docker/environments/drupal-staging/docker-compose.yml
- _docker/lib/staging-sync/database_sync.rb
- _docker/lib/staging-sync/run.rb
- _docker/tests/staging-sync/test_database_sync.rb
This pull-request adds the ability to sync content from production environment Drupal instance into the staging environment (developers.stage.redhat.com) Drupal instance. This is needed so that staging is more representative of production.
The work in this PR builds on what we know already works in dev and PR environments, namely using a Docker data image to obtain most of the content from Production. The staging Drupal instance has been re-configured in the `docker-compose.yml` for the `drupal-staging` environment to mount the active Drupal configuration and any images from production.
The major difference here is how we apply the database synchronisation. As the database in the staging environment is a fully IT managed MariaDB instance, we cannot use the current Docker-based approach to …
> [DEVELOPER-4044] Sync production Drupal content into staging environment

- _docker/control.rb
- _docker/java/Dockerfile
- _docker/searchisko/Dockerfile
- _docker/tests/test_control.rb
This PR updates the Dockerfile for the Java image used on the project to correctly install the latest JDK 8 update. We had to move from JDK 7 as Oracle has removed support for it unless you have a contract with them.
In this PR we:
1. Update the Java Dockerfile to install the latest JDK 8
2. Ensure that we tag the build of the Java image as version 3.0.0 to show things have changed
3. Update any dependent images to use the new Java image version (searchisko only really)
4. Update the tests to ensure we're building images as expected
For reviewers:
Verify that all docker images built as part of this build (the build not failing will ensure this is working.)
> [DEVELOPER-4169] Fix broken Java Docker image

- _docker/lib/export/static/404-error/index.html
- _docker/tests/export/test_export_html_post_processor.rb
Currently the 404 page is excluded from the sitemap.xml of Drupal and is therefore not included in the site export. The root cause of this currently appears to be an issue with Drupal that is responding with a 404 status code when the page actually exists.
This PR works around this by simply copying in the current 404 page of the site into the export as a static resource. This will work until we work out the root cause in Drupal.
For reviewers:
- Navigate to /404-error on the site export of this PR. Look at the page source and see that page links take you to developers.redhat.com
> [DEVELOPER-4176] Ensured 404 page is copied into site export

- _docker/drupal/drupal-filesystem/composer.json
- _docker/drupal/drupal-filesystem/composer.lock
- _docker/drupal/drupal-filesystem/web/config/sync/views.view.vimeo_videos.yml
- _docker/drupal/drupal-filesystem/web/config/sync/views.view.youtube_videos.yml
To test this, you will want to view:
http://stumpjumper.lab4.eng.bos.redhat.com:36892/drupal/videos/vimeo
http://stumpjumper.lab4.eng.bos.redhat.com:36892/drupal/videos/youtube.
I left the combined version (http://stumpjumper.lab4.eng.bos.redhat.com:36892/drupal/videos) in case it will be used elsewhere. I don't think it's needed, but I need to split the drupal and vimeo videos for DCP indexing.
> ViewUpdate - Separated Drupal Video views by vimeo and youtube.

- _docker/drupal/drupal-filesystem/web/config/sync/views.view.vimeo_videos.yml
- _docker/drupal/drupal-filesystem/web/config/sync/views.view.youtube_videos.yml
Updated the view for - https://issues.jboss.org/browse/DEVELOPER-3942
To test this: Visit http://stumpjumper.lab4.eng.bos.redhat.com:36894/drupal/videos/vimeo and http://stumpjumper.lab4.eng.bos.redhat.com:36894/drupal/videos/youtube and observe that 'field_video_publish_date' is now displaying in ISO format. This will be used for indexing the sys_created value in DCP.
> DateFixVideoRESTExport - Date format is now UTC and ISO format

- stylesheets/_alerts.scss
This PR fixes the image paths with _alerts.scss which is causing Awestruct to fail in staging and production.
Unfortunately I don't believe there is anyway to test this not in staging or prod as we don't use the cdn() function in PR environments.
> [DEVELOPER-4212] Fixed image paths within _alerts.scss 

- _blinkr/config/pr_blinkr.yaml
- _blinkr/config/stage_blinkr.yaml
Dropped Blinkr threads to 15 as using 20 may be causing intermittent timeouts.
> Reduced Blinkr threads to 15 

- javascripts/nav-highlight.js
https://issues.jboss.org/browse/DEVELOPER-4075
When on dotnet topic and dotnet product pages only the correct navigation heading should be highlighted not both.
> DEVELOPER-4075 - Both Topics and Technologies menu items are active for dotnet

- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/topic/node--topic.html.twig
- javascripts/topics.js
- stylesheets/_topics.scss
HACKATHON
**1.  [DEVELOPER-3682 - Topic white cards are not fully loaded for mobile views](https://issues.jboss.org/browse/DEVELOPER-3682)**
What to check: 16 white cards should be loaded on desktop, tablet and mobile.
Also fixed width of 4 top white cards on tablet.
**2. [DEVELOPER-3623 - Topics page cards overflow and disrupt page structure](https://issues.jboss.org/browse/DEVELOPER-3623)**
In short, this was fixed (screenshot from /devops) : https://www.dropbox.com/s/81kihngprckaviq/Screenshot%202017-06-15%2011.22.54.png?dl=0
> DEVELOPER-3682 and 	DEVELOPER-3623 Fixed Topics' white cards

- _docker/drupal/drupal-filesystem/web/config/sync/views.view.vimeo_videos.yml
- _docker/drupal/drupal-filesystem/web/config/sync/views.view.youtube_videos.yml
This fixes the formatting of Drupal Target Products. These can be reviewed at:
http://stumpjumper.lab4.eng.bos.redhat.com:36906/drupal/videos/vimeo
http://stumpjumper.lab4.eng.bos.redhat.com:36906/drupal/videos/youtube
You will want to add a target product for both vimeo and youtube. Once you add the target product, observe that the string appears in the REST views above.
Part 2 will include the fixes to the JS. The target products are entity links, so the text is fixed and needs to be updated on the JS side.
> DEVELOPER-4215 [PART 1] - Updated target_product export view

- javascripts/developer-materials.angular.js
HACKATHON -- [DEVELOPER-3362 'Publish date' filter is broken on product pages learn](https://issues.jboss.org/browse/DEVELOPER-3362)
Fixed the 'Publish Date' filter on product learn pages
> DEVELOPER-3362 Fixed products learn pages date filter

- _docker/drupal/drupal-filesystem/web/config/sync/embed.button.node.yml
- _docker/drupal/drupal-filesystem/web/config/sync/entity_browser.browser.media_browser.yml
Two of the three tabs in the media browser were not working, so I took
them out.
The node embed button was only embedding the node id, it is now
embedding the teaser view of the node.
I'm considering this as part of DEVELOPER-3978.
When you use the media library button you will only be able to place a media item. For Node embedding, you will now see the teaser form of the embedded node.
> DEVELOPER-3978 - Modified the media browser/entity embed

- _docker/lib/export/httrack_export_strategy.rb
- _docker/tests/export/test_httrack_export_strategy.rb
We are experiencing random failures of the cache roll-over logic for  the export process. It would appear that `FileUtils.mv` in Ruby 2.1.0 will randomly fail when `mv`-ing a directory if the target directory already exists.
As a work-around to this issue, we now first delete any previous cache roll-over if it exists. It is safe for us to delete the previous cache roll-over as when we do so, we are in the process of creating a new one.
Unfortunately this isn't an easy one to test, so perhaps just a code review on this PR.
> [DEVELOPER-4224] Prevent "Directory Exists" error on export cache roll-over

- _cucumber/features/primary_nav/primary_nav.feature
- _cucumber/features/search/search.feature
- _cucumber/features/smoke_test/smoke_tests.feature
- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/solution/page--rhd-solution-overview.html.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/system/html.html.twig
PLEASE REVIEW BUT DO NOT MERGE -- If approved it will be merged once the redirects are ready to go live
[DEVELOPER-4049 - Move all topics under '/topics' URL](https://issues.jboss.org/browse/DEVELOPER-4049)
- Updated main navigation Topics' links from '/<topic-name>' to '/topics/<topic-name>'
- Updated Acceptance tests
- Updated links in page--rhd-solution-overview.html.twig
- Updated DTM code
> [HOLD] DEVELOPER-4049 Move all topics under /topics URL

- _docker/drupal/drupal-filesystem/web/config/sync/embed.button.media_browser.yml
You'll have to pick either an embedded or thumbnail view when you place
a media item.
To test this you'll want to try to embed a video using the media embed button. You'll see an option for how you want to embed the media.
> Could not embed videos previously.

- javascripts/build.js
- typescript/rhdp-search/rhdp-search-results.ts
To test: Navigate to http://stumpjumper.lab4.eng.bos.redhat.com:36928/search?q=fuse and check the Demo or Quickstart filter. Load More should no longer load duplicates. For reference, you can check the main site with the same filters. You will notice that the last items are often duplicated.
https://issues.jboss.org/browse/DEVELOPER-4201
> DEVELOPER-4201 - New search 'Load More' has inconsistent behavior

- _docker/drupal/drupal-filesystem/web/config/sync/metatag.metatag_defaults.global.yml
Look at any page within Drupal and also some product pages. Make sure they are absolute links. Ideally the export process works just fine, however, they may not. This is just on the Drupal side for testing.
> DEVELOPER-3994 - rel="canonical" absolute links

- javascripts/downloads.js
https://issues.jboss.org/browse/DEVELOPER-4252
Specifically the /products/amq/download/ page layout in Firefox was all messed up.
Local environment isn't working at the moment, so putting this change in to give it a look in FF.
> DEVELOPER-4252 - Broken download page layout in Firefox

- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/rhd.theme
Our Drupal logs are congested with errors around trying to get a
property from a non-object based around line 259 of the rhd.theme file.
I'm pretty sure we only need this to run an actual node is being viewed.
> The comment says it all

- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/rhd.theme
The node check removed the ddo object on some pages, causing script errors and disabling other scripts.
> DEVELOPER-4258 - Remove Node Check

- _cucumber/features/help/forums/DEVELOPER-3057_forums.feature
- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/system/html.html.twig
- products/dotnet/_common/product.yml
Mike updated the title on the product and would like the link in the technology menu to match the title of the product.
> DEVELOPER-4290 - Mike updated the product title

- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/node--article.html.twig
[DEVELOPER-4296 - Subscription article not showing up in on-site search](https://issues.jboss.org/browse/DEVELOPER-4296)
Removed DCP:WebpageSearchExclude tag from Drupal article pages, so articles will not be excluded from the search results.
Easiest way to review this is to go to one of the Drupal articles like '/articles/using-java-rhel-7-openjdk-8/' look at the page source and do a quick search for **DCP:WebpageSearchExclude**. The tag should not be found.
Note: articles will not be shown in the search results until this is merged and the DCP re-indexes the pages.
> DEVELOPER-4296 Removed search exclude from Drupal articles

- _docker/lib/pull_request/clean_up/pull_request_cleaner.rb
- _docker/tests/pull_request/clean_up/test_pull_request_cleaner.rb
This PR updates very slightly the PR clean-up code to ensure that we delete all Docker images associated with a pull request.
**For Reviewers:**
There isn't really a good way to test this. Unit tests have been updated as part of the PR, so probably best just to perform a code review.
> [DEVELOPER-4262] Delete all Docker images associated with a pull request

- _docker/lib/process_runner.rb
- _docker/lib/pull_request/clean_up/pull_request_cleaner.rb
- _docker/tests/pull_request/clean_up/test_pull_request_cleaner.rb
- _docker/tests/test_process_runner.rb
The previous PR for this issue introduced a regression whereby the clean-up job now fails if there are no Docker images to be removed. This PR fixes that regression.
**For Reviewers:**
- Another code review please
> [DEVELOPER-4262] Ignore failure of docker rmi command if there are no images to remove

- javascripts/build.js
- typescript/rhdp-search/rhdp-search-box.ts
[DEVELOPER-4241 - Important security issue present on developers.redhat.com](https://issues.jboss.org/browse/DEVELOPER-4241)
To review:
1. go to /search/
2. insert this malicious content into Search field:
`<script>alert('test');</script>`
The term searched should be _alert('test');_ without the html _tags_
> DEVELOPER-4241 strips HTML tags from search input

- _docker/environments/drupal-dev/rhd.settings.yml
- _docker/environments/drupal-pull-request/rhd.settings.yml.erb
Maintenance updates for dev environments to point to the correct URL for DTM staging since ITOS is being shut down.
@LightGuard or @paulrobinson this will need to be done on staging too. If you would change the Staging config's DTM code to point to: https://dpal-it-marketing.int.open.paas.redhat.com/developers
Also, if you want to update the Sentry config to point to version 3.17.0 this is probably a good time to do that too.
> DPAL updates for dev DTM

- .gitignore
- _docker/drupal/Dockerfile
- _docker/drupal/logrotate/httpd
- _docker/environments/drupal-dev/docker-compose.yml
- _docker/environments/drupal-production/docker-compose.yml
- _docker/environments/drupal-staging/docker-compose.yml
This PR makes it easier to access the Drupal log files without having to access the Drupal container. Additionally log files survive each Drupal deployment meaning that errors can be tracked over time.
Within this PR we configure [logrotate](http://www.linuxcommand.org/man_pages/logrotate8.html) within the Drupal container and also provide a configuration to ensure that we correctly rotate the Apache log files. Additionally we provide bind-mounts at the Apache log file location for `drupal-dev`, `drupal-staging` and `drupal-production` environments. This helps to ensure log files survive container restarts.
The logrotate configuration ensures:
- log files are rotated each day
- log files are rotated if they reach 100M in size or greater
- log files are suffixed with .1, .2, .3 etc. as …
> [DEVELOPER-4134] Provide easier access to Drupal log files for error debugging 

- javascripts/build.js
- stylesheets/_searchapp.scss
- typescript/rhdp-search/rhdp-search-app.ts
- typescript/rhdp-search/rhdp-search-query.ts
[DEVELOPER-4245 - Add loading image while waiting for results](https://issues.jboss.org/browse/DEVELOPER-4245)
Requirements:
The amount of time to return search results can be multiple seconds. There should be an image showing that loading is happening so users do not get confused.
To test:
1.  Search for 'eap'
2. Loading gif should show while results load
3. Click on the 'books' filter (this one takes the longest so you see the gif for a bit
> DEVELOPER-4245 Added loading image in search results

- _docker/drupal/drupal-filesystem/web/config/sync/pathauto.pattern.cheat_sheet.yml
I don't have a ticket for this yet. Simply goes from
/cheat-sheet/[node:title] -> /cheat-sheets/[node:title]
I know there's more to it than that.
> [HOLD] DEVELPER-4078: Tiffany wanted the auto alias to be plural

- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/system/html.html.twig
- stylesheets/_header.scss
1. Updated footer from Copyright © 2016 Red Hat Inc. to Copyright © **2017** Red Hat Inc.
2. Fixed hover and focus states for the main nav, mostly these issues:
- Menu item shouldn't be white on focus state [Screenshot of issue](https://www.dropbox.com/s/dubfigfyfedjjo4/Screenshot%202017-07-26%2007.45.53.png?dl=0 )
- If on topics page, 'Topics' should be yellow, unless on hover (when sub-menu is open) [Screenshot of issue](https://www.dropbox.com/s/dmwwaxuvs0grq9p/Screenshot%202017-07-26%2007.46.47.png?dl=0)
> Minor fixes

- forums.html.slim
[DEVELOPER-4346 - Forums - Add read-only notice to all products](https://issues.jboss.org/browse/DEVELOPER-4346)
All of the product forums (except "cdk","developertoolset","devstudio") listed in /forums/ should have the following message under the product name:
> “PLEASE NOTE: This forum will become read-only on September 1st, 2017. You can now post your Red Hat <product> developer questions to StackOverflow using the <relevant tags link>. Why are we doing this? <link to artcile>.”
> DEVELOPER-4346 Forums page - Added read-only notice to all products

- _docker/drupal/drupal-filesystem/web/config/sync/views.view.cheat_sheets_rest_export.yml
https://issues.jboss.org/browse/DEVELOPER-4259
To review: Visit http://stumpjumper.lab4.eng.bos.redhat.com:36978/drupal/cheat-sheets and notice that "created" now shows the appropriate date.
DCP will pick up the and display it as yyyy-mm-dd.
> DEVELOPER-4259 - Incorrect date for cheat sheets in search results

- downloads.html.slim
https://issues.jboss.org/browse/DEVELOPER-4341
Stops the Downloads page from being Awestruct-built. Content update will happen once this is in production.
> DEVELOPER-4341 - Remove links to non-existent mobile download

- javascripts/drupal-namespace.js
- products/rhamt/_common/product.yml
- stack-overflow.html.slim
https://issues.jboss.org/browse/DEVELOPER-4351
To test: Visit http://rhdp-jenkins-slave.lab4.eng.bos.redhat.com:36996/stack-overflow#!q=rhamt and make sure that the stackoverflow data populates.
Also, you will need to check the help page: http://rhdp-jenkins-slave.lab4.eng.bos.redhat.com:36996/products/rhamt/help (this will only work on the Drupal site--not the export) I had to update the product field in Drupal in order for the help page to pull in the SO data. We will likely need to do this in production as well. From what I can tell, this shouldn't cause any problems since there is no forum page.
> DEVELOPER-4351 - Add RHAMT to Stack Overflow Dropdown

- _docker/lib/export/export_html_post_processor.rb
- _docker/tests/export/test_export_form_rewrite/index/index.html
- _docker/tests/export/test_export_html_post_processor.rb
This PR fixes an issue added in #2002 that was merged too early. The previous version of the code added a double trailing slash to the access.redhat.com documentation links resulting in blinkr reporting broken links.
This attempts to rectify this.
**For reviewers**
- Check the blinkr report for 404 on access.redhat.com doc links
- Verify if any of them are being caused by missing the trailing `index.html` suffix
> [DEVELOPER-4373] Fixed addition of double trailing slash to access.redhat.com doc links

- _layouts/get-started-item.html.slim
I don't see the point in doing this any longer, things don't change, and if we're going to fix broken links, I'd rather do it in Drupal and not worry about things being overwritten.
> No longer pushing any get started items to drupal

- jboss-docker.html.slim
- variants/hero2.html.slim
- variants/join-now-2.html.slim
We'll need to fix the broken links in Drupal once this goes through.
> Adding some more files to not push

- _docker/export/Dockerfile
I have moved the httrack fork used by the RHDP program to be under the redhat-developer organisation within GitHub.
This PR simply updates the export Docker container build to now pull from that location.
**For Reviewers**
- Simply ensure that the export process for this PR has worked as expected
> [DEVELOPER-4034] Relocate httrack fork to redhat-developer organisation

- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.promotion_page.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.promotion_page.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.promotion_page.field_exclude_from_search.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_exclude_from_search.yml
- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/promotion-page/node--promotion-page.html.twig
[DEVELOPER-4348 Exclude the Cheat Sheet promotion pages from on-site search](https://issues.jboss.org/browse/DEVELOPER-4348)
Added a checkbox to Promotions content type to exclude a page from the search page results.
If the checkbox is checked, a meta tag `<meta name="DCP:WebpageSearchExclude" content="true">` is added to the page, which the dcp indexer picks up and adds a flag to exclude that page from the search results.
To review: 
1. Go to edit the following page (or any of the promotion pages): /promotions/docker-cheatsheet/
2. Check the 'Exclude from search' checkbox at the bottom and save the changes
3. In the saved page, look at the source code and do a quick search for _DCP:WebpageSearchExclude_
If the checkbox was checked, you should be able to find the meta tag in the source …
> DEVELOPER-4348 Added exclude from search option to promotion content type

- javascripts/referrer.js
Per Mark Little's request, the link in the /middleware referrer alert link was updated to: https://developer.jboss.org/blogs/mark.little/2017/08/31/we-are-moving?_sscc=t
To review, go [here](https://developers-pr.stage.redhat.com/pr/2019/export/middleware/?referrer=jbd) and check that the link in the alert goes to the link above.
> Updated /middleware referrer alert link

- stylesheets/_adaptive-placeholder.scss
[DEVELOPER-4109 - Move the field label for adaptive placeholder text inside the field border](https://issues.jboss.org/browse/DEVELOPER-4109)
The CSS changes are not visible anywhere on the site (yet) but Tiffany reviewed them on a temp page and has approved this PR.
> DEVELOPER-4109 Updated styles for adaptive placeholders

- Gulpfile.js
- javascripts/scroll-to-top.js
- stylesheets/app.scss
[DEVELOPER-4200 - Add "Back to Top" floating link to results](https://issues.jboss.org/browse/DEVELOPER-4200)
Add a scroll to top button to the search page, just like the one used in the Customer Portal [here](https://access.redhat.com/articles/63269)
You can preview it here: http://rhdp-jenkins-slave.lab4.eng.bos.redhat.com:37023/search?q=RHEL
> DEVELOPER-4200 Added "Scroll to top" button

- stylesheets/_javaone.scss
Some tables were just added to the content of /events/javaone/2017. This CSS fixes the table's widths.
> DEVELOPER-4243 JavaOne 2017 - Fixes width of tables

- stylesheets/_javaone.scss
This minor fix makes the tables in [this page](https://developers-pr.stage.redhat.com/pr/2036/export/events/javaone/2017/) be full width.
> DEVELOPER-4243 JavaOne 2017 Fixes width of tables

- _cucumber/features/help/forums/DEVELOPER-3057_forums.feature
Given content could change due to drupal it makes no sense to hard-code any text/product name etc. Ruby Based tests will be redundant soon, too.
> Remove hard coded product names from tests. 

- _tests/e2e/features/search/search.feature
- _tests/e2e/features/step_definitions/search_steps.js
- _tests/e2e/support/pages/search.page.js
- javascripts/build.js
- stylesheets/_searchapp.scss
- typescript/rhdp-search/rhdp-search-results.ts
[DEVELOPER-4216 - Notification for end of results](https://issues.jboss.org/browse/DEVELOPER-4216)
**Requirements**
As a user, I should be able to see some sort of notification when I reach the end of the results. Currently, the LOAD MORE disappears which should still occur in addition to the notification message.
**Review Process**
1. Go to: /search/?q=faq
2. Filter by CONTENT TYPE of "Article" - You should see about 12 as the results found number
3. Click LOAD MORE
4. Verify a notification message displays at the end of the results to indicate there are no more results.
> DEVELOPER-4216 Search - Added notification for end of results

- _tests/unit/rhdp-tryitnow_spec.js
- javascripts/build.js
- stylesheets/_products.scss
- typescript/rhdp-tryitnow.ts
This is a PR to work off of for the try it now feature.
https://issues.jboss.org/browse/DEVELOPER-4432
Test see what it looks like, I've been running this in the chrome console:
sel = document.querySelector('#block-rhd-content > article > section.product-graphics.application-development');
sel.removeChild(sel.firstElementChild);
var title = "Try EAP 7 right now in the cloud.
No download, installation or configuration needed.",
subtitle = "Within seconds, you could be using a browser based IDE to evaluate EAP 7.",
buttonID = "test button id",
buttonText = "Launch EAP 7 Now",
buttonLink = "http://www.google.com",
icon = "https://static.jboss.org/rhd/images/icons/rocket.png";
wc = document.createElement('rhdp-tryitnow');
wc.title = title;
wc.subtitle = subtitle;
wc.buttonID = buttonID; …
> DEVELOPER-4432 - Create 'Try it now' feature for EAP Kitchensink quickstart

- stylesheets/app.scss
Added PDF icon to be automatically displayed after any PDF links that have the .pdf extension. [Example screenshot](https://www.dropbox.com/s/2zydvni8n4zdclo/Screenshot%202017-10-10%2010.34.15.png?dl=0)
For any PDF links that do not have the .pdf extension, I added the css class ".pdf" that can be manually added to the anchor tag to display the PDF icon.
> DEVELOPER-3793 Added PDF icon to PDF links

- stylesheets/_adaptive-placeholder.scss
[DEVELOPER-4441 Odd text overlap in password field in Chrome browser](https://issues.jboss.org/browse/DEVELOPER-4441)
Fixes spacing between input and labels in adaptive placeholders. Libor has tested this CSS fix and says it works as it should, but needed it added to our app.css stylesheet.
> DEVELOPER-4441 Style fix for adaptive placeholders

- Gulpfile.js
- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/promotion-page/node--promotion-page.html.twig
- _layouts/ticket-monster.html.slim
- javascripts/pdf-links.js
- stylesheets/app.scss
- JS to open all links with .pdf extension in new tab
- Added CSS to prevent pdf icon from displaying if pdf link has img child,
- Added CSS to prevent pdf icon from displaying if pdf link is a heavy or medium CTA
> DEVELOPER-3793 Updates hyperlink behavior in "Link to PDF"

- Gulpfile.js
Opening all links with extension '.pdf' in a new tab broke downloads for pdfs in DM. This PR disables the script that was forcing the new tab. 
New pr coming soon with an exclusion to DM links within pdf-links.js
> [URGENT] DEVELOPER-4477 Disabled pdf-links.js

- Gulpfile.js
- javascripts/pdf-links.js
[DEVELOPER-4477 - "Bad Request" when attempting to download PDFs from the download manager](https://issues.jboss.org/browse/DEVELOPER-4477)
The script pdf-links.js should force all PDF links, except Download Manager links, to open in a new tab.
This PR excludes DM links to prevent the download flow from breaking.
> [HOLD] DEVELOPER-4477 Excludes DM links in pdf-links.js

- javascripts/pdf-links.js
Script is broken in Firefox because of missing bracket.
> [URGENT] - Add missing bracket

- _docker/drupal/drupal-filesystem/web/config/sync/views.view.books_rest_export.yml
https://issues.jboss.org/browse/DEVELOPER-3915
To review: 
* Add a "Related product" to a book and save (make sure book is published).
* Navigate to <base_pr_url>/drupal/books and notice that the related product should now be displayed in string format.
There is a separate pull request on DCP (https://github.com/searchisko/configuration/pull/102) that will pull the product in and display it as "sys_project" in search queries.
> DEVELOPER-3915 - Add to books REST API product definition

- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.promotion_page.default.yml
This had been removed in a previous commit. Added it back so that we can exclude promotion pages from DCP indexing.
> DEVELOPER-4410 - Added promotions exclude checkbox back to the config

- _docker/lib/export/export_html_post_processor.rb
- _docker/tests/export/test_export_form_rewrite/index/index.html
- _docker/tests/export/test_export_html_post_processor.rb
The export process adds `/index.html` to access.redhat.com documentation links if the URL does not end with `/index.html`. Unfortunately this logic was being applied if the link ended with a `.pdf` or `.epub` resource as well.
This PR ensures that `.pdf` and `.epub` linked resources remain untouched by the export process.
**For reviewers:**
Ensure that all epub and pdf documentation links on the `/products/devstudio/docs-and-apis` page of the export do not have a `/index.html` suffix.
> [DEVELOPER-4515] Ensure export does not re-write .pdf and .epub documentation links

- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.cheat_sheet.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.cheat_sheet.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.cheat_sheet.field_exclude_from_search.yml
- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/node--cheat-sheet.html.twig
https://issues.jboss.org/browse/DEVELOPER-4410
To Test: Visit /admin/content?title=git+cheat+sheet&type=All&langcode=All&moderation_state= and edit the Git Cheatsheet.
* Check the box for "Exclude from search" at the bottom.
* Visit the page and notice that: 
```javascript
<noscript>
&lt;meta name="DCP:WebpageSearchExclude" content="true"&gt;
</noscript> 
```
Will appear in the body.
This will force DCP to skip the "WEBPAGE" indexing.
> DEVELOPER-4410 - Cheat sheets showing up as both WEBPAGE and CHEAT SHEET in results

- _docker/lib/export/static/rhdp-apps/downloads/products.json
- _tests/unit/rhdp-downloads/rhdp-downloads-all-item_spec.js
- _tests/unit/rhdp-downloads/rhdp-downloads-all_spec.js
- _tests/unit/rhdp-downloads/rhdp-downloads-app_spec.js
- _tests/unit/rhdp-downloads/rhdp-downloads-popular-product_spec.js
- _tests/unit/rhdp-downloads/rhdp-downloads-popular-products_spec.js
- _tests/unit/rhdp-downloads/rhdp-downloads-products_spec.js
- javascripts/build.js
- stylesheets/_downloads.scss
- typescript/rhdp-downloads/rhdp-downloads-all-item.ts
- typescript/rhdp-downloads/rhdp-downloads-all.ts
- typescript/rhdp-downloads/rhdp-downloads-app.ts
- typescript/rhdp-downloads/rhdp-downloads-popular-product.ts
- typescript/rhdp-downloads/rhdp-downloads-popular-products.ts
- typescript/rhdp-downloads/rhdp-downloads-products.ts
- typescript/rhdp-downloads/rhdp-downloads.ts
https://issues.jboss.org/browse/DEVELOPER-3587
Currently, we have the download button show "fetching" while it is iterating through the api products and fetching them one by one. With the new download functionality, there is no need for that since it does a one-time bulk fetch.
Some thoughts though:
1.) What do we want displayed when download-manager is down? I know that we have an alert that shows outages; however, if nothing is displayed, it will just show "Popular Downloads" and "All Downloads"
2.) Once this does get merged in, will the products.json be exported similar to onebox.json?
> DEVELOPER-3587 - Improve the performance of /downloads

- _tests/unit/rhdp-os-download_spec.js
- javascripts/build.js
- javascripts/downloads.js
- javascripts/drupal-namespace.js
- typescript/rhdp-os-download.ts
https://issues.jboss.org/browse/DEVELOPER-4415
To test: Visit the download page of each of the products and confirm that they still refer to the correct download.
Special cases:
DevSuite and CDK should now detect the platform that you are running (RHEL, MacOS or Windows). These should point to the downloads listed on https://docs.google.com/document/d/1m1WljXUSM8EonxaFKtDTmysxrWUnssH1PiShKZ6Mz1o/edit?ts=59c0d31b#
The e2e test failures are unrelated to this component
> DEVELOPER-4415 - Add support for OS detection for the pervasive red DOWNLOAD buttons

- _tests/blc/config/pr_blinkr.yaml
- _tests/blc/config/prod_blinkr.yaml
- _tests/blc/config/stage_blinkr.yaml
We do not own those pages, therefore cannot fix broken links.  Also reduced phantomjs threads in an attempt to reduce random build timeouts.
> Blinkr: Ignore quickstarts

- _tests/unit/rhdp-search/rhdp-search-result_spec.js
- javascripts/build.js
- typescript/rhdp-search/rhdp-search-result.ts
[DEVELOPER-4504 - UI issues with books when displayed in search results](https://issues.jboss.org/browse/DEVELOPER-4504)
Some of the search results for books were showing a longer description because the sys_description coming from the DCP contained multiple HTML tags such as p, ul, li.
In this PR, i've stripped all HTML tags from the search result's descriptions so they are all displayed in the same way.
I've also removed two unit tests that used check that the displayed description was exactly like the description coming from the DCP (they are no longer the same since HTML tags are removed).
> DEVELOPER-4504 Fixes display for 'book' search results

- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/system/html.html.twig
- _tests/e2e/features/website/rhd_navigationMenu.feature
- _tests/e2e/features/website/rhd_topics_white_cards.feature
[DEVELOPER-4530 - Change Security topic name on Topics pulldown](https://issues.jboss.org/browse/DEVELOPER-4530)
To review:
- In the Topics pulldown, "Security" should be changed to "Secure Programming".
> DEVELOPER-4530 Changed Security topic name on main nav

- Gulpfile.js
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.video_resource.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.article.teaser.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.books.teaser.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.cheat_sheet.teaser.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.video_resource.teaser.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.video_resource.field_related_content.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.video_resource.field_slideshare_source.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.video_resource.field_video_related_links.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.video_resource.field_video_transcript.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_related_content.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_slideshare_source.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_video_related_links.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_video_transcript.yml
- _docker/drupal/drupal-filesystem/web/config/sync/pathauto.pattern.coding_resource.yml
- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/rhd_common.module
- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/rhd_common.video.inc
- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/node--article--teaser.html.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/node--books--teaser.html.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/node--cheat-sheet--teaser.html.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/node--product--teaser.html.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/video/field--node--field-related-content.html.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/video/field--node--field-related-video.html.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/video/node--video-resource--teaser.html.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/video/node--video-resource.html.twig
- javascripts/related-content.js
- javascripts/show-more.js
- stylesheets/_videos.scss
- stylesheets/app.scss
**Wireframe for reference:** https://redhat.invisionapp.com/share/RMD3XZQX8#/screens
The most important changes to the Video Resource content type in this PR:
- Added field_related_content
- Added field_slideshare_source
- Added field_video_related_links
- Added field_video_transcript
Since field_related_content is an entity reference for books, articles, videos, and cheat sheets, I added twig teaser templates for those content types.
The related-content.js script fills out any spaces in the 'More Like This' section with content from the DCP, pulled using the video_resource_tags.
The show-more.js script is only for the functionality of 'Show More/Less' when the video description is displayed.
>  [DO NOT MERGE] DEVELOPER-3890 Improved video pages

- javascripts/footer.js
https://issues.jboss.org/browse/DEVELOPER-4508
Footer links should no longer expand or collapse when the window is over 1170 pixels wide.
> DEVELOPER-4508 - Links in footer disappear after being clicked

- _docker/drupal/drupal-filesystem/2174633-174.patch
- _docker/drupal/drupal-filesystem/composer.json
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.video_resource.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.video_resource.field_related_content.yml
- _docker/drupal/drupal-filesystem/web/config/sync/views.view.entity_type_view.yml
To test: https://issues.jboss.org/browse/DEVELOPER-4553
You should be able to replicate this image
> DEVELOPER-4553 - Display Content Type in Entity Reference Autocomplete

- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/templates/product-pages.html.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/node--books.html.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/node--cheat-sheet.html.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/promotion-page/node--promotion-page.html.twig
- javascripts/build.js
- typescript/rhdp-downloads/rhdp-downloads-app.ts
- typescript/rhdp-search/rhdp-search-zapp.ts
https://issues.jboss.org/browse/DEVELOPER-4424
Appropriate pages should have their respective placeholder.
* Download (span w/ class dl-outage-msg)
* /downloads/
* /products/*/download/
* /cheat-sheets/*/
* /books/*
* Search (span w/ class search-outage-msg)
* /(homepage latest content)
* /search/
* /products/*/help/
* /stack-overflow/
* /projects/
* /events/
> DEVELOPER-4424 - Create messaging placeholders

- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/paragraph/paragraph--get-started.html.twig
Christina Lin wants to use katacoda for some of their stuff in Fuse.
We needed to add the script for katacoda.
I tried a couple of approaches, but this was the easiest and probably least invasive way of doing it.
We end up downloading an extra script file that at worst we won't need, but that doesn't seem to be that bad.
JIRA: https://issues.jboss.org/browse/DEVELOPER-4573
Testing:
Update a product Hello World page to include the following code (I tested in the additional section so you don't have to wade through tabs):
<div id="my-element-1"
data-katacoda-env="node"
data-katacoda-layout="editor-terminal"
data-katacoda-port="3000"
data-katacoda-filename="app.js" style="border: 2px solid #ccc;" >
var http = require('http');
var requestListener = function (req, res) {
res.writeHead(200); …
> DEVELOPER-4573 Adding katacoda

- stylesheets/_middleware.scss
[DEVELOPER-4385 - Bugs and issues for the /middleware page](https://issues.jboss.org/browse/DEVELOPER-4385)
1. Changes the background color for the green section in /middleware for a green that passes Web contrast/accessibility standards.
2. Fixes issue where footer in /middleware page was getting some extra padding. Footer should now look the same as in the other pages
> DEVELOPER-4385 Style fix for Middleware page

- javascripts/drupal-namespace.js
https://issues.jboss.org/browse/DEVELOPER-4599
The tag was updated to rhmap. This will still not return any results in staging since the below dcp call returns no results.
http://dcp.stage.jboss.org/v2/rest/search/stackoverflow/?field=sys_url_view&field=sys_title&field=is_answered&field=author&field=sys_tags&field=answers&field=sys_created&field=view_count&field=answer_count&field=down_vote_count&field=up_vote_count&field=sys_content&from=0&product=rhmap&project=&query=&query_highlight=true&size=10&size10=true&tag=rhmap
However, it will return results in production. The production DCP has results for the new tag:
https://dcp2.jboss.org/v2/rest/search/stackoverflow/?field=sys_url_view&field=sys_title&field=is_answered&field=author&field=sys_tags&field=answers&field=sys_created&field=view_co …
> DEVELOPER-4599 - This page is missing Red Hat Mobile Application Platform

- javascripts/downloads.js
https://issues.jboss.org/browse/DEVELOPER-4609
Adds additional logic to test the download manager service response to make sure an empty table isn't created.
> DEVELOPER-4609 - .NET Core download page incorrect

- _docker/environments/drupal-production/docker-compose.yml
This PR ensures that the production Drupal instance loads the `rhd.settings.php` file rather than `rhd.settings-lightning.php`. I assume the latter was created as part of the migration to the lightning profile, but as we're now running on completely new hardware, it is not required.
The `rhd.settings.php` already exists on the production host and has the exact same content as the `rhd.settings-lightning.php`:
```
[root@developer-rhdp-drupal drupal]# pwd
/credentials/drupal
[developer-rhdp-drupal.web.prod.ext.phx2.redhat.com] [12:46:07 PM]
[root@developer-rhdp-drupal drupal]# ls
rhd.settings-lightning.php  rhd.settings.php  rhd.settings.yml
[developer-rhdp-drupal.web.prod.ext.phx2.redhat.com] [12:46:08 PM]
[root@developer-rhdp-drupal drupal]# diff rhd.settings.php …
```
> [DEVELOPER-4647] Ensure prod Drupal uses puppet managed configuration file

- _docker/drupal/drupal-filesystem/web/config/sync/views.view.cheat_sheets_rest_export.yml
https://issues.jboss.org/browse/DEVELOPER-4610
You can review this by visiting /drupal/cheat-sheets. Pagination limited the results to 10. I switched the setting so it now returns all cheatsheets for the indexer.
> DEVELOPER-4610 - Updated REST export query for DCP indexing

- javascripts/drupal-namespace.js
- typescript/rhdp-downloads/rhdp-downloads-all-item.ts
This fixes the issue with the downloads pages on https://github.com/redhat-developer/developers.redhat.com/pull/2180
> DEVELOPER-4640 - Fix DevSuite file versions to latest 2.2.0

- stylesheets/_home.scss
When the homepage was migrated to Drupal there were some overwriting of CSS classes that stopped happening, causing the homepage to have margins all around in mobile, and a bottom padding in desktop.
This is a temporary fix. We will address the bigger issue with the redesign of the site.
> [URGENT] Homepage margin fixes

- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/system/html.html.twig
- _tests/e2e/features/website/rhd_navigationMenu.feature
[DEVELOPER-3932](https://issues.jboss.org/browse/DEVELOPER-3932)
Removes the Resources page from the main nav, and from the navigation e2e tests.
_Part 1 of a series of PRs to remove the Resources page._
> DEVELOPER-3932 Removed Resources from main nav

- javascripts/build.js
- typescript/rhdp-downloads/rhdp-downloads-products.ts
To review: Visiting http://rhdp-jenkins-slave.lab4.eng.bos.redhat.com:37212/downloads and check to make sure that:
* Red Hat JBoss Web Server points to https://developers.redhat.com/products/webserver/download/
* Red Hat Application Migration Toolkit to link directly to the default download, as this product is now in the download manager.
* Red Hat Mobile Application Platform to link to https://developers.redhat.com/products/mobileplatform/download/ (Check most popular as well).
> DEVELOPER-4472 - Direct Links to Customer Portal on https://developers.redhat.com/downloads/

- javascripts/middleware-blog.js
- stack-overflow.html.slim
/StackOverflow was still an Awestruct page. I added the as_is_html to fix that.
I also removed a random console.log that was mistakenly left behind in a js script.
>  Added as_is_html tag to StackOverflow page

- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/rhd.theme
- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/templates/system/html.html.twig
- stylesheets/_middleware.scss
Fixed issue where the page's path wasn't being added to the body tag of all pages. This will fix any issues where we need the path as a CSS class, such as the /middleware page to have page-specific CSS.
> Fixes styles for middleware page

- stylesheets/_stackoverflow.scss
[DEVELOPER-3689
Stack Overflow questions/answers view contains html entities](https://issues.jboss.org/browse/DEVELOPER-3689)
These are just style fixes. The fix required in the Jira is directly on the html on the page, in Drupal.
> DEVELOPER-3689 Fixes for StackOverflow page

- _docker/drupal/drupal-filesystem/web/config/sync/views.view.events_rest_query.yml
https://issues.jboss.org/browse/DEVELOPER-4751 - This allows /drupal/events to display a JSON from the REST View
> DEVELOPER-4751 - Events JSON export

- _docker/lib/drupal-data/lite/drupal_data_lite_image_builder.rb
I think this gets us a smaller data lite
The tests still pass without having to change anything which makes me
worried, but testing this locally, it made a smaller container.
With a smaller data-lite container it saves ~7 minutes during a build or dev restart.
> Slim data-lite container, again

- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/rhd_assemblies.routing.yml
- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/rhd_assemblies.services.yml
- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Controller/WppostAutocompleteController.php
- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Plugin/AssemblyBuild/BlogPostsBuild.php
- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Plugin/Field/FieldFormatter/WppostTeaserFormatter.php
- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Plugin/Field/FieldType/ListWpcategoriesItem.php
- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Plugin/Field/FieldType/WppostItem.php
- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Plugin/Field/FieldWidget/WppostAutocompleteWidget.php
- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Service/RemoteContentApiInterface.php
- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Service/WordpressApi.php
- Refactors existing wordpress API calls into a service.
- Adds several methods to that service to facilitate display/querying of wordpress content
- Adds a field type, widget, and formatter for a single wordpress post
> JIRA 4796 - Wordpress post entity reference

- _tests/e2e/features/step_definitions/hooks.js
- _tests/e2e/features/support/pages/keycloak/Login.page.js
- _tests/e2e/features/support/pages/keycloak/Register.page.js
Minor changes to fix intermittent failures on PR's. 
- Upped the wait time for login/register pages.
- Added try/catch to after hooks. Noticed on @KamiQuasi 's PR the after hook timed out with `function timed out after 60000 milliseconds`. Catching the after hook with console output as we don't want the test to fail after it is already complete.
> Fix for intermittent failures on PR's.

- _docker/drupal/drupal-filesystem/web/config/sync/core.extension.yml
- _docker/drupal/drupal-filesystem/web/themes/custom/rhd/rhd.theme
Fences needs to be enabled for a lot of the frontend work we're doing with the new theme, but we don't want it to have any effect on the current them. Fences works by altering the theme registry and inserting its own path the field templates - this simply forces the path to be that of the Classy theme (what RHD inherits from)
> fences shouldn't do anything when rhd is the active theme

- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/rhd_common.form_validations.inc
To test: Create a new event with dates included. This should no longer bug out.
Also, make sure that form error is thrown when end date is before start date.
> [URGENT] EventsValidationFix - Fixed date comparison bug

- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Plugin/Field/FieldWidget/WppostAutocompleteWidget.php
- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Service/WordpressApi.php
This uses the new title search wordpress endpoint to improve functionality of the wordpress post autocomplete from JIRA 4796. Also fixes a bug which would prevent content without featured media from rendering properly.
> use new title search endpoint for wordpress post matching

- _docker/drupal/drupal-filesystem/web/config/sync/core.base_field_override.node.topic_page.promote.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.topic_page.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.topic_page.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.topic_page.teaser.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.topic_page.field_sections.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.topic_page.scheduled_update.yml
- _docker/drupal/drupal-filesystem/web/config/sync/node.type.topic_page.yml
- _docker/drupal/drupal-filesystem/web/config/sync/simple_sitemap.bundle_settings.node.topic_page.yml
There might need to be a followup issue on this - I can't add assembly types to the sections field that are currently pending pull requests. Any future tasks to create an assembly type should consider it part of that task to add the assembly type to the sections field for Landing Pages and Topic Pages.
> DEVELOPER-4805: new Topic Page node type

- _docker/drupal/drupal-filesystem/web/config/sync/block.block.rhdp_page_title.yml
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhdp.theme
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/node/node--assembly-page.html.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/system/page.html.twig
The title is now displayed. If the page alias is "harmonize/home", the title will be omitted.
> DEVELOPER-4915 Fix title display in RHDP theme

- _tests/e2e/config/wdio.conf.base.js
- _tests/e2e/specs/rhd-cheatsheet-downloads.js
- _tests/e2e/specs/rhd-home.spec.js
- _tests/e2e/specs/rhd-navigation-spec.js
- _tests/e2e/specs/rhd-search.spec.js
Mocha-tags are not honoured when running production smoke checks.
> mocha-tags are not honoured when running production smoke checks.

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/rhd.scss
[DEVELOPER-5089 - CSS style for Code snippets within body text is missing or being overwritten	
](https://issues.jboss.org/browse/DEVELOPER-5089)
> DEVELOPER-5089 Pre and Code tags style fix

- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/rhd_common.module
Also removing a TODO comment that is done
JIRA: https://issues.jboss.org/browse/DEVELOPER-4078
Testing:
* Create a new video resource instance
* Paste in the YouTube link
* Wait for the AJAX call to finish
* Verify the URL alias is /videos instead of /video
> [HOLD] DEVELOPER-4078 Fix the auto-generated URL

- .gitignore
- _tests/e2e/specs/rhd-blog.spec.js
- _tests/e2e/specs/support/pages/website/Blog.page.js
Adding sanity check for the blog page. Test verifies that the page source contains the binary string for RHD.
> Sanity check for blog page

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_navigation.scss
When vieweing this page https://developers.redhat.com/events/ you can see the correct format in Chrome and the incorrect format in Firefox.
> Developer-5095 Add fixed height for a tag in rhd nav

- _docker/drupal/drupal-filesystem/web/config/sync/views.view.events_rest_query.yml
* https://issues.jboss.org/browse/DEVELOPER-5210
This is part 1 of the fix.
* Notice that all events should be displayed on /drupal/events instead of just the first 10.
* Upon merge, DCP changes will be submitted to staging. From there, the links returned from search should link to the actual event page instead of the 404 page generated from the event node id.
> DEVELOPER-5210 - Fix broken links for Events on Search

- _docker/lib/export/export_html_post_processor.rb
- _docker/tests/export/test_export_html_post_processor.rb
* https://issues.jboss.org/browse/DEVELOPER-5103
Look at the export, make sure the og:image doesn't include a reference which has a query string in it.
> DEVELOPER-5103 drop query string from url

- _docker/drupal/drupal-filesystem/web/config/sync/views.view.books_rest_export.yml
Currently, we're using the raw output, this needs to change
N/A
Look at the books view and verify the description has rendered HTML instead of the Drupal code.
> Updating the description on book export

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/js/drupal-namespace.js
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/rhdp-os-download.ts
* https://issues.jboss.org/browse/DEVELOPER-5244
* Visit - https://developers.redhat.com/products/cdk/download/ and verify that the button version is 3.5.0-1 on Mac, Linux, and Windows
> Updating CDK version to 3.5.0-1

- _docker/drupal/apache/drupal.conf
I had tried to do this at the Drupal level, but that didn't really work
well, so I'm removing it at the apache level.
* https://issues.jboss.org/browse/DEVELOPER-5243
* Log into the Drupal instance
* Open dev tools
* Navigate to a new web page on the site
* Look at the response headers in the Network tab of the dev tools
* Verify the following headers are not present:
** link
** x-drupal-cache
** x-drupal-dynamic-cache
** x-generator
** x-powered-by
** x-ua-compatible
Probably a good idea to do this as a logged in user and also as an anonymous user
> DEVELOPER-5243 Removing the headers via apache

- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.books.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.cheat_sheet.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.product.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.topic_page.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.video_resource.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.books.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.cheat_sheet.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.product.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.video_resource.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.books.field_share_image.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.cheat_sheet.field_share_image.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.product.field_share_image.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.video_resource.field_meta_tags.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.video_resource.field_share_image.yml
* [DEVELOPER-5158 Add the Share Image field to additional content types](https://issues.jboss.org/browse/DEVELOPER-5158)
- Go to each of the content types (Books, Cheat Sheets, Products, Videos) and verify the field to add a 'Share Image" is available.
- Verify that you can also reference that field in the Open Graph > Image section in the Meta Tags area. ([node:field_share_image:share:url])
> DEVELOPER-5158 Added the Share Image field to additional content types

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_content_with_image.scss
Update assembly content_with_images mobile styles to push image above content and center image and content. Add button margins.
https://issues.jboss.org/browse/DEVELOPER-5238
1. Visit: /topics/linux/ OR create a new "Rich Text with Image" assembly on any page
2. Resize browser to 768px and lower
3. Observe that image now slides above the content and all content is centered
**Desktop**
**Tablet**
**Mobile**
**XS Mobile**
> [DEVELOPER-5238] Update content_with_images assembly mobile styles

- _docker/lib/export/export_html_post_processor.rb
- _docker/tests/export/test_export_html_post_processor.rb
Fixes are no longer required
* https://issues.jboss.org/browse/DEVELOPER-5268
* Navigate to RHAMT Docs & API page, verify the "Red Hat Customer Portal" link does not 404
> DEVELOPER-5268 Remove access.redhat.com fixes

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/system/page.html.twig
Removing the title display on the home page.
* https://issues.jboss.org/browse/DEVELOPER-5310
Look at the home page, verify the title is no longer showing.
> DEVELOPER-5310 Title is displayed on home page

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/js/pdf-links.js
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_downloads.scss
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_get-started.scss
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_microsite.scss
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_rhd.scss
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_videos.scss
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/patterns/_buttons.scss
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/typography/_anchor.scss
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/tsconfig.json
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/paragraph/paragraph--help.html.twig
[DEVELOPER-5190 Styling issues on Product pages](https://issues.jboss.org/browse/DEVELOPER-5190)
Review that the style issues listed are not happening anymore (see jira for screenshots):
- Small columns such as Release Date on downloads table shouldn't wrap into two lines (https://developers-pr.stage.redhat.com/pr/2581/export/products/amq/download/)
- Blue boxes should have equal height (https://developers-pr.stage.redhat.com/pr/2581/export/products/amq/hello-world/)
- PDF icon in the 'View As' dropdowns are not showing up (https://developers-pr.stage.redhat.com/pr/2581/export/products/amq/docs-and-apis/)
- "Red Hat Support and Professional Services" icons should have equal height to make the content look even (https://developers-pr.stage.redhat.com/pr/2581/export/products/amq/help/)
- …
> DEVELOPER-5190 Styling issues on Product pages

- _docker/lib/export/export_html_post_processor.rb
- _docker/tests/export/test_export_form_rewrite/drupal-host-leak/index.html
Adding another step where we modify links in the export. Test included.
* https://issues.jboss.org/browse/DEVELOPER-5337
* Go to the home page of the export
* Look for the KubeBoot video about half way down the page
* Inspect the element in dev tools
* Verify the data-disqus-thread-link attribute points to the correct location instead of Drupal
> DEVELOPER-5337 Modifying export disqus links

- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.video_resource.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.video_resource.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.video_resource.field_exclude_from_search.yml
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/coding-resource/node--coding-resource.html.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/video-resource/node--video-resource.html.twig
* [DEVELOPER-5306 - DevNation sessions missing from search engine.](https://issues.jboss.org/browse/DEVELOPER-5306)
- Go to edit one of the video pages on Drupal
- Check the option to 'Exclude from search'
- Preview the page, and look at the source
- this meta tag should be present: `<meta name="DCP:WebpageSearchExclude" content="true">`
- go back to edit the page, and uncheck 'Exclude from search'
- save the page and look at the source code, the meta tag should no longer be there.
Once this is merged and the DCP re-indexes the video pages, all pages that have 'Exclude from search' unchecked should appear on the search results
> DEVELOPER-5306 - Fixes missing videos in search

- .gitignore
- _docker/control.rb
- _docker/lib/rhd_environment.rb
- _docker/tests/test_control.rb
- _docker/tests/test_rhd_environment.rb
Something has changed in the staging and production environments that means `control.rb` is now returning bad DNS lookups for the host on which Drupal is exposed. This is causing the Drupal boot management sequence to fail as the scripts believe that Drupal is not running.
* [DEVELOPER-5369](https://issues.jboss.org/browse/DEVELOPER-5369)
The PR build process should work smoothly. Check the output of the PR build to verify that the control.rb script is checking that the Drupal instance is up on host `rhdp-jenkins-slave.lab4.eng.bos.redhat.com`
> [DEVELOPER-5369] Avoid bad DNS lookups for control.rb

- _docker/control.rb
- _docker/lib/export/export.rb
- _docker/lib/export/export_diff.rb
- _docker/tests/export/test_export.rb
- _docker/tests/export/test_export_diff.rb
- _docker/tests/export/test_export_diff/sitemap-1.xml
- _docker/tests/export/test_export_diff/sitemap-2.xml
This PR adds the ability for the export process to determine which page content has changed between runs. It does this by inspecting the current `sitemap.xml` and comparing the `<lastmod>` entry for each page against that from the previous export.
It locates the previous export by looking in the export archive directory. Each time an export is successfully rsynced, a copy is made into the archive directory to facilitate easy rollback. This copy contains the previous version of the `sitemap.xml` with previous content modification times.
This PR merely adds the ability to detect which pages have changed, it does not add anything to act on that e.g. clearing the Akamai cache. This will be added in another PR.
Additionally this PR removes an unnecessary call to clear the Drupal cache each …
> [DEVELOPER-5364] Determine changed content between runs of the export

- _docker/environments/drupal-production/docker-compose.yml
- _docker/environments/drupal-staging/docker-compose.yml
Whenever IT perform any maintenance to our staging or production environments that involve either a reboot of the VM or a restart of the Docker daemon, our Drupal instance is not automatically restarted until the deploy job runs in Jenkins. This causes two problems:
1. Anyone wanting to edit content after IT maintenance has to wait until Drupal is re-deployed to do so
2. We set off a lot of Nagios alerts because our Drupal instance remains down after IT maintenance
This PR simply applies a Docker restart policy to the Drupal containers in `stage` and `production` environments. We apply the `unless-stopped` policy which says that the Drupal container will be restarted unless it has been explicitly stopped via `docker stop` or `docker-compose down`.
* …
> [DEVELOPER-5380] Ensure Drupal automatically restarts in staging & production

- _docker/lib/export/export_diff.rb
Somehow a missing `require 'time'` statement in the `export_diff.rb` class has made it through all testing and into production. 
This simply adds the missing `require` statement.
* [DEVELOPER-5414](https://issues.jboss.org/browse/DEVELOPER-5414)
* The export process works as expected.
> [DEVELOPER-5414] Added the missing require 'time' from export_diff.rb

- _docker/environments/drupal-staging/docker-compose.yml
Changed the directory in which the export does local filesystem work to something much more self-explanatory. This is going into `stage` only at this moment in time as a test. No other environments are impacted by this.
* https://issues.jboss.org/browse/DEVELOPER-5390
- The export continues to work as expected in staging.
> [DEVELOPER-5390] Changed directory for local filesystem export work

- _docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.learning_paths.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.article.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.assembly_page.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.author.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.books.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.cheat_sheet.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.coding_resource.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.connectors.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.events.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.learning_path.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.page.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.product.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.promotion_card.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.promotion_page.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.rh_certification_exam.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.rh_training_class.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.rhd_microsite.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.rhd_solution_overview.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.topic.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.topic_page.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.video_resource.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/node.type.learning_path.yml
It looks like the latest version of Drupal changed how the config is exported which seemed to be blockin `drush cim` from importing correctly. These are the configs exported from the `drupal-data-lite` container.
> Export configs from drupal-data-lite container.

- _tests/e2e/config/browsers/BrowserManager.js
- _tests/e2e/config/wdio.conf.base.js
- _tests/e2e/environments/docker-compose.yml
- _tests/e2e/specs/rhd-downloads.spec.js
- _tests/e2e/specs/support/Utils.js
- _tests/e2e/specs/support/pages/Page.js
- _tests/e2e/specs/support/pages/keycloak/Login.page.js
* NO ISSUE
* Just an update to docker-selenium (chrome) and upped timeout for login process as for some reason at times it takes more than 1 minute to log in (when downloading).
* Sometimes the direct logout (via url) doesn't work so added an after hook to to do a regular logout first, and then fallback to do a direct logout.
> [NO ISSUE]: bump docker-selenium version 

- _tests/e2e/config/browsers/BrowserManager.js
- _tests/e2e/specs/support/pages/website/CheatSheets.page.js
* NO ISSUE: Fix for failing sanity checks. Cookie banner is blocking log in to download button.
> Updates for cookie banner blocking log in to download button.

- _docker/awestruct/Dockerfile
- _docker/backup/Dockerfile
- _docker/control.rb
- _docker/drupal/Dockerfile
- _docker/export/Dockerfile
- _docker/ruby/Dockerfile
- _docker/tests/test_control.rb
*Something* has changed which means that installing git via `yum` in our CentOS 6 images no longer works. This is causing the re-build of the Drupal image to fail.
I've therefore updated the Ruby image to install Git and Git LFS from a different source. This is a significant bump to our Git version.
I've made sure to tag the new ruby image as `2.4.0` and updated all dependent Dockerfiles to use the new version.
I've additionally tested that the `backup` container can still successfully `git lfs clone` the backup repo using the new version of Git and Git LFS.
* https://issues.jboss.org/browse/DEVELOPER-5437
* The build should be completely green
* Verify that  Drupal seems to be working as expected
> [DEVELOPER-5437] Fix broken Docker image builds

- README.md
This commit updates the README to include instructions to:
1. Increase Docker for Mac's RAM allocation to 4GB,
2. Add the docker host to your /etc/hosts file to make it available to
the setup script (and generally),
3. Request the Fort Awesome npm config from a co-worker prior
to executing the setup script, and
4. Run the Drupal server with `drush runserver`
> Update README with RAM, IP and Fort Awesome info

- _docker/drupal/drupal-filesystem/composer.json
- _docker/drupal/drupal-filesystem/composer.lock
- _docker/drupal/drupal-filesystem/db-migrations/20181011213825_remove_openapi_redoc_module.php
This eliminates 2 distinct errors that arise currently during the build
process / the execution of setup_local_drupal.sh.
The first is a Drupal core patch that could not apply,
2421001-124.patch. This issue was resolved in Drupal 8.5.x, so this
patch is no longer necessary. I removed it from composer.json. I also
updated our other core patch to a newer version of the patch that had
more user testing reports within the issue queue.
The second error was a 'missing module in filesystem' error for the
openapi_redoc module. To resolve this issue, I created a Phinx DB
migration that deletes that entry from the key_value table. To ensure
that my SQL query would resolve this issue, I locally ran the query via
drush sql-query and re-executed setup_local_drupal.sh, and I did not
observe a warning …
> DEVELOPER-5438: Eliminate Build Errors

- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/rhd_common.form_validations.inc
This change allows a draft to be saved without a value for the PDF Link
field. I also verified that I could submit the form without a value for
the ISBN field.
* https://issues.jboss.org/browse/DEVELOPER-5378
Go here:
Relative URL: `/node/add/books`
Do this:
* Fill out all of the required fields with some data
* Check the RHDP hosted book checkbox field
* Do **not** enter a value for the ISBN or PDF Link fields
* Leave the moderation state "Save as" value as Draft (the default)
* Save and submit the node edit form
* The form should submit successfully without errors and should redirect you to the newly create Book node
Example:
> DEVELOPER-5378: Update Book Node Edit Form

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhdp.theme
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/assembly/assembly--static-item.html.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/events/node--events--tile.html.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/node/node--product--featured-tile.html.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/video-resource/node--video-resource--teaser.html.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/video-resource/node--video-resource--tile.html.twig
In this commit, in the 5 changed template files, we are passing just the
plain-text string to the <img> src or a <href> attribute(s). Previously,
many of these attributes were having entire Node objects passed to them,
which resulted in instances where HTML comments, for example, were being
injected into the src or href attributes. In addition to the 4 entity
type + display modes detailed in DEVELOPER-5255:
* Node, Events, Tile
* Node, Product, Featured Tile
* Node, Video Resource, Teaser
* Node, Video Resource, Tile
I also discovered a similar issue with the Assembly, Static Item entity
type + display mode, so I resolved that in this commit as well.
* https://issues.jboss.org/browse/DEVELOPER-5255
Here is an example of the behavior of this bug prior to my changes. You can see all of the …
> DEVELOPER-5255: Image Style URLs

- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.connectors.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.connectors.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.connectors.field_connector_image.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.storage.node.field_connector_image.yml
- _docker/drupal/drupal-filesystem/web/config/sync/views.view.connectors_rest_export.yml
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/js/connectors.js
This adds a Media (Image) field to the Connector content type to store a
thumbnail to be displayed on the Connectors page. The new field is added
to the Connectors REST Export View, which will be consumed by the DCP.
In turn, the front-end of our application will make an AJAX call to the
DCP and retrieve the relative URL to the image from the DCP endpoint and
serve that on the Connectors Fuse page. In the event that there is not
an image uploaded to a Connector, a fallback image will display from
static.jboss.org.
> [DEVELOPER-5422] Fuse Page Connector Images

- _docker/awestruct/Dockerfile
- _docker/awestruct/mariadb/MariaDB.repo
- _docker/backup/Dockerfile
- _docker/backup/mariadb/MariaDB.repo
The yum.mariadb.org SSL certificate has expired meaning that Docker image builds fail. This update addresses the issue by importing the GPG key from the HTTP url instead.
This PR targets `stage` so that we can test things there before going into prod.
* [DEVELOPER-5478](https://issues.jboss.org/browse/DEVELOPER-5478)
- Build should go green
> [DEVELOPER-5478] Updated yum gpg URL to use HTTP rather than HTTPS

- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.assembly.events_list.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.assembly.featured_products.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.assembly.static_content_band.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.assembly.events_list.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.assembly.featured_products.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.assembly.static_content_band.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.events_list.field_cta_link.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.featured_products.field_cta_link.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.static_content_band.field_cta_link.yml
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_event_list.scss
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_featured_products.scss
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_learning_paths.scss
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_static_content_band.scss
https://issues.jboss.org/browse/DEVELOPER-5461
1. Add/Edit each of the updated assemblies to see new CTA Link field
2. Update CTA Link field and view on front-end.
**Updated Assemblies:**
1. Curated Content (static_content_band)
2. Events List
3. Featured Products
> [DEVELOPER-5461] Add Missing CTA Links to Assemblies

- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/templates/wordpress-post-teaser.html.twig
- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/templates/wordpress-post-tile.html.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhdp.theme
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/events/node--events--teaser.html.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/video-resource/node--video-resource--tile.html.twig
https://issues.jboss.org/browse/DEVELOPER-5462
- Linked images in drupal assemblies have auto generated alt text
NOTE: After auditing assemblies I found the following three were not including alts tags in their images.
> [DEVELOPER-5462] Add alt tags to images in assemblies

- _docker/drupal/drupal-filesystem/web/config/sync/filter.format.rhd_html.yml
This removes an automatically added rel="nofollow" attribute to every
<a> tag created within a WYSIWYG field using the Red Hat Approved text
format.
* https://issues.jboss.org/browse/DEVELOPER-5460
Go here: `/articles/build-run-colossal-cave-adventure-game`
Scroll down to the body of the article and find the link text Colossal Cave Adventure in the 3rd sentence of the article. Right click and Inspect Element on that link.
There is no longer a rel="nofollow" attribute automatically added to every <a> tag in the body field of Articles.
> DEVELOPER-5460: Remove rel nofollow

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_get-started.scss
This makes a very small change to remove some styles that were
unintentionally resulting in a border-bottom being applied to the
active tab in the Hello World! section of product pages.
* https://issues.jboss.org/browse/DEVELOPER-5493
* Go here: `/products/rhamt/hello-world`
* Click on Web Console to make that the active tab within the Hello World! section of this product page
* Observe that there is no gray bottom border on the active tab
> DEVELOPER-5493: Product pages unwanted border

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhdp.theme
This commit generally tidies up the rhdp.theme file. It applies Drupal
coding standards to almost the entire file, with a few exceptions for
line width. It applies a 2-space indentation to the entire file. It
reorganizes a few portions of the preprocessors to improve readability.
I have also discovered an issue in rhdp_preprocess_views_view() that
will throw an undefined variable error upon any execution of this hook.
I have noted that in the appropriate place in the file. We should
resolve that within the PR containing this commit if possible.
* n/a
* Nearly the entire .theme file should now conform to the Drupal coding standards
* The functionality provided by these preprocessors, and any additional functions, within the .theme file should remain exactly the same
> Clean up rhdp.theme file

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhdp.theme
This removes some typehinting that I added earlier to the www_ddo helper
function in rhdp.theme. Apparently, sometimes NULL can also be passed
into this function. This seems inadvertent, but it will throw an error.
* n/a
After visiting the homepage, you should not observe a typehint error for the www_ddo helper function in the Drupal watchdog logs `drush ws` or `/admin/reports/dblog`.
> Removes the typehinting from www_ddo function

- _tests/blc/dcp/Gemfile.lock
* No issue, just a version bump to dcp-checker, now ignoring `jbossdeveloper_archetype` and `jbossdeveloper_bom`. 
* Nothing to review.
> version bump for dcp-checker

- _docker/drupal/apache/drupal.conf
This PR remove the redirects within the Drupal VirtualHost configuration that were added for DCP integration. These are now implemented directly at the DCP itself.
* https://issues.jboss.org/browse/RHDENG-2643
* The build should be green
> [RHDENG-2643] Removed redirects for DCP integration

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_topic-page.scss
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/rhd.scss
This removes a background style that was being applied to the masthead
and layout containers on Topic Pages. @tiffanynolan  requested we remove
the style.
@tiffanynolan Please approve this change when the PR environment is available
* n/a
Go here: `/topics/linux`
You should not see this white background around the `div.layout-container` element
> Remove Topics Page background style

- _docker/environments/drupal-dev-local-dcp/docker-compose.yml
- _docker/environments/drupal-dev-local-dcp/rhd.settings.yml
- _docker/environments/drupal-dev/docker-compose.yml
- _docker/environments/drupal-dev/rhd.settings.php
- _docker/environments/drupal-dev/rhd.settings.yml
- _docker/environments/drupal-pull-request/docker-compose.yml
- _docker/environments/drupal-pull-request/rhd.settings.php
- _docker/environments/drupal-pull-request/rhd.settings.yml.erb
- setup_local_drupal.sh
The outage this morning was caused by a DB migration accidentally targeting the wrong DB name. This worked in `dev` and `pr` environments because the database was named correctly for the migration. However once it got to `prod` the migration failed because the DB there has a different name.
This PR ensures that all environments use a consistent DB name so that any migrations not targeting the correct database should fail in PR environment
* https://issues.jboss.org/browse/DEVELOPER-5550
* This build should go completely green
* Access the Drupal interface and see that it's connected to the `rhd_mysql` database
> [DEVELOPER-5550] Consistent DB names in Dev and PR environments

- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.article.field_content.yml
This removes the Product Features assembly type as an option from the
Content entity reference revisions field on the Articles content type.
Gina has requested we removed this assembly type as an option on this
content type until we implement some changes to the styling of the
Product Features component that will allow it to be displayed more
functionality in situations with less width.
* https://issues.jboss.org/browse/DEVELOPER-5576
* The Product Features assembly type is not available from the assembly reference field on Article nodes
> Remove Product Features assembly from Articles

- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.product.field_content.yml
This adds the CTA assembly type as a reference-able assembly from the
Content field on the Product content type.
* https://issues.jboss.org/browse/DEVELOPER-5595
* An editor can now reference CTA assemblies from the Content field on Product nodes
> [DEVELOPER-5595] Adds CTA to Content field on Product nodes

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_articles.scss
https://issues.jboss.org/browse/DEVELOPER-5590
for the new article pages the author name should now be #0066CC if it is a link to a profile otherwise it should be #424242.
an example of this page is here /articles/build-run-colossal-cave-adventure-game/
> [DEVELOPER-5590] Make author name blue if a link otherwise grey

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhdp.theme
This commit adds a typechecking to the $node variables, ensuring it is
the Node class before operating on it, within the page preprocessor in
rhdp.theme. Prior to this commit, this lack of typechecking resulted in
a fatal error that made it impossible to view entity revisions.
* https://issues.jboss.org/browse/DEVELOPER-5614
* If you visit any node Revisions page (ex. /finservices/openbanking/revisions), you should be able to successfully click on one of the timestamps (ex. 01/04/2019 - 07:44) to successfully view the revision
> [DEVELOPER-5614] Adds typechecking to page preprocessing

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhdp.theme
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/learning-path/field--node--field-learning-path-content-item.html.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/learning-path/node--books--learning-path-card.html.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/learning-path/node--cheat-sheet--learning-path-card.html.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/learning-path/node--rh-training-class--learning-path-card.html.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/learning-path/node--video-resource--learning-path-card.html.twig
This resolves some invalid render array errors with the Learning Paths
pages (/learn/*). The 'interval' and 'period' array keys were not truly
render array keys as we were attempting to use them in Twig, so I made
some additions to the node preprocessor to make the interval available
to the templates via PHP.
* https://issues.jboss.org/browse/DEVELOPER-5626
Go here: `/learn/microservices`
Then, go here: `/admin/reports/dblog` and you should see no errors in the log like this:
`User error: "period" is an invalid render array key in...`
or
`User error: "interval" is an invalid render array key in...`
> DEVELOPER-5626: Learning Paths Invalid Render Array

- _docker/drupal/drupal-filesystem/composer.json
- _docker/drupal/drupal-filesystem/composer.lock
This PR updates the `imagecache_external` module to a fixed `dev` version in order to resolve an issue with it throwing an Exception if it failed to fetch an image from a remote source.
I've had to use a `dev` version of the library as I cannot get the patches that people have submitted to apply cleanly to the `1.0` release and it appears that the dev team for `imagecache_external` have fixed this issue in their `dev` branch
@jordanpagewhite / @LightGuard I'd appreciate your review on this as I've applied a particular SHA1 version of a dev dependency, which is not something I've done before. The steps I followed to get the version of the dependency were:
- Visit [project page](https://www.drupal.org/project/imagecache_external)
- Click on the `Browse code repository`
- Click on the …
> [DEVELOPER-5269] Updated imagecache_external module to prevent internal server error if remote image cannot be fetched

- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/rhd_common.sitemap.inc
- pr-build-steps.sh
This resolves an issue where the 'old', paragraph-based subpages were
being indexed for Product pages using the 'new, assembly-based Product
page design/approach. This commit provides a conditional to the
simple_sitemap hook that creates these entries for custom
subpages/routing for the product pages that will distinguish
appropriately between the product nodes using the paragraphs-based
approach and those using the new, assembly-based approach.
* https://issues.jboss.org/browse/DEVELOPER-5633
* The site export can execute successfully
* All product page scenarios are properly handled by the simple_sitemap
**Case 1: Product node using old, paragraphs-based approach**
/sitemap.xml should display a route for each of the paragraph subpages/subroutes defined on the Node edit form. For …
> DEVELOPER-5633: Sitemap broken for product pages

- _docker/drupal/drupal-filesystem/web/config/sync/views.view.product_groups.yml
This error was a result of a missing handler (relationship) on the
product_groups View, which seemed to be some past image field. I removed
the relationship from the View and verified that the display of the View
remained the same. It did. I also verified that the error no longer was
logged. It was not.
* https://issues.jboss.org/browse/DEVELOPER-5622
Go here:
`/products`
and here:
`/product-testing`
Do this:
* Log in to your Drupal account and go to the logs `/admin/reports/dblog` and ensure there are no errors like `Notice: Undefined index: base in Drupal\views\Plugin\…` logged within the time you visited the two routes above.
> [DEVELOPER-5622] Product Category View Undefined Index Base

- _docker/drupal/drupal-filesystem/patches/openid_connect/openid_connect.module-logging.patch
This updates the way that variables are injected into the Logger
messages in a patch for the OpenID Connect module to the standard Drupal
way. This will ensure the output is HTML-safe.
* https://issues.jboss.org/browse/DEVELOPER-5648
* Patch applies cleanly / all build steps are green
* Messages are still logged properly in Drupal when a user logs in via OpenID Connect
> OpenID Path Logger Variables

- _docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.curated_links.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.assembly.curated_links.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.assembly.curated_links.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.curated_links.field_audience_selection.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.curated_links.field_content_list.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.curated_links.field_navigation_title.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.curated_links.field_title.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.article.field_content.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.assembly_page.field_sections.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.product.field_content.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.product.field_downloads_page_content.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.product.field_getting_started_content.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.topic_page.field_sections.yml
- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Plugin/AssemblyBuild/CuratedLinksBuild.php
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_curated-links.scss
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/rhd.scss
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/assembly/assembly--curated-links.html.twig
This creates a new assembly type: Curated Link (curated_link) and
includes the template and styling necessary to match the mock ups
provided by UX.
* https://issues.jboss.org/browse/DEVELOPER-5642
* You should be able to create a Curated Links assembly from the assembly reference fields on the following content types: Articles, Page, Product and Topic Pages
* You should be able to reference any of the following with the Curated Link assembly type: Node Reference, Static Item and Wordpress Post Reference
Curated Link assemblies should look like this:
**Mobile**
**Desktop**
> [DEVELOPER-5642] Curated Link Listing Assembly

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhdp.theme
* https://issues.jboss.org/browse/DEVELOPER-5649
Go here:
* /user/login (log in to your admin account)
* /admin/reports/dblog
Go here in another tab:
* /taxonomy/term/9?page=4
Do this:
* Refresh the /admin/reports/dblog page
No error like:
```
Notice: Undefined offset: 0 in rhdp_preprocess_node() (line 312 of /var/www/drupal/web/themes/custom/rhdp/rhdp.theme)
```
is logged in the Drupal dblog.
And, everything still renders the same on the Taxonomy page.
> [DEVELOPER-5649] Fix Undefined offset: hook_preprocess_node()

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhdp.theme
This verifies that the #id array key we access in hook_preprocess block
has some non-empty value prior to using the value in conditionals.
* https://issues.jboss.org/browse/DEVELOPER-5652
Go here:
/user/login
Do this:
* Login to you admin account using the default Drupal login form (not the SSO button/form)
Go here:
/admin/reports/dblog
You should *not* see an error logged that starts like this:
```
Notice: Undefined index: #id in rhdp_preprocess_block() (line 83 of /Users/jowhite/Sites/developers.redhat.com/_docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhdp.theme) #0 
```
> [DEVELOPER-5652] Undefined Index Preprocess Block

- _docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.video_hero.yml
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_video-hero.scss
[DEVELOPER-5655 - Full width video hero](https://issues.jboss.org/browse/DEVELOPER-5655)
Updates to the Video Hero assembly:
- Added the "Full width video" that displays video edge-to-edge. No other content from the assembly shoul be displayed.
I've added a full width video assembly to the bottom of this page: http://rhdp-jenkins-slave.lab4.eng.bos.redhat.com:37825/products/codeready-workspaces/overview
> [URGENT] [DEVELOPER-5655] Full width video hero

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhdp.theme
This verifies that an array key, #type, is set before accessing it in
hook_preprocess_field().
* https://issues.jboss.org/browse/DEVELOPER-5656
Go here:
/taxonomy/term/8585/feed
Then go here:
/user/login
and do this:
* log in to your admin account
* Go to the dblogs at /admin/reports/dblog
You should *not* see an error like this logged within the timeframe you visited /taxonomy/term/8585/feed 
```
Notice: Undefined index: #type in rhdp_preprocess_field() (line 619 of /var/www/drupal/web/themes/custom/rhdp/rhdp.theme) #1958 
```
> [DEVELOPER-5656] Undefined Index #type

- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.assembly_page.field_sections.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.topic_page.field_sections.yml
This adds the Feature Articles assembly type as an available assembly
type to reference from the Sections (assembly reference) field on the Page and
Topic Page content types.
* n/a
Do this:
* Log in to your editor or admin account at /user/login in the Drupal PR environment
Go here:
/node/add/assembly_page
You should be able to reference Featured Article assemblies using the Sections field.
Go here:
/node/add/topic_page
You should be able to reference Featured Article assemblies using the Sections field.
> Add Featured Articles to Page and Topic Page

- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.video_resource.field_video_resource_tags.yml
[DEVELOPER-5104 - DevNation Tech Talk Content Collection Page](https://issues.jboss.org/browse/DEVELOPER-5104)
Added the ability to tag video resources with audience segments (taxonomy) so videos can be used on Content Collection assemblies.
1. Add an item to audience_segment in taxonomy
2. Go into any video resouce, and it should allow you to add the audience_segment you just created in the tag field
> [DEVELOPER-5104] Added audience_segment to video taxonomy

- _docker/drupal/drupal-filesystem/composer.json
- _docker/drupal/drupal-filesystem/composer.lock
- _docker/drupal/drupal-filesystem/web/config/sync/core.extension.yml
- _docker/drupal/drupal-filesystem/web/config/sync/lightning_core.versions.yml
- _docker/drupal/drupal-filesystem/web/config/sync/login_security.settings.yml
- _docker/drupal/drupal-filesystem/web/config/sync/rest.resource.entity.node.yml
- _docker/drupal/drupal-filesystem/web/config/sync/seckit.settings.yml
This PR installs and enables the `seckit`, `login_security` and `rest ui` modules for Drupal. Additionally it provides some default configuration values.
The purpose of enabling this modules is primarily to increase the security of our Drupal instance once it is live on the Internet directly. In particular:
* `login_security` - provides us with some additional security around brute force login attempts and also sends out notifications to admins when suspicious login attempts occur
* `seckit` - provides us with better options for controlling security of things like XSS scripting attacks
* `restui` - gives us a greater oversight of what REST endpoints we're exposing and the authentication for those endpoints. Also allows us to prevent specific HTTP methods against endpoints
* …
> [MWES-2461] Activate seckit, login_security and REST UI modules for Drupal

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_videos.scss
[DEVELOPER-5653 - Broken style on video page](https://issues.jboss.org/browse/DEVELOPER-5653)
Style is broken when there are more than one speakers listed on a video resource page. See speakers on /videos/youtube/QYbXDp4Vu-8
Visit a video page with more than one speaker ( /videos/youtube/QYbXDp4Vu-8 ), and check that the speakers' names are shown on the same line, separated by a comma.
> [DEVELOPER-5653] Minor style fix for video resources

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhdp.theme
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/views/views-view-fields--connectors_rest_export--connectors_rest_export_block.html.twig
This resolves an issue that prevented the following links (and
associated link text) from displaying for every Connector:
field_connector_link_1, field_connector_link_1_text,
field_connector_link_2, field_connector_link_2_text and
field_connector_details_url.
We were not properly accessing these values anyway, but in addition to
that, we were not verifying that any value(s) existed for any of the
fields before trying to access them, which resulted in both nothing
being rendered and many errors being thrown in the logs any time the
Connectors page was visited.
I am now verifying values exist, in a preprocessor for the
views-view-fields, and then accessingt those values and setting them in
the $variables array before accessing them in the Twig template.
* …
> [DEVELOPER-5646] Invalid Render Array Keys

- _docker/drupal/drupal-filesystem/composer.json
- _docker/drupal/drupal-filesystem/composer.lock
- _docker/drupal/drupal-filesystem/patches/akamai/change-button-text.patch
- _docker/drupal/drupal-filesystem/web/config/sync/akamai.settings.yml
- _docker/drupal/drupal-filesystem/web/config/sync/block.block.akamaicacheclear.yml
- _docker/drupal/drupal-filesystem/web/config/sync/block.block.universalheader.yml
- _docker/drupal/drupal-filesystem/web/config/sync/block.block.useraccountmenu.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.extension.yml
- _docker/drupal/drupal-filesystem/web/config/sync/lightning_core.versions.yml
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_akamai-block.scss
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_navigation.scss
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/rhd.scss
- _docker/environments/drupal-dev/rhd.settings.php
- _docker/environments/drupal-production/docker-compose.yml
- _docker/environments/drupal-pull-request/docker-compose.yml
- _docker/environments/drupal-pull-request/rhd.settings.php
- _docker/environments/drupal-staging/docker-compose.yml
This PR brings integrates Drupal with the Akamai Fast Purge API allowing content editors to request clears of content in the Akamai Cache directly from Drupal.
Please note this functionality is **disabled** in PR and dev environments.
This PR adds a button to the top of the user navigation window when browsing content in Drupal. The button is titled "Refresh Page in Akamai". Clicking on this button will send a request to Akamai to clear the cache entry for the page being viewed. This mechanism gives content editors a way of immediately requesting changes to published.
**Note:** Until Drupal is running on Managed Platform, content editors are still reliant upon the export process running before their content will appear live on the site. I need to merge this functionality back into our …
> [MWES-2463] Integrate Drupal with Akamai Fast Purge API

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_content_with_image.scss
[DEVELOPER-5660 - Homepage H1/H2 adjustments](https://issues.jboss.org/browse/DEVELOPER-5660)
- Updates H2 style in rich text with image assembly to match the styles of the previously used H1 header.
- H2 header in the first hero on homepage (Rich Text with Image - Homepage Most Valuable Products) should be sized: 50px.
> [DEVELOPER-5660] Homepage header fixes

- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.user.user.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/views.view.books_rest_export.yml
- _docker/drupal/drupal-filesystem/web/config/sync/views.view.cheat_sheets_rest_export.yml
- _docker/drupal/drupal-filesystem/web/config/sync/views.view.connectors_rest_export.yml
- _docker/drupal/drupal-filesystem/web/config/sync/views.view.events_rest_query.yml
- _docker/drupal/drupal-filesystem/web/config/sync/views.view.rest_products.yml
- _docker/drupal/drupal-filesystem/web/config/sync/views.view.taxonomy_tags_rest_export.yml
- _docker/drupal/drupal-filesystem/web/config/sync/views.view.video.yml
- _docker/drupal/drupal-filesystem/web/config/sync/views.view.vimeo_videos.yml
- _docker/drupal/drupal-filesystem/web/config/sync/views.view.youtube_videos.yml
This PR makes an update to all views used by the DCP for content indexing to explicitly configure the `json` serializer. Without this none of the views work on the Managed Platform deployment of Drupal.
I do not know why this works on  the legacy Drupal deployment, but not on Managed Platform.
It also brings in some configuration that appears to have been changed in prod and not captured into Git.
* https://issues.jboss.org/browse/MWES-2947
* Ensure the build goes green
* Log in to Drupal and ensure there are no dangling configuration changes to import
* Ensure that the following URLs give you JSON output:
* /drupal/books?_format=json
* /drupal/events?_format=json
* /drupal/cheat-sheets?_format=json
* /drupal/connectors?_format=json
* /drupal/videos?_format=json
* …
> [MWES-2947] Fixed views for supporting DCP content indexing

- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_common/src/Controller/ProductPageController.php
I forgot that there are 2 'types' of config objects in Drupal 8, and
only 1 of those support config overrides. I was using the mutable config
object to check trailing_slash config key/values, but the mutable config
objects do not respect config overrides, which was discovered as an
issue once this went to MP. I have now changed the code so that I'm only
using the mutable object to inject URLs into the trailing_slash
settings, and instead using the immutable object to retrieve
trailing_slash config key/values.
* n/a
* Create a config override: `$config['trailing_slash.settings']['enabled'] = TRUE`
* This should resolve the trailing slash issues for the Product pages we were experiencing on the MP stage deployment
> [MWES-2910] Updates configuration checks for trailing_slash

- _docker/drupal/drupal-filesystem/web/config/sync/views.view.taxonomy_term.yml
This disables the View pages generated by the taxonomy_term View except
for the tags taxonomy terms/vocab.
* https://issues.jboss.org/browse/DEVELOPER-5663
Go here: /taxonomy/term/8725 (8725 is a taxonomy term id under the product_categories vocabulary)
You should see the RHDP 404 Page Not Found page/template.
> [DEVELOPER-5663] Disable Taxonomy Term Views Pages (not tags)

- _docker/drupal/drupal-filesystem/web/config/sync/user.role.content_admin.yml
- _docker/drupal/drupal-filesystem/web/config/sync/user.role.content_creator.yml
Content Creators can no longer edit or view URL Aliases, but I added the
ability for Content Admin to view and edit URL Aliases. NOTE: Content
Admin already had the ability to Administer URL Aliases, so this is a
somewhat redundant change in that sense. I thought it made sense to give
the permission to Content Admin though in case a quick edit had to be
made.
* https://issues.jboss.org/browse/DEVELOPER-5664
> [DEVELOPER-5664] URL Alias permissions changes

- README.md
- _docker/environments/drupal-dev/docker-compose.yml
- _docker/environments/drupal-pull-request/docker-compose.yml
- _docker/environments/drupal-staging/docker-compose.yml
This PR updates the PR environment, local dev environment and legacy stage environment to use data images generated from the Managed Platform deployment of Drupal and hosted within the internal Red Hat IT managed Docker Registry.
**THIS MUST NOT BE MERGED UNTIL MANAGED PLATFORM DEPLOYMENT IS LIVE**
* https://issues.jboss.org/browse/MWES-2944
* Ensure that the build goes green.
> [MWES-2944] Use Data Images from Managed Platform Deployment

- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.assembly_page.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.assembly_page.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.assembly_page.field_hide_title.yml
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/node/node--assembly-page--full.html.twig
This creates a new boolean field on the Page content type, and makes
adds a node--assembly-page--full Twig template, which allows editors to
conditionally hide the Title field on Page nodes via a checkbox field
directly beneath the Title field on the node edit form.
* https://issues.jboss.org/browse/DEVELOPER-5704
* Open the Drupal PR environment and log in using your admin/editor credentials
* Open `/finservices/openbanking` and `/finservices/openbanking/edit` in two tabs
* You should notice that the page title on the Open Banking page displays (as it does on Prod for example)
* On the edit form, you should see a new checkbox field 'Hide Title' directly below the Title field
* Check this Hide Title checkbox and submit the form to save your changes
* Refresh the Open Banking page: …
> [DEVELOPER-5704] Conditionally hide title Pages

- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.article.field_content.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.assembly_page.field_sections.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.product.field_content.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.product.field_downloads_page_content.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.product.field_getting_started_content.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.topic_page.field_sections.yml
This adds all assemblies to Assembly fields on new world content types.
I have not included the Product Download List, Product Download Hero and
Product Try-It Hero assembly types to non-Product assembly fields only
because they will not work without an id to pass to download manager and
fetch the data necessary to render the assembly.
* https://issues.jboss.org/browse/DEVELOPER-5679
All assembly types can be references from all assembly reference fields on the Product, Page, Topic and Article content types with the exception of the Product Download List, Product Download Hero and Product Try-It Hero assembly types on non-Product assembly fields.
> [DEVELOPER-5679] Add all assemblies to new world

- _docker/drupal/drupal-filesystem/composer.lock
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.assembly_page.default.yml
A couple small followup issues from the compose merge:
* Fixes the entity browser widget used for share images on page nodes
* Updates beryllium to fix the width on entity browser modal dialogs
> Developer 5505 followup

- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.product.field_content.yml
https://issues.jboss.org/browse/DEVELOPER-5757
login to cms and edit a product page "Content" field on Product Pages should read "Overview Page Content"
> [DEVELOPER-5757] change content field label to Overview Page Content

- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.article.default.yml
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_articles.scss
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_featured_articles.scss
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/articles/node--article--card.html.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/articles/node--article.html.twig
[DEVELOPER-5765 - Article Content Type: Related articles view mode update](https://issues.jboss.org/browse/DEVELOPER-5765)
Per my discussion with Gina, the card style used on Featured Articles will be reused for Related Articles in any article page.
1. Go to http://rhdp-jenkins-slave.lab4.eng.bos.redhat.com:37894/node/205615
2. The related articles at the bottom should be displayed in a card style, without the black border at the top.
> DEVELOPER-5765 - Updated related articles view

- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.katacoda_course.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.katacoda_course.teaser.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.katacoda_individual_lesson.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.katacoda_individual_lesson.teaser.yml
This PR is simply a fresh `drush cex` using the most recent production data dump to ensure that we capture the currently dangling Katacoda configuration changes.
* https://issues.jboss.org/browse/DEVELOPER-5792
* Visit the configuration synchronisation screen in Drupal and ensure there are no changes left to import
> [DEVELOPER-5792] Exported dangling Katacoda configuration from production

- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_eloqua_embed/src/Controller/EloquaEmbedController.php
This resolves a PHP notice that was spamming the logs due to trying to
access the undefined offset 0 in the ternary operator. To resolve it, I
am validating the the array isset for that key first in an if/else
statement.
* https://issues.jboss.org/browse/DEVELOPER-5691
* You can visit an eloqua embed form (ex. https://developers.redhat.com/rhd/rhd_eloqua_embed/5745) and you when you review the logs, you should not see an error like Notice: Undefined offset: 0 in Drupal\rhd_eloqua_embed\Controller\EloquaEmbedController->getForm()
> [DEVELOPER-5691] EloquaEmbedController Offset

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/learning-path/node--video-resource--learning-path-card.html.twig
This resolves an issue with a null-coalescing operator on 2 lines, which
both use the |capitlize filter, in
node--video-resource--learning-path-card.html.twig. An empty array was
being evaluated by the null-coalescing operator, so that was passed to
the capitalize filter, which results in an error since the capitalize
filter requires a string param.
* https://issues.jboss.org/browse/DEVELOPER-5696
* Go here: http://localhost:8888/learn/reactive-meets-microservices
* View the logs and you should not see an error like "Warning: mb_substr() expects parameter 1 to be string, array given in twig_capitalize_string_filter()"
* The top-level node divs being output for Nodes without a value for the Level field should have an attribute like `level="Unclassified"`, whereas the ones with a value set …
> [DEVELOPER-5696] Fixed logic error with null-coalescing operator

- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.video_resource.default.yml
Update the Video Resource moderation state widget to the Moderation
State widget instead of the Textfield widget.
* https://issues.jboss.org/browse/DEVELOPER-5811
* Go here `/node/add/video_resource`
* Click on the settings tab
* Open the Moderation State section
* You should see the Moderation State dropdown widget with: Draft, Needs Review and Published
> [DEVELOPER-5811] Video Resource Moderation State

- _docker/drupal/drupal-filesystem/web/config/sync/node.type.katacoda_course.yml
- _docker/drupal/drupal-filesystem/web/config/sync/node.type.katacoda_individual_lesson.yml
- _docker/drupal/drupal-filesystem/web/config/sync/system.menu.katacoda-courses.yml
- _docker/drupal/drupal-filesystem/web/config/sync/views.view.katacoda_all_courses.yml
To fix this issue with the missing intermediate breadcrumb link, we need
to add these pages, and their desired structure/nesting, to a menu. I
have created a new menu in Drupal that we can add this Katacoda content
to. When courses and individual scenarios are properly added to the
menu, this breadcrumb issue will be resolved.
* https://issues.jboss.org/browse/DEVELOPER-5758
* Go here: http://rhdp-jenkins-slave.lab4.eng.bos.redhat.com:37913/courses/serverless
* Click on any of the Katacoda Individual Scenarios by using the Start buttons
* You should see the breadcrumbs at the top of the page properly list each step in navigation, for example: `Katacoda All Courses > Serverless Interactive Tutorials > Serverless: Simple Javascript Greeting Function`
Example:
> [DEVELOPER-5758] Katacoda Breadcrumb Fix

- _docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.events_hero.yml
- _docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.product_download_hero.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.assembly.events_hero.default.yml
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_events-hero.scss
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_product_hero.scss
[DEVELOPER-5780 - Add Visual Style Field to Events Hero
](https://issues.jboss.org/browse/DEVELOPER-5780)
Added light/dark visual styles to the Events Hero Assembly.
1. Go to http://rhdp-jenkins-slave.lab4.eng.bos.redhat.com:37914/devnation/edit
2. Select a the light visual style
3. Go back to http://rhdp-jenkins-slave.lab4.eng.bos.redhat.com:37914/devnation and the events hero should have a light background image with dark type
4. Repeat selecting the dark visual style
5. The hero should have a dark background image with white type
> DEVELOPER-5780 - Add Visual Style Field to Events Hero

- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/rhd_assemblies.module
This adds a custom validation hook for non-Product node forms and node
edit forms that will ensure that an editor does not accidentally add a
route that conflicts with one of our reserved Product sub-page routes:
/overview, /download or /getting-started.
* https://issues.jboss.org/browse/DEVELOPER-5737
* Go here: http://rhdp-jenkins-slave.lab4.eng.bos.redhat.com:37918/node/add/assembly_page
* Add some value for the Title field
* Click on the Settings tab
* Click on URL Alias to reveal the URL Alias input
* Add the following value for the URL Alias input: `/products/rhamt/overview`
* Add some value for the Revision Log field
* Click Save to submit the form
You should see the following error displayed that prevents the form from submitting with the reserved URL pattern:
> [DEVELOPER-5737] Add custom validation hook for non-Product nodes

- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Plugin/AssemblyBuild/DynamicContentFeedBuild.php
- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Service/WordpressApi.php
This commit updates the Dynamic Content List Assembly to allow pulling
all latest content, ordered by most recent, from Drupal and Wordpress.
Currently, an editor has to specify some categories in order to get
results from Wordpress or Drupal. This makes it so that when no
categories are specified, the latest content is pulled from Drupal and
Wordpress.
* https://issues.jboss.org/browse/DEVELOPER-5820
* Go here: http://rhdp-jenkins-slave.lab4.eng.bos.redhat.com:37920/node/add/assembly_page
* Add some value for the Title field
* Click on the dropdown of Assembly types in the Sections field
* Select Dynamic Content List
* Click Add new assembly
* Add values for the Name and Title fields
* Click on the Settings Tab
* Add a URL Alias
* Click Save to save the new Dynamic Content List assembly …
> [DEVELOPER-5820] Dynamic Content List Assembly

- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.product.default.yml
This makes the Logo and CTA Link fields available to editors under the
Fields tab of Product node forms.
* n/a
* Go here: http://rhdp-jenkins-slave.lab4.eng.bos.redhat.com:37923/node/add/product
* Click on the Fields tab
* There should be Logo and CTA Link fields available to edit
> Display Logo and CTA fields on Product node Form

- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.assembly.product_download_hero.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.assembly.product_try_it_hero.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.assembly.product_download_hero.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.assembly.product_try_it_hero.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.product_download_hero.field_background_image.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.product_try_it_hero.field_background_image.yml
[DEVELOPER-5823 - Add background image field to assemblies](https://issues.jboss.org/browse/DEVELOPER-5823)
Content creator should be able to add a background image to the Product Download assembly and the Product Try-it assembly.
> [DEVELOPER-5823] Added background image field to assemblies

- _docker/drupal/drupal-filesystem/web/config/sync/user.role.content_creator.yml
In DEVELOPER-5664, I removed the permission for Content Creators to
add/edit URL aliases. This was part of an effort to reduce clutter on
Node edit forms. At the time, I thought that the URL aliases for all
nodes were being generated automatically by Pathauto. That is not the
case, so this was a regression.
Furthermore, now that we are using Compose and the URL alias field is
not on the main page causing visual bloat, I do not think that this is
adding to UX clutter.
* https://issues.jboss.org/browse/DEVELOPER-5768
* Log into an account that has the Content Creator role (and not other roles like the Content Admin or Administrator roles)
* Go to any node edit/create form like: `/node/add/assembly_page`
* Click on the Settings tab
* You should see a URL Alias tab. Click on it to reveal the …
> [DEVELOPER-5768] Add URL Alias for Content Creator

- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.katacoda_individual_lesson.field_katacoda_scenario_time.yml
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_katacoda.scss
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/katacoda/node--katacoda-course.html.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/katacoda/node--katacoda-individual-lesson--card.html.twig
* https://issues.jboss.org/browse/DEVELOPER-5817
Go here: `/courses/serverless`
* There should be a space between the minutes (Int value) and 'minutes' string in the Katacoda Individual Scenario cards
Go here:  `/courses`
Go here:  `/courses/serverless` (open in another tab to compare)
* The two hero elements should very closely match
** The background image implementation should now be the same
** The padding should be the same or nearly the same between all the various elements
** The font size(s) and weight(s) should be the same
* Gina
> [DEVELOPER-5817] Improve Katacodas Hero and Add Space to Duration

- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.katacoda_individual_lesson.default.yml
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_katacoda.scss
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/katacoda/field--node--field-katacoda-embed-id.html.twig
These changes make the Katacoda Individual Scenario node Default view
mode meet the designs from Gina.
* https://issues.jboss.org/browse/DEVELOPER-5839
* Gina and Joe
Go here: http://rhdp-jenkins-slave.lab4.eng.bos.redhat.com:37936/courses/openshift/getting-started-openshift
Do this:
* Make your viewport > 812px
* You should see the Katacoda scenario (iframe)
* If you scroll down, you should *not* see "Sorry for the inconvenience" and the Katacoda logo like this:
Do this:
* Make your viewport < 812px
Go here: http://rhdp-jenkins-slave.lab4.eng.bos.redhat.com:37936/courses
* Within each row in the grid, cards are a consistent height 
NOTE: Currently, on our PR environments, the /courses route displays "404: You've found …
> [DEVELOPER-5839] Make Individual Scenario Default Meet Designs

- .gitignore
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/.dockerignore
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/Dockerfile
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/tests/unit/config/karma.conf.js
- _docker/tests/test-runner/test_run_tests.rb
- _tests/run_tests.rb
- _tests/unit/environments/docker-compose.yml
This PR updates the unit tests to run on Blessed Docker images ahead of our migration to Managed Platform for pull request builds.
In particular this PR:
- Ensures that unit tests run in a blessed container
- Ensures that the unit tests run as a non-root user (using root user is not supported on Managed Platform)
- Ensures that the unit tests container operates in non-priviledged mode (this is not supported on Managed Platform)
* https://issues.jboss.org/browse/MWES-3085
- Unit tests should go green
- You can visit the test report successfully in Jenkins
> [MWES-3085] Ensured that unit tests run on blessed Docker Images

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/js/terms-and-conditions.js
[DEVELOPER-5830 - Fix multiple downloads on media page](https://issues.jboss.org/browse/DEVELOPER-5830)
The media download thank you page should only display one of the blue banners, and it should only download the file once.
To test this go to: /cheat-sheets/podman-basics/
**Note:** when testing this, you'll need to go back to the PR build after logging in, otherwise you'll be testing the staging media thank you page
> DEVELOPER-5830 Fix multiple downloads on media pages

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/books/node--books--card.html.twig
I have added a validation check around our markup for the image in the
Books Card template. This resolves the issue that Gina was experiencing
with the Featured Resources assembly type.
* https://issues.jboss.org/browse/DEVELOPER-5847
* Create a Basic Page and add a Featured Resources assembly type
* Add Drools Developer’s Cookbook to the entity reference field (autocomplete) of that Featured Resources assembly
* Save the Basic Page and view it
* You should not receive any error, and you should be able to view the page
* It should look something like this
> DEVELOPER-5847: Twig Tweak Type Error

- _docker/drupal/drupal-filesystem/composer.json
- _docker/drupal/drupal-filesystem/composer.lock
- _docker/drupal/drupal-filesystem/web/config/sync/akamai.settings.yml
Akamai are ending support for v2 of their FastPurge API which is what we are currently using. Therefore we need to bump it to use v3. The Akamai Plugin supports v3 out-of-the-box, but I have taken the chance here to update the plugin to the latest version and then ensured that we're using v3 by default
This PR is targeting `stage` branch in the first instance so that I can verify the functionality works as expected in an environment that has Akamai support. Additionally I need to do some updates to our Managed Platform environments to support the latest version of Akamai credentials for v3 of the API.
* https://issues.jboss.org/browse/MWES-3156
* View `admin/reports/updates` in Drupal and ensure Akamai plugin is at version `8.x-3.0-alpha4`
* View …
> [MWES-3156] Update Akamai to CCUV3

- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/rhd_assemblies.module
Within a validation hook, used to validate that non-Product URL aliases
will not conflict with programmatically-generated Product URL paths, we
are not validating that a URL alias is set prior to accessing the value.
This commit validates that the URL alias is set prior to accessing the
value.
This will remove the following error from the Drupal logs: "Notice:
Uninitialized string offset: 0 in..."
* n/a
* Go to any non-Product Node edit form i.e. `node/209371/edit` pattern
* Save the node edit form without setting a URL Alias value
* You should _not_ see an error like "Notice:
Uninitialized string offset: 0 in..." in the Drupal logs
> Uninitialized String Offset Product URL Alias

- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Plugin/AssemblyBuild/BlogPostsBuild.php
- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Plugin/AssemblyBuild/DynamicContentFeedBuild.php
- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Service/WordpressApi.php
https://issues.jboss.org/browse/DEVELOPER-5878
This is. fix for all dynamic list assembly requests returning the same content (broken filter).
check the homepage compared with live, the 'build here' and 'go anywhere' sections should have different content.
Also if you check /topics/kubernetes/ it should have different content in the 'Kubernetes development articles' to the 'go anywhere' panel on the homepage.
If you edit the /topics/kubernetes/ page and edit the dynamic list assembly on that page, checking the 'Wordpress category use 'and' logic' should change the content in the 'Kubernetes development articles' section then change it back and ensure the content changes back appropriately.
check the dynamic list assembly content varies as it should and the and/or logic works
> [DEVELOPER-5878] update logic and fix issues with null

- Jenkinsfile
- _docker/drupal/managed-platform/ansible/templates/preview/drupal/phinx.yml.j2
- _docker/drupal/managed-platform/ansible/templates/preview/drupal/rhd.settings.php.j2
- _docker/drupal/managed-platform/ansible/templates/preview/drupal/rhd.settings.yml.j2
- _tests/.dockerignore
- _tests/e2e/.dockerignore
- _tests/e2e/tests/config/wdio.conf.base.js
- _tests/e2e/tests/specs/export/rhd-downloads.spec.js
- _tests/e2e/tests/specs/support/utils/Utils.js
- previews/README.md
- previews/connect-to-db.sh
- previews/connect-to-drupal.sh
- previews/oc-config.sh.example
- previews/view-drupal-boot-logs.sh
- previews/view-drupal-logs.sh
This PR introduces supporting code for migrating the `d.r.c` pull request pipeline to run on Managed Platform. This PR _**does not**_ change the existing pipeline, so the build for this PR should complete as normal. Any failure on this build should be investigated.
Once on managed platform, PR builds will benefit from:
* No export
* Full HTTPS support 
* Downloads work in PR environments
* Keycloak logins work in PR environments
* Drupal runs on its own domain name at the root of the domain
* https://issues.jboss.org/browse/MWES-2920
> [MWES-2920] Run pull request builds on Managed Platform

- _docker/drupal/drupal-filesystem/web/config/sync/editor.editor.full_html.yml
- _docker/drupal/drupal-filesystem/web/config/sync/editor.editor.rhd_html.yml
- _docker/drupal/drupal-filesystem/web/config/sync/editor.editor.rich_text.yml
- _docker/drupal/drupal-filesystem/web/config/sync/filter.format.full_html.yml
- _docker/drupal/drupal-filesystem/web/config/sync/filter.format.rhd_html.yml
- _docker/drupal/drupal-filesystem/web/config/sync/filter.format.rich_text.yml
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/typography/_heading.scss
https://issues.jboss.org/browse/DEVELOPER-5740
Added the ability for the content creator to style headers with other header styles ( for example, to have an H2 that looks like an H1).
I spent a long time trying to get Alloy's plugin for this to work, but it was possible to get it to work with our RHDP theme. I tried to figure out what was breaking the plugin with Matt, but I ended up coming up with a solution that adds a `<span>` tag with the desired class, inside the header tag. Adding the span tag does not affect SEO, as the `<span>` element has no semantic meaning.
I created a dummy page where you can preview these styles. You can use the inspector to be sure things headers are being styled correctly. Test page: http://rhdp-jenkins-slave.lab4.eng.bos.redhat.com:37965/testpage
To test …
> DEVELOPER-5740 - Adjustments to global headers

- _tests/e2e/tests/specs/export/rhd-search.spec.js
We're seeing intermittent failures on the search tests. Running through the tests by hand everything seems to be fine. Looking over the tests there doesn't seem to be anything that explicitly waits for the results to be loaded before running assertions. In the new preview environments, pages will load noticeably quicker than before as we have gzip compression enabled. It could simply be that the improved performance here is showing up race conditions that we've always had but were simply hidden by the performance of the site
> [MWES-2920] Ensure that search tests explictly wait for the results to be shown

- Jenkinsfile
This PR adds the ability to run _only_ the acceptance tests on a pull request build if you want too. This is particularly useful when a test is being flaky and you want to quickly retry it.
The PR introduces the following behaviour:
* Comment `rebuild this please` on your pull request to receive a full rebuild of  your preview environment and a re-run of the acceptance test suite
* Comment `retest this please` on your pull request to re-run _only_ the acceptance tests. You will obviously need to ensure that your environment is up and running.
I've just used the `retest this please` functionality to get the tests to pass on this PR as you can see from the comment history.
* https://issues.jboss.org/browse/MWES-3311
* Comment `rebuild this please` on the PR to see a complete environment …
> [MWES-3311] Support only running tests on pull request builds

- _docker/drupal/Dockerfile
- _docker/drupal/Dockerfile.mp
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/Dockerfile
- _tests/e2e/tests/specs/support/pages/website/components/search/SearchFilter.js
IT PaaS team are requesting that everyone build their images to images.paas.redhat.com so that registry.paas.redhat.com can be decommissioned. This is the first step for us getting our Drupal images into images.paas.redhat.com instead.
* https://issues.jboss.org/browse/MWES-2989
> [MWES-2989] Migrated base Docker images to images.paas.redhat.com

- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Service/WordpressApi.php
This PR dramatically reduces the number of calls that are made to Wordpress to fetch content. It builds upon the work done by @jordanpagewhite in #2986 (this PR only adds PHP fixes for errors that were apparent in the Drupal logs).
We are looking to reduce the number of calls to Wordpress to an absolute minimum as they are very slow and produce a bad experience for content editors when they are accessing the site.
* https://issues.jboss.org/browse/DEVELOPER-5907
* All Wordpress related functionality should be working as expected
> [DEVELOPER-5907] Reduce calls to WordPress API to improve content editor experience

- _docker/drupal/Dockerfile.mp
- _docker/drupal/managed-platform/ansible/templates/dev/drupal/rhd.settings.php.j2
- _docker/drupal/managed-platform/ansible/templates/local/drupal/rhd.settings.php.j2
- _docker/drupal/managed-platform/ansible/templates/preview/drupal/rhd.settings.php.j2
- _docker/drupal/managed-platform/ansible/templates/prod/drupal/rhd.settings.php.j2
- _docker/drupal/managed-platform/ansible/templates/stage/drupal/rhd.settings.php.j2
- _docker/drupal/managed-platform/etc/opt/rh/rh-php71/php.d/50-developer-drupal.ini
This PR follows the advice at https://www.drupal.org/docs/7/managing-site-performance/tuning-phpini-for-drupal to apply recommended filesystem configuration for Drupal.
* https://issues.jboss.org/browse/MWES-3390
* Visit `/admin/reports/status` and ensure that `PHP memory limit` is `256M`
* [Log in to the Drupal container](https://github.com/redhat-developer/developers.redhat.com/tree/master/previews) and ensure the following are true:
* `drush php:eval "print_r(ini_get('memory_limit'));"` == `256M`
* `drush php:eval "print_r(ini_get('realpath_cache_size'));"` == `256k`
* `drush php:eval "print_r(ini_get('realpath_cache_ttl'));"` == `300`
> [MWES-3390] Added recommended PHP configuration for filesystem operations

- _docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.featured_articles.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.assembly.featured_articles.default.yml
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/_articles.scss
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/styles/assembly/_featured_articles.scss
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/field--assembly--field-articles--featured-articles.html.twig
https://issues.jboss.org/browse/DEVELOPER-5885
Updated Featured Articles assembly to use a Flexbox layout instead of the Zurb Foundation grid, and so that when there are only one or two articles, the tiles are centered instead of floating to the left.
Featured Articles should be center aligned instad of left aligned on pages such as /products/codeready-workspaces/getting-started
> DEVELOPER-5885 - Updated Articles tile view

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/js/drupal-namespace.js
https://issues.jboss.org/browse/RHDFEED-816
Unable to test this in PR since the download manager is showing 3.8 version for this environment.
go to /products/cdk/download and check the feature download has the 3.9 version and the link is correct.
> [RHDFEED-816] update cdk download version 3.9.0-1

- _docker/drupal/drupal-filesystem/composer.json
- _docker/drupal/drupal-filesystem/composer.lock
- _docker/drupal/drupal-filesystem/web/config/sync/bootstrap.settings.yml
This updates the drupal/bootstrap contrib theme to its latest version,
which is a significant improvement/change. This commit also sets the
config of the theme to declare no CDN, as opposed to the JSDelivr CDN.
Both of these changes are necessary to remove an unpredictably large
number of CDN requests that were being made on every admin request to
the JSDelivr CDN. As noted in the Github issue, this should result in a
significant performance increase in pages that use the admin theme(s).
* https://github.com/redhat-developer/developers.redhat.com/issues/3008
* No calls are made to the JSDelivr CDN
* The average load time of admin pages improves, as noted in the linked Github issue
> [#3008] Update drupal/bootstrap and set no CDN

- _docker/drupal/dev/README.md
- _docker/drupal/managed-platform/ansible/templates/dev/drupal/rhd.settings.php.j2
- _docker/drupal/managed-platform/ansible/templates/local/drupal/rhd.settings.php.j2
- _docker/drupal/managed-platform/ansible/templates/preview/drupal/rhd.settings.php.j2
- _docker/drupal/managed-platform/ansible/templates/stage/drupal/rhd.settings.php.j2
This update makes memcached the default cache engine for all environments other than production and local dev to ensure it works as expected with our deployment workflow.
* https://issues.jboss.org/browse/MWES-2871
* Visit `/admin/reports/memcache` and ensure that two memache instances are listed
> [MWES-2871] Make memcached default cache engine in all environments but prod and local dev.

- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_disqus/js/disqusFetch.js
* https://sentry.io/share/issue/01661b0203b94e90a51aac4d81262f18/
This is an error from Sentry that has been a huge contributor to errors in the system. The original logic was not working in cases where the variable was undefined, which caused an error to be thrown.
> Fix broken comment script

- _docker/drupal/managed-platform/ansible/templates/prod/drupal/rhd.settings.php.j2
As a follow up to #3017 , this PR enables memcached as the cache engine of choice for Drupal in production.
* https://issues.jboss.org/browse/MWES-2871
* Build should go green.
> [MWES-2871] Enable memcached for our production deployment of Drupal

- _docker/drupal/dev/README.md
- _docker/drupal/dev/docker-compose.yml
- _docker/drupal/dev/run-config-export.sh
This commit changes the way we run drush cex in the local development environment to ensure that deletion of configuration is properly captured and also to address an issue whereby Drupal could not write to the sync directory because it was owned by root.
The README.md is also updated to reflect the latest changes and the run-config-export.sh now performs a quick check to ensure we have properly bootstrapped the local Drupal instance before trying to export configuration
* https://issues.jboss.org/browse/DEVELOPER-5942
* https://issues.jboss.org/browse/DEVELOPER-5941
* Make changes to your local Drupal configuration (including uninstalling a module)
* Run `run-config-export.sh` in the `_docker/drupal/dev` directory
* Ensure that a `git status` shows what you would …
> [DEVELOPER-5941] [DEVELOPER-5942] Fix drush cex errors in local development environment

- _docker/drupal/dev/run-drupal-connect.sh
- _docker/drupal/dev/run-drupal.sh
This PR fixes the permissions in the local dev environment so that you can edit the contrib modules files.
Closes #3033 
* #3033 
* Ensure that in the local development environment, once Drupal has booted you can run `./run-drupal-connect.sh` and edit any of the files within the `/var/www/drupal/web/modules/contrib` directory.
> [3033] Fix permissions on /modules/contrib for local development

- _docker/drupal/Dockerfile.mp
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/.npmrc
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/package-lock.json
This PR updates the `rhd-frontend` component within the `rhdp` theme to use the internal Nexus repository to offset traffic to `registry.npmjs.org`
* https://issues.jboss.org/browse/MWES-3496
* The build should go green.
* Visit the site and ensure it looks and functions as expected.
> [MWES-3496] Use Nexus for all npm dependencies

- _docker/drupal/Dockerfile
- _docker/drupal/Dockerfile.mp
- _docker/drupal/dev/docker-compose.yml
- _docker/drupal/dev/run-drupal.sh
This updates the local development experience to remove the usage of `http_proxy` and `https_proxy` environment variables.
* https://issues.jboss.org/browse/MWES-3412
* Log in to the container locally and ensure that `printenv` does not show the usage of `http_proxy` or `https_proxy`
* Log in to the PR Drupal container and ensure that `http_proxy` and `https_proxy` are correctly set to `http://proxy.util.phx2.redhat.com:8080`
> [MWES-3412] Clean-up usage of http_proxy and https_proxy environment variables

- _docker/drupal/Dockerfile.mp
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/system/html.html.twig
* none
The following errors (in the screenshot above) should no longer exist:
- All of the font fetch errors starting at the second error in the list down to overpass-bold.ttf
- The errors for site.webmanifest and favicon.ico (second and third from the bottom)
> Fixes broken favicon paths & updates rhd-frontend

- _tests/e2e/Dockerfile
- _tests/e2e/package-lock.json
Discovered that the e2e tests are also running `npm install` and therefore need to be updated to use the internal Nexus repo.
* https://issues.jboss.org/browse/MWES-3496
* Build should go green.
> [MWES-3496] Make use of the Nexus repository for the e2e tests

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--content-with-image.html.twig
* #3036 
Go here: /openshift
TBD
Go here: https://developer-preview-3077.ext.us-west.dc.preprod.paas.redhat.com/topics/containers
TBD
*NOTE:* The link at the bottom of the content is displaying as a plain text link instead of a CTA button. This is an issue that will either have to be resolved in content (WYSIWYG) or via CSS overrides. Since I think that it will be incredibly challenging to replace every instance of a legacy class in WYSIWYG text, I have suggested CSS override(s) in this ticket: https://github.com/redhat-developer/rhd-frontend/issues/199 in the rhd-frontend repo.
> [SURGE-3036] Rich text with image

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhdp2.libraries.yml
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--curated-links.html.twig
* #3056 
* #3070 
Go to: https://developer-preview-3081.ext.us-west.dc.preprod.paas.redhat.com/openshift
Also, our new RHD FontAwesome kit should load https://kit.fontawesome.com/3f83b4c6d2.js , and our prior iteration of the FontAwesome script should not js/all.min.js
This addresses #3070
> [SURGE-3056] Curated links

- _docker/drupal/drupal-filesystem/static/cdn/devsuite/java-1.8.0-openjdk.windows.x86_64.version.json
Adding this piece of JSON from the legacy docroot that we currently mount from the static web servers. No-one seems to know what it's for, but until we can track that down it will prevent us from decomissioning the legacy web servers. Instead we can simply host it as part of Drupal (for now) and that will allow us to decommission the old infrastructure.
* https://issues.jboss.org/browse/MWES-3422
* Visit `/cdn/devsuite/java-1.8.0-openjdk.windows.x86_64.version.json` on the Drupal instance for this PR and ensure the contents of the file in this PR show.
> [MWES-3422] Add static JSON from legacy Docroot

- _docker/drupal/dev/README.md
- _docker/drupal/dev/run-drupal.sh
- _docker/drupal/managed-platform/ansible/testing/rhdp-data-seed/Dockerfile
The Docker registry on which we host data images for local development is being decommissioned and therefore we need to migrate to the PSI hosted registry.
* https://issues.jboss.org/browse/MWES-2904
> [MWES-3558] Update local dev to pull data images from PSI Upshift registry

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--dynamic-content-list.html.twig
* n/a
See: https://github.com/redhat-developer/developers.redhat.com/pull/3112/files#diff-13e27bc27aa0565c90e70152bfbd1a37R11
- The dynamic content list component closes and the padding for the component doesn't  extend to all subsequent elements on the page. This can be verified on the homepage.
> [NO ISSUE] BUG: Dynamic content list closing div

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/system/html.html.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/system/page.html.twig
* n/a
- `pf-c-content` is on the `div.layout-container` element on every page in Drupal
- `pf-c-content` is no longer on the <body> element of any page
> [NO ISSUE] Move pf-c-content from body to layout container

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/components/card-grid.twig
* #3143 
Go here: /harmonize/styleguide/
You should see this at the bottom of the page:
with a total of 32px of vertical space between the last row of cards and the CTAs
and 24px of horizontal space between each CTA in the row of CTAs
> [SURGE-3143] Update card grid cta markup

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/components/card.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/node/node--books--card.html.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/node/node--cheat-sheet--card.html.twig
* n/a
- Go to the homepage
- Scroll down a bit to find Cheat Sheet and Ebook cards and verify that the ones with authors set actually display the authors
There is an issue with Card spacing that will be resolved in this ticket in the rhd-frontend repo
https://github.com/redhat-developer/rhd-frontend/issues/229
> Add Authors to Ebook and Cheat Sheet Cards

- _docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.dynamic_content_feed.yml
This updates a visual style class of the Dynamic Content Feed assembly
type from `center` to `centered` to match the styles in the FE repo. I
accidentally committed
https://github.com/redhat-developer/developers.redhat.com/pull/3142
with the `center` class, so this is simply a follow-up to that.
Follow-up to #3142 
The Dynamic Content Feed assembly type has a visual style with the `centered` CSS class name and not the `center` CSS class name.
> [NO ISSUE] Dynamic content feed visual style centered

- _docker/drupal/.gitignore
- _docker/drupal/Dockerfile.mp
- _docker/drupal/dev/build-theme.sh
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhdp2.libraries.yml
This adds the building of rhd.min.js file to the FE build process in
Dockerfile.mp and dev/build-theme.sh and the copying of the file into
the ./rhdp2/js directory. It also declares the file in the
rhdp2.libraries.yml file. Lastly, I've added rhd.min.js to .gitignore
since we do not want to track a file we are building.
Closes #3122 
- `./rhdp2/js/rhd.min.js` exists
- `./rhdp2/js/rhd.min.js` is loaded in the browser
The 'Report a website issue' footer button works and brings up a JIRA iframe like this:
> [SURGE-3122] Load rhd.min.js in rhdp2 theme

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly.html.twig
This adds a container, pf-l-flex, class to a generic assembly.html.twig
and assembly--code-snippet.html.twig. The generic assembly.html.twig
covers assemblies that do not have a specific template, like the Image
assembly type.
This will close #3059 
/coderland/serverless/building-a-serverless-service/
Before, you would see this:
Now, you should see this:
Notice that the assemblies are not respecting the same container width in the Before example, and they are now
> [SURGE-3059] Add container to assembly, Code snippet, Image

- _docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.content_with_image.yml
- _docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.events_hero.yml
- _docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.hero.yml
- _docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.product_download_hero.yml
- _docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.product_try_it_hero.yml
- _docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.rich_text.yml
- _docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.rich_text_columns.yml
- _docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.sign_up_hero.yml
- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/rhd_assemblies.module
- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/rhd_assemblies.updates.inc
*  n/a
| Old class       | New class         | New class (if applicable)  |
| ------------- |-------------| ------------|
| assembly-dark     | dark |  |
| product-hero--dark     | dark |  |
| product-hero--light    | light |  |
| product-hero--slim     | assembly-slim |  |
| center | centered |  |
| assembly-center | centered |  |
| product-signup-hero--dark | dark |  |
| events-hero--light | light |  |
| product-hero--dark-centered | dark | centered |
| product-hero--light-centered | light | centered |
Go here: https://developer-preview-3148.ext.us-west.dc.preprod.paas.redhat.com/assembly/20025/edit
- The Dark visual style should be applied
Go here: https://developer-preview-3148.ext.us-west.dc.preprod.paas.redhat.com/products/eap2/overview
- The Rich Text assembly …
> [DO NOT MERGE][NO ISSUE] Standardize light, dark, centered and assembly-slim visual style class names

- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/rhd_assemblies.module
- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/templates/wordpress-post-tile.html.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--wordpress-post-reference.html.twig
This adds the proper template suggestion(s) and templates to render the
Wordpress Post Reference assembly type as a Card. The actual wordpress
post will render as a Tile, which you will see configured and in the
Twig template name. I am doing this, instead of using the Card because
this implementation has to render the _content_ of the Card vs. the
entire Card, so the markup is actually different. The top-level
container element comes from assembly--wordpress-post-reference.
Closes #3047 
Go here: /openshift/
> [SURGE-3047] Wordpress Post Reference

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/field/field--node--body--topic-page.html.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/node/node--topic-page.html.twig
This changes the markup of the node title and summary in the Topic
Page, default/full view mode, so that it now respects our container
width, .component .pf-l-grid, and matches other components on the page.
Before/current state:
n/a
Go here: https://developer-preview-3181.ext.us-west.dc.preprod.paas.redhat.com/topics/service-mesh/
> [NO ISSUE] Topic Page node title and summary fit container

- _docker/drupal/Dockerfile.mp
This adds back the rhdp theme builds steps. We have implemented a
ThemeNegotiator to load the rhdp theme for only the old,
paragraphs-based Product pages.
There was a regression accidentally introduced here: https://github.com/redhat-developer/developers.redhat.com/commit/bacf9259f6cc977fe157798f7e24e7cc591be988#diff-ed77739bf4e1242389299ce08b6729cdL29
n/a
These routes should load the `rhdp` theme:
https://localhost/products/rhel/
https://localhost/products/rhel/overview/
https://localhost/products/rhel/download/
https://localhost/products/rhel/hello-world/
https://localhost/products/rhel/docs-and-apis/
https://localhost/products/rhel/help/
These routes should load the `rhdp2` theme:
https://localhost/products/openjdk/
https://localhost/products/openjdk/overview/ …
> [NO ISSUE] Build rhdp theme

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhdp2.info.yml
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhdp2.libraries.yml
This loads the PFElement JS file in the head and no longer loads the
onebox JS file explicitly, as that is loaded via the Search JS file.
n/a
- `js/pfelement.umd.min.js` is loaded in the head.
- There are no JS errors in the console on the /search page, or at least none specifically related to our web component implementation.
> [NO ISSUE] Load PFElement in the head

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/menu/menu--topics-menu.html.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/system/page.html.twig
Follow up fixes for top nav -- left/right padding should look right through all breakpoints; All Topics should show up appropriately through all breakpoints.
> Top nav fixes

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhdp2.theme
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/node/node--product--featured-tile.html.twig
https://github.com/redhat-developer/rhd-frontend/issues/354
The CTA link in product cards (on for example: /products) direct to the Download page for the correct product.
Go here: https://developer-preview-3200.ext.us-west.dc.preprod.paas.redhat.com/products/
Click each of the Download CTA button in the Product cards at the top of the page.
You should be directed here:
https://developer-preview-3200.ext.us-west.dc.preprod.paas.redhat.com/products/rhel/download
https://developer-preview-3200.ext.us-west.dc.preprod.paas.redhat.com/products/openshift/download
https://developer-preview-3200.ext.us-west.dc.preprod.paas.redhat.com/products/eap/download
> [SURGE-354] Fix product card cta links

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--product-download-hero.html.twig
We don't want to render the div/CSS Grid item at all if there is no
content because it will squish the display on mobile.
n/a
I meant to push this up before merging this PR https://github.com/redhat-developer/developers.redhat.com/pull/3228 . It was a part of what I just demo'd in the Google Hangouts chat, so it is already approved.
> Don't render grid item without image

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/menu/menu--universal-header.html.twig
This links the logo in the universal nav to https://www.redhat.com
#3268 
Go here: /home
When you click on the logo in the universal nav, it should direct you to https://www.redhat.com
> [SURGE-3268] Redhat.com logo link in universal nav

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhdp2.theme
This adds back some necessary preprocessing for marketing script
variables in html.html.twig, and the commit also adds back a toggle for
Keycloak to provide Keycloak stage on non-Prod environments.
n/a
Testing steps TBD. I am not certain if we can test these marketing integrations on PR environments.
@robpblake For Keycloak, we create the code in the hook below `function rhdp2_library_info_alter(array &$libraries, $extension)` during the Managed Platform epic, but I am confused now because I am certain that we were loading Keycloak stage on local environments without this hook. Are we doing anything in the build layer to toggle that?
> [NO ISSUE] Add back marketing scripts and Keycloak toggle

- _docker/drupal/Dockerfile.mp
- _docker/drupal/dev/build-theme.sh
- _docker/drupal/dev/docker-compose.yml
This commit does a couple of things.
Firstly it removes any reference to the fontawesome stuff from the Drupal build. We are now hosting those assets from a CDN.
Secondly it only calls `npm run-script build` to create the new rhd-frontend assets. We were previously calling `npm run-script styles` and then `npm run-script build`, however the build script additionally calls styles, so this was a duplication
* The site should look as expected
> [#3304] Remove multiple builds of rhd-frontend theme

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
This creates new issue templates for the d.r.c. repo per this week's discussions.
> [NO ISSUE] Add Github issue templates

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/js/drupal-namespace.js
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhd-frontend/src/scripts/@rhd/js/sso.js
- _docker/drupal/managed-platform/ansible/templates/dev/drupal/rhd.settings.php.j2
- _docker/drupal/managed-platform/ansible/templates/local/drupal/rhd.settings.php.j2
- _docker/drupal/managed-platform/ansible/templates/stage/drupal/rhd.settings.php.j2
This commit updates dev, stage and local dev to use the new SSO servers. Additionally it updates the rhd-frontend reference to pull in changes made in that project to support the SSO migration. The changes are also replicated in the legacy rhd-frontend component in this repo.
* Visit Drupal and ensure you can login as a site visitor
* Visit Drupal and ensure you can login as a Drupal content editor
* Visit `/login` and ensure you correctly redirected to the homepage after completing the login process.
> [MWES-3660] Phase 2 of SSO migration

- _tests/e2e/tests/config/wdio.conf.base.js
- _tests/e2e/tests/specs/export/rhd-search.spec.js
This reinstates the mobile search tests that were disabled as part of the `surge` work. 
Closes #3249 
> [#3249] Reinstate search tests for mobile

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhdp.theme
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhdp2.theme
- _docker/drupal/managed-platform/ansible/templates/dev/drupal/rhd.settings.php.j2
- _docker/drupal/managed-platform/ansible/templates/local/drupal/rhd.settings.php.j2
- _docker/drupal/managed-platform/ansible/templates/preview/drupal/rhd.settings.php.j2
- _docker/drupal/managed-platform/ansible/templates/prod/drupal/rhd.settings.php.j2
- _docker/drupal/managed-platform/ansible/templates/stage/drupal/rhd.settings.php.j2
Makes available the SWEL API endpoint for user registration event management post SSO merge.
This does not change any work-flow, merely makes available the configuration for future work.
* https://issues.jboss.org/browse/MWES-3660
* Please ensure the following variable is available via the JS console: `drupalSettings.rhd.swel.url`. For the preview environment its value should be: `https://api.developers.stage.redhat.com/swel`
> [MWES-3660] Expose SWEL API endpoint for user registration event integration

- .gitmodules
The `.gitmodules` file is no longer required since `rhd-frontend` was bought into this repo. This simply deletes the file.
* Build should go green.
> [No Issue] Removed .gitmodules file from the repo

- _tests/e2e/Dockerfile.mp
- _tests/e2e/Jenkinsfile
- _tests/e2e/docker-compose.yml
- _tests/e2e/tests/specs/support/utils/Utils.js
By migrating to a Jenkins pipeline we can remove our dependency on Ruby in the d.r.c project which will help us further clean-up the repo. Additionally it helps us to make our Jenkins setup
much easier to recover and is captured as part of our migration to a PSI Jenkins instance
This PR merely installs the supporting infrastructure to make this change. It does not change the way in which the tests are currently executed and as such this build should go green with no further changes.
* https://issues.jboss.org/browse/MWES-3564
> [MWES-3564] Support for running e2e tests as a Jenkins pipeline.

- _docker/drupal/dev/README.md
- _docker/drupal/dev/local-config.sh.example
- _docker/drupal/dev/run-drupal.sh
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_comment-list-card.scss
https://github.com/redhat-developer/developers.redhat.com/issues/3298
Fixes #3298 
Go to any page with disqus comments and check no text is overlapping the comment box.
On a local dev environment, there is now an option to prevent the startup script from tying to login to get the docker container if you have a no expire key. Instructions added to the readme
> option to skip docker login and fix comment list

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_component-base.scss
Fixes #3374 
Go to /training/ the pagination should sit inline with the content at all screen sizes
> Assembly pagination is outside of content area #3374

- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/templates/wordpress-post-tile.html.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_cards.scss
Fixed #3282 
on the homepage check on mobile and see that the images on the build here section ae centred with a blurred background image .
> add blured image for background on wordpress cards

- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.katacoda_individual_lesson.default.yml
This commit updates the Default view mode of the Katacoda Individual
Course node type so that Purpose Attributes are no longer displayed.
#3336 
Do this: Log in to your Drupal account
Go here: /courses/openshift/playground-openshift311/edit
Do this: Add Purpose Attributes under the Fields tab and publish a revision to the node.
You should **not** see Purpose Attributes listed across the bottom of the Katacoda Individual Lesson as links, as you would currently on Prod.
> [DEVELOPER-3336] Purpose Attributes on Katacoda Individual Courses

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhdp.theme
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhdp2.theme
- _docker/drupal/managed-platform/ansible/templates/dev/drupal/rhd.settings.php.j2
- _docker/drupal/managed-platform/ansible/templates/local/drupal/rhd.settings.php.j2
- _docker/drupal/managed-platform/ansible/templates/preview/drupal/rhd.settings.php.j2
- _docker/drupal/managed-platform/ansible/templates/prod/drupal/rhd.settings.php.j2
- _docker/drupal/managed-platform/ansible/templates/stage/drupal/rhd.settings.php.j2
This commit adds the endpoint for the Fusion API for the new search to the Drupal configuration and then exposes them for the frontend integration on the
drupalSettings Javascript object.
* https://issues.jboss.org/browse/MWES-3382
* Please visit the site and ensure the following variable is available on the Javascript console:
* `drupalSettings.rhd.fusion.url` with the value `https://api.developers.stage.redhat.com/search`
> [MWES-3382] Add Fusion API endpoints to Drupal configuration

- Jenkinsfile.psi
This commit adds a new Jenkinsfile to the project root to support our migration to PSI Jenkins instance for triggering of pull request builds. It does not replace the current Jenkinsfile on the project as the migration needs to be phased and we also need the ability to rollback if things don't work out.
In addition this makes no changes in the way our pull request builds are triggered. This will be done once this change has been merged.
A further update will merge these changes into the main Jenkinsfile and remove the Jenkinsfile.psi once the migration to our PSI Jenkins instance is complete
and verified.
* https://issues.jboss.org/browse/MWES-3562
> [MWES-3562] Add Jenkinsfile to support migration of PR trigger to PSI Jenkins

- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.books.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.cheat_sheet.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.katacoda_course.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.katacoda_individual_lesson.default.yml
This changes the moderation state field widget to Moderation State for
the following 4 node types: Books, Cheat Sheets, Katacoda Course and
Katacoda Individual Lesson.
#3385 
Go here: https://developer-preview-3384.ext.us-west.dc.preprod.paas.redhat.com/books/adventures-aboard-kluster-kruise-ship/old/edit
Go here: https://developer-preview-3384.ext.us-west.dc.preprod.paas.redhat.com/cheat-sheets/advanced-linux-commands/old/edit
Go here: https://developer-preview-3384.ext.us-west.dc.preprod.paas.redhat.com/courses/openshift/playground-openshift311/edit
Go here: https://developer-preview-3384.ext.us-west.dc.preprod.paas.redhat.com/courses/modern-app-dev/edit
> [DEVELOPER-3385] All Content Types use Moderation State Widget

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--node-reference.html.twig
This resolves an issue where Node Reference cards, in static content
bands, had too much spacing between cards in the card grid.
https://github.com/redhat-developer/rhd-frontend/issues/347
Go here: https://localhost/topics/kubernetes/
and
NOTE: I created a follow-up issue for that right margin on the cards on mobile here: https://github.com/redhat-developer/rhd-frontend/issues/384
> [SURGE-347] Node Reference Cards spacing

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhdp.libraries.yml
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/rhdp.theme
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhdp2.libraries.yml
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhdp2.theme
- _docker/drupal/managed-platform/ansible/templates/prod/drupal/rhd.settings.php.j2
Migrates developers.redhat.com to use the new SSO servers.
* https://issues.jboss.org/browse/MWES-3661
* Please view the  site source and ensure `keycloak.js` is loaded from `sso.redhat.com`.
* Please visit the site and ensure you can login as a site visitor
* Please visit the site and ensure you can login as Drupal admin using the SSO login.
> [DO NOT MERGE] [MWES-3661] Update prod to use new SSO servers

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/scripts/js/rhd/5-sso.js
Adds a replacement for the current registration cookie `rhd_registered` to work with the new SSO
* Upon successful login the SWEL service is called to check registration date
* IF registration was within 24 hours
* AND the `rhd_logged` cookie is not set
* Set the `rhd_registration` cookie
> Add new generation for rhd_registered cookie

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/css/rhdp2.css
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/data/components/curated-links/context/base/background-gray.toml
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/data/components/curated-links/context/base/center-aligned.toml
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/data/components/curated-links/context/base/default.toml
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/data/components/curated-links/context/base/nav-menu.toml
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/data/components/curated-links/context/base/no-padding-bottom.toml
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/data/components/curated-links/context/base/no-padding-top.toml
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/data/components/curated-links/context/base/two-col.toml
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/data/components/curated-links/context/base/with-additional-content.toml
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/data/components/curated-links/variants.toml
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/_mixins.scss
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/_rhd-theme.scss
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/colors/_rhd-brand.scss
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_component-base.scss
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_curated-links.scss
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_rhd-c-two-col-hero-layout.scss
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_rhd-divider.scss
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhdp2.theme
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--curated-links.html.twig
Estimate: 5
Fixes #3418 
This should also Fixes #3438 
Create or edit an existing page
Add or edit the curated links assembly
Under visual style (or display type) select render as horizontal nav from the drop down menu
Input a couple of test links.
Save and preview page
Expected behavior
When selecting the "render as horizontal nav" style, the links should be displayed in a single horizontal band with no arrow icon shown next to each link.
Currently, the style just shows the links as the standard single column link list.
> Fix horizontal nav feature

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhdp2.theme
[RHDX-54](https://projects.engineering.redhat.com/browse/RHDX-54)
Viewing a node with an Assembly of type Event Hero causes a PHP warning to be written to the logs. 
The current only content that this affects is node 23605, or https://localhost/testingandtsting/.
1. View the content /testingandtsting/ OR /node/23605 OR create and view content with an Event Hero assembly type.
2. Check the logs for the warning (Reports -> Recent Log Messages)
3. There should be no logs related to Undefined index: field_description.
> [RHDX-54] Undefined index: field_description in rhdp2_preprocess_node

- _docker/drupal/drupal-filesystem/web/config/sync/user.role.content_creator.yml
This grants the content creator role access to create Media entities.
This bug was reported by Marco Rizzi while working on the RHAMT product
page.
n/a
Go here: /user/login
Do this:
* Log in to a Drupal user account with only the content creator role
Go to the RHAMT node edit form: /node/37375/edit
Do this:
* Click on the Fields tab and scroll down to the Individual Sub Pages field and open the panel if it is closed
* Click on the Edit button for the Overview paragraph
* Scroll down to the PRODUCT FEATURE IMAGE AND TEXT section and then the Media Reference section within that section and click on the green Add Media button
* Click on the Upload tab and then click on the Choose File button to pick a file to upload from your computer
* Fill out a file/media name and any other required …
> [NO ISSUE] Grant content creators access to create Media

- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/rhd_assemblies.services.yml
- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Plugin/AssemblyBuild/ProductDownloadHeroBuild.php
- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Plugin/AssemblyBuild/ProductDownloadListBuild.php
- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Service/DownloadManagerApi.php
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--product-download-list.html.twig
This adds a Drupal cache bin and drupal_static() caching to our Download
Manager interactions. This should significantly improve the performance
of, most notably, the product download pages, but more generally pages
that reference Product Download Hero assembl(ies) and/or Product
Download List assembl(ies).
* Related to: https://projects.engineering.redhat.com/browse/RHDX-67
* This implements a cache bin for Download Manager responses by Product ID.
TODO: We will need to implement a configurable TTL in the future. It is currently set, in code, to an hour
* This will provide static caching of the Download Manager response, getProductById() method. This should considerably improve the performance of Product download pages, almost all of which make multiple getProductById() calls i.e. …
> [RHDX-67] Add Drupal caching to Product downloads

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_product-download-hero.scss
https://projects.engineering.redhat.com/browse/RHDX-153
Go to https://developer-preview-3464.ext.us-west.dc.preprod.paas.redhat.com/products/fuse/overview and check the 'download tooling' link and the paragraph text 'Distributed, cloud-native integration platform' in the hero is white.
> [RHDX-153] add dark theme to hero download

- _docker/drupal/managed-platform/ansible/templates/common/apache/drupal.conf.j2
This small change to the Drupal Apache configuration further tightens access to key Drupal pages. 
* N/A
* Verify that you can log in as expected using the SSO login
* Log in to the Drupal container and ensure `drush cron` works as expected
* Ensure that the following pages result in a 403 Forbidden response:
* install.php
* cron.php
* authorize.php
* upgrade.php
* xmlrpc.php
> [No Issue] Further tighten access to key Drupal resources

- Jenkinsfile
We have two Jenkinsfiles in the root of the repo. `Jenkinsfile` was for the legacy PR pipeline before we migrated to the PSI upshift infrastructure. `Jenkinsfile.psi` supported the migration to PSI.
We can now start to remove this duplication. First step here is to simply replace the contents of `Jenkinsfile` with that of `Jenkinsfile.psi`. Once this is done and merged, the pipelines can be updated to use `Jenkinsfile` and the `Jenkinsfile.psi` can be deleted.
* N/A
* The build should go green.
> [No Issue] Begin removal of Jenkinsfile duplication

- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/templates/wordpress-post-compact-dynamic-article-list-item.html.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/components/card.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/node/node--article--compact-dynamic-article-list-item.html.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/node/node--video-resource--compact-dynamic-article-list-item.html.twig
This comments out the Disqus HTML markup on 3 Twig templates: the card
component-level template and 2 node type implementations of the Compact
Dynamic Article List. This should prevent any Disqus API calls from
being made. This is a temporary measure until we can actually implement
the comment count feature on these cards and compact dynamic article
lists. Since this functionality is not present currently, there is no
reason to make these API  calls, and we actually benefit from preventing
the calls from taking place (currently) to cut back on network calls and
reduce the probability of hitting our Disqus API quota.
* https://projects.engineering.redhat.com/browse/RHDX-233
* No Disqus calls are made  to fetch  comments for any Card-like components or Compact Dynamic Article List …
> [RHDX-233] Disable disqus calls on cards and lists

- _docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.layout_two_col_left_sidebar.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.assembly.layout_two_col_left_sidebar.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.assembly.layout_two_col_left_sidebar.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.layout_two_col_left_sidebar.field_column_1.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.layout_two_col_left_sidebar.field_column_2.yml
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_rhd-c-two-col-hero-layout.scss
This changes the way that Layout: 2 Column assembly type will display
content. We want to use this assembly type to support any kind of
assembly-based, 2 column layouts, not just a left sidebar scenario. To
do so, I have created 2 visual styles: Left sidebar and right sidebar.
The default behavior, now, will be an evenly split 6:6 layout.
* https://projects.engineering.redhat.com/browse/RHDX-248
Relates to: https://projects.engineering.redhat.com/browse/RHDX-179
If/when merged, this will require a content update (update the visual style to Left Sidebar) of the 1 referenced Layout: Two Column assembly on Prod (the homepage). We could write a migration for that I suppose, but since there is only 1, it seems like a better use of time to just update the content manually.
> [RHDX-248] Update Layout: 2 Column assembly type display

- _docker/drupal/drupal-filesystem/composer.json
- _docker/drupal/drupal-filesystem/composer.lock
- _docker/drupal/drupal-filesystem/web/config/sync/imagecache_external.settings.yml
There is a required cron interval config keyvalue that we apparently had
never set for the ImageCache External module. I tested this against the
1.1 and 1.2 releases locally and it _seemed_ like the field was required
in both releases. I am not sure, at least at this point in my debugging,
why we started to encounter these cron failures at this point, instead
of at an earlier date whenever this required value was introduced to the
contrib module. Setting a value resolves the error that arises during
cron execution though. I will verify this on the PR build once a build
either fails or completes successfully by reviewing the logs and testing
the command(s) against the commandline of the PR environment.
* https://projects.engineering.redhat.com/browse/RHDX-291
* Builds  succesfully
* Tests …
> [RHDX-291] Set required cron interval ImageCache External

- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_eloqua_embed/templates/rhd-eloqua-embed-page.html.twig
[RHDX-293](https://projects.engineering.redhat.com/browse/RHDX-293)
The Eloqua forms that display the Country field should provide an Opt In radio selection after selecting specific countries.
1. - See the test form provided here: https://developers.redhat.com/node/215345/
2. - Create test content: Assembly Page node, Eloqua Form assembly using the contents of the 215345 in production
3. - Select a GDPR country such as  "Austria",  "Belgium", "Bulgaria".
4. - Verify an Opt In field appears with the label "Red Hat may use your personal data to inform you about its products, services, and events. You may withdraw your consent any time (see Privacy Statement for details)."
5. - Submit the form and verify that you do not have a form validation error.
Test the form with and without the visual …
> [RHDX-293] Show Opt In Field on Eloqua Form 

- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Service/DownloadManagerApi.php
This is a change to properly inject EntityTypeManagerInterface as a
dependency, instead of EntityTypeManager. I discovered this issue while
debugging some performance issues when I tried to enable and use the
webprofiler module. It will result in a fatal error because we are not
properly injecting the interface.
* https://projects.engineering.redhat.com/browse/RHDX-333
* I will be creating a merge request to Compose soon because it also includes 1 instance of this same issue. I will track that in the JIRA issue.
* Everything works exactly the same as it did before
* Unfortunately, you will not be able to test this next step until we make a change to the Compose (contrib) module, and we cannot use the latest Compose branch until we are on Drupal core 8.8.x. This is the scenario, though, …
> [RHDX-333] Make DownloadManagerApi use EntityTypeManagerInterface

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhdp2.theme
The conditional logic we have in hook_theme_suggestions_alter() is not
properly validating that we have retrieved a Node object in $node. I
have adjusted the logic to ensure that we've actually fetched an object
that is an instance of NodeInterface. This should resolve an issue that
arises when trying to view Node revisions.
```
Error: Call to a member function hasField() on string in rhdp2_theme_suggestions_page_alter() (line 80 of themes/custom/rhdp2/rhdp2.theme).
```
* https://projects.engineering.redhat.com/browse/RHDX-360
Go here: /node/213906/revisions/17508836/view/
You should not see this:
```
The website encountered an unexpected error. Please try again later.
Error: Call to a member function hasField() on string in rhdp2_theme_suggestions_page_alter() (line 80 of …
```
> [RHDX-360] Fix theme suggestions conditional logic

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/paragraph/paragraph--help.html.twig
This adds a 'How do I report an issue' section to the RHAMT Product's
Help sub-page. This content is added via a conditional, targeting the
field_product_machine_name value.
* https://projects.engineering.redhat.com/browse/RHDX-367
Go to https://developer-preview-3528.ext.us-west.dc.preprod.paas.redhat.com/products/rhamt/help
You should see a new section with the following text:
> How do I report an issue?
> 
> Our issue tracking system is available on https://issues.redhat.com/projects/WINDUP/issues. You may use your access.redhat.com user account to login to this system. To find out how to use the issue tracking system, refer to https://confluence.atlassian.com/display/JIRA/JIRA+Documentation
Go to https://developer-preview-3528.ext.us-west.dc.preprod.paas.redhat.com/products/rhel/help …
> [RHDX-367] Add a How do I report an issue section to RHAMT

- _docker/drupal/drupal-filesystem/web/config/sync/assembly.assembly_type.call_to_action.yml
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_call-to-action.scss
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_component-base.scss
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/components/_component-styles.scss
https://projects.engineering.redhat.com/browse/RHDX-412
check cat components on 
https://docs.google.com/spreadsheets/d/1cD6W-nwd4wqyhMclD_kqJffnmOvjM_RNA8sT_C-UXoc/edit#gid=0
Test any CTA_assembly you should have the option for dark theme and light-blue theme, also left centre and right align.
Now if you have a background Image you can select dark to have white text and leave without a theme class to maintain dark text if the background image is light.
will require content changes need to discuss with UX , plan to make changes (Alistair) 40 components.
Tc confirm Alistair will make the changes to the live content after release.
> [RHDX-412] Rework cta styles and add light-blue theme

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/js/show-more.js
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/scripts/js/rhd/terms-and-conditions.js
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhdp2.theme
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/assembly/assembly--call-to-action.html.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/node/node--article--full.html.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/node/node--video-resource--full.html.twig
[RHDX-425](https://projects.engineering.redhat.com/browse/RHDX-425?filter=-1)
Any usage of `.hide` in  twig templates, hooks or js files intended to hide/show elements on the page should be replaced with `.pf-u-hidden`, now that Foundation is removed. 
- Check video resource;  There should not be calls to slideshare.net if there is no slide deck.
- Check show more text on Videos and Learning Paths
- Simplified table of contents twig classes; Check that it hides when its supposed to (field_hide_toc)
There is some usage of `.hide`  in the rhdp-searchapp, I did not update that usage since the class exists within that web component.
/videos/youtube/FC3jSKgTNK0/
/videos/youtube/ajlY_qiIunA/
/videos/youtube/ywrA0312bOo/
/videos/youtube/B9MdhWCvDCM/
/videos/youtube/Cv8_EHQgUZ4/
> [RHDX-425] Update usage of hide class

- _docker/drupal/Dockerfile.mp
This commit updates to the rhel-76.4 version of the developer base image which has been updated to incorporate changes in IT PaaS entitlement management when building images in Managed Platform
* Log in to the Drupal container and verify the version of Ansible is 2.9 by using `ansible --version` from the command line.
> [No Issue] Update to rhel-76.4 version of base image

- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.node.topic_page.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.topic_page.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.topic_page.field_hide_title.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.node.topic_page.field_sections.yml
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhd-frontend/src/styles/rhd-theme/_pf4-custom-globals.scss
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/node/node--topic-page.html.twig
https://projects.engineering.redhat.com/browse/RHDX-458
https://projects.engineering.redhat.com/browse/RHDX-459
A topic page now has a field to hide the title.
When the field is active, the Title and Body of the topic page should no longer appear on the rendered page.
I also repaired a Patternfly css override to reset images back to height: auto.
Images embedded into assemblies that have width/height attributes should render in the correct ratio.
> [RHDX-548] Add hide title field to Topics page

- _tests/e2e/tests/specs/export/rhd-adobe-ddo-spec.js
The /openshift route now redirects to
https://developers.redhat.com/products/openshift/getting-started. As a
result, one of the assertions in the rhd-adobe-ddo-spec.js file is
failing. Now that this Openshift is in a Product page, it will be
covered by the Product page e2e test(s), and we can remove this
assertion.
* n/a
* All of the tests pass
> [NO ISSUE] Remove /openshift Adobe ddo e2e test

- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp/templates/system/html.html.twig
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhdp2.libraries.yml
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/templates/system/html.html.twig
This makes the following changes to asset/libraries loading: we will now
load trustarc in the rhdp theme (it previously/curently is not), the
JIRA issue collector will load in the at the bottom of the <body>,
trustarc will not load on local environments.
* https://projects.engineering.redhat.com/browse/RHDX-450
* TrustArc scripts/assets do no load on local environments
* TrustArc scripts/assets and functionality continues to behave exactly as it does now on all non-local environments
* TrustArc now loads on the `rhdp` theme (old, paragraphs-based Product pages e.g. RHEL)
* The JIRA issue collector loads at the bottom of the <body>
> [RHDX-450] Do not load trustarc on local environment

- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_form_display.assembly.compact_dynamic_article_list.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.assembly.compact_dynamic_article_list.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/field.field.assembly.compact_dynamic_article_list.field_number_of_posts.yml
- _docker/drupal/drupal-filesystem/web/modules/custom/rhd_assemblies/src/Plugin/AssemblyBuild/CompactDynamicArticleListBuild.php
This adds a field to the Compact Dynamic Article List assembly type, the
same field that is on the Dynamic Content Feed, that allows an editor to
configure the number of articles displayed in the list. The current
number of articles displayed is 8. This provides a default of 8, but
allows an editor to set the valuable anywhere between 4 to 10.
* https://projects.engineering.redhat.com/browse/RHDX-465
Go to the [homepage](https://developer-preview-3565.ext.us-west.dc.preprod.paas.redhat.com/) and verify that the list in the left sidebar, at the very top of the page still renders as expected.
* Go to the [homepage edit form](https://developer-preview-3565.ext.us-west.dc.preprod.paas.redhat.com/home/edit/) and observe the Number of Posts field
* Set some number of posts between 4 and 10
* …
> [RHDX-465] Compact Dynamic Article List Length

- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.assembly.featured_products.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.books.default.yml
- _docker/drupal/drupal-filesystem/web/config/sync/core.entity_view_display.node.product.card.yml
- _docker/drupal/drupal-filesystem/web/themes/custom/rhdp2/rhdp2.theme
The related products field on the Books node type now renders the
referenced Product nodes with the Card view mode. This required some
minor changes to make the Card view mode, for the Product node type,
display as intended.
I also decided to have the Featured Products assembly type render the
referenced Products using the Card view mode since it is more intuitive
that the Featured Tile view mode, and we eventually want to eliminate
card-related usage of the Featured Tile or Tile view modes in favor of
Card.
* https://projects.engineering.redhat.com/browse/RHDX-471
* [Edit Knative Cookbook](https://developer-preview-3564.ext.us-west.dc.preprod.paas.redhat.com/books/knative-cookbook/old/edit) and add Red Hat Enterprise Linux as a reference in the Related Product field
* Save the node to …
> [RHDX-471] Related Products field renders as Card
